/* adduser.vala.c generated by valac 0.42.6, the Vala compiler
 * generated from adduser.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gee.h>


#define TYPE_ADD_USER_DIALOG (add_user_dialog_get_type ())
#define ADD_USER_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ADD_USER_DIALOG, AddUserDialog))
#define ADD_USER_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ADD_USER_DIALOG, AddUserDialogClass))
#define IS_ADD_USER_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ADD_USER_DIALOG))
#define IS_ADD_USER_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ADD_USER_DIALOG))
#define ADD_USER_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ADD_USER_DIALOG, AddUserDialogClass))

typedef struct _AddUserDialog AddUserDialog;
typedef struct _AddUserDialogClass AddUserDialogClass;
typedef struct _AddUserDialogPrivate AddUserDialogPrivate;
enum  {
	ADD_USER_DIALOG_0_PROPERTY,
	ADD_USER_DIALOG_NUM_PROPERTIES
};
static GParamSpec* add_user_dialog_properties[ADD_USER_DIALOG_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block14Data Block14Data;

#define TYPE_APP_WIN (app_win_get_type ())
#define APP_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APP_WIN, AppWin))
#define APP_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APP_WIN, AppWinClass))
#define IS_APP_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APP_WIN))
#define IS_APP_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APP_WIN))
#define APP_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APP_WIN, AppWinClass))

typedef struct _AppWin AppWin;
typedef struct _AppWinClass AppWinClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_CHAT_CLIENT (chat_client_get_type ())
#define CHAT_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CHAT_CLIENT, ChatClient))
#define CHAT_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CHAT_CLIENT, ChatClientClass))
#define IS_CHAT_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CHAT_CLIENT))
#define IS_CHAT_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CHAT_CLIENT))
#define CHAT_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CHAT_CLIENT, ChatClientClass))

typedef struct _ChatClient ChatClient;
typedef struct _ChatClientClass ChatClientClass;

#define TYPE_USER_DATA (user_data_get_type ())
typedef struct _UserData UserData;

#define TYPE_MY_GRID (my_grid_get_type ())
#define MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_GRID, MyGrid))
#define MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_GRID, MyGridClass))
#define IS_MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_GRID))
#define IS_MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_GRID))
#define MY_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_GRID, MyGridClass))

typedef struct _MyGrid MyGrid;
typedef struct _MyGridClass MyGridClass;
typedef struct _MyGridPrivate MyGridPrivate;

#define TYPE_USER_MSG (user_msg_get_type ())
typedef struct _UserMsg UserMsg;
#define _user_data_free0(var) ((var == NULL) ? NULL : (var = (user_data_free (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _AddUserDialog {
	GObject parent_instance;
	AddUserDialogPrivate * priv;
	GtkDialog* dlg1;
	GtkEntry* name;
	GtkEntry* pwd;
	gint birthyear;
	GtkEntry* desc;
	gint sex;
};

struct _AddUserDialogClass {
	GObjectClass parent_class;
};

struct _Block14Data {
	int _ref_count_;
	AddUserDialog* self;
	GtkEntry* cfpwd;
	GtkComboBoxText* yearSelect;
	GtkComboBoxText* sexSelect;
};

struct _UserData {
	gint64 Id;
	gchar* Name;
	gint Sex;
	gint Age;
	gchar* Desc;
};

struct _UserMsg {
	gint64 id;
	gint sex;
	gchar* name;
	gchar* desc;
	gint age;
	gchar* msg_offline;
	gchar* timestamp_offline;
};

struct _MyGrid {
	GObject parent_instance;
	MyGridPrivate * priv;
	GtkEntry* port1;
	GtkGrid* mygrid;
	GeeHashMap* frds1;
	GtkCssProvider* provider1;
	GtkCssProvider* mark1;
	GtkCssProvider* name_css;
	gint mark_num;
	GtkCssProvider* button1;
	GtkCssProvider* link_css1;
	GtkButton* strangers_btn;
	GtkButton* user_btn;
	GtkButton* msend_btn;
	gchar* man_icon;
	gchar* woman_icon;
	gint64 uid;
	gint16 usex;
	gchar* uname;
	gchar* udesc;
	gint16 uage;
	gchar* host;
};

struct _MyGridClass {
	GObjectClass parent_class;
};


static gpointer add_user_dialog_parent_class = NULL;
extern AppWin* app;
extern ChatClient* client;
extern MyGrid* grid1;

GType add_user_dialog_get_type (void) G_GNUC_CONST;
AddUserDialog* add_user_dialog_new (void);
AddUserDialog* add_user_dialog_construct (GType object_type);
static Block14Data* block14_data_ref (Block14Data* _data14_);
static void block14_data_unref (void * _userdata_);
GType app_win_get_type (void) G_GNUC_CONST;
static void __lambda78_ (Block14Data* _data14_);
static void ___lambda78__gtk_combo_box_changed (GtkComboBox* _sender,
                                         gpointer self);
static void __lambda79_ (Block14Data* _data14_);
static void ___lambda79__gtk_combo_box_changed (GtkComboBox* _sender,
                                         gpointer self);
static void __lambda80_ (Block14Data* _data14_,
                  gint rid);
GType chat_client_get_type (void) G_GNUC_CONST;
gint chat_client_add_user (ChatClient* self,
                           const gchar* name,
                           const gchar* pwd,
                           gint sex,
                           gint birthyear,
                           const gchar* desc);
GType user_data_get_type (void) G_GNUC_CONST;
UserData* user_data_dup (const UserData* self);
void user_data_free (UserData* self);
void user_data_copy (const UserData* self,
                     UserData* dest);
void user_data_destroy (UserData* self);
UserData* chat_client_login (ChatClient* self,
                             const gchar* name,
                             const gchar* pwd);
GType my_grid_get_type (void) G_GNUC_CONST;
GType user_msg_get_type (void) G_GNUC_CONST;
UserMsg* user_msg_dup (const UserMsg* self);
void user_msg_free (UserMsg* self);
void user_msg_copy (const UserMsg* self,
                    UserMsg* dest);
void user_msg_destroy (UserMsg* self);
void save_name (const gchar* name1);
void chat_client_get_friends_async (ChatClient* self);
static void ___lambda80__gtk_dialog_response (GtkDialog* _sender,
                                       gint response_id,
                                       gpointer self);
void add_user_dialog_show (AddUserDialog* self);
static void add_user_dialog_finalize (GObject * obj);


static Block14Data*
block14_data_ref (Block14Data* _data14_)
{
	g_atomic_int_inc (&_data14_->_ref_count_);
	return _data14_;
}


static void
block14_data_unref (void * _userdata_)
{
	Block14Data* _data14_;
	_data14_ = (Block14Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data14_->_ref_count_)) {
		AddUserDialog* self;
		self = _data14_->self;
		_g_object_unref0 (_data14_->sexSelect);
		_g_object_unref0 (_data14_->yearSelect);
		_g_object_unref0 (_data14_->cfpwd);
		_g_object_unref0 (self);
		g_slice_free (Block14Data, _data14_);
	}
}


static void
__lambda78_ (Block14Data* _data14_)
{
	AddUserDialog* self;
	gchar* title = NULL;
	GtkComboBoxText* _tmp0_;
	gchar* _tmp1_;
	self = _data14_->self;
	_tmp0_ = _data14_->yearSelect;
	_tmp1_ = gtk_combo_box_text_get_active_text (_tmp0_);
	title = _tmp1_;
	self->birthyear = (gint) g_ascii_strtoll (title, NULL, 0);
	_g_free0 (title);
}


static void
___lambda78__gtk_combo_box_changed (GtkComboBox* _sender,
                                    gpointer self)
{
	__lambda78_ (self);
}


static void
__lambda79_ (Block14Data* _data14_)
{
	AddUserDialog* self;
	gint _tmp0_;
	gint _tmp1_;
	self = _data14_->self;
	_tmp0_ = gtk_combo_box_get_active ((GtkComboBox*) _data14_->sexSelect);
	_tmp1_ = _tmp0_;
	self->sex = _tmp1_ + 1;
}


static void
___lambda79__gtk_combo_box_changed (GtkComboBox* _sender,
                                    gpointer self)
{
	__lambda79_ (self);
}


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


static void
__lambda80_ (Block14Data* _data14_,
             gint rid)
{
	AddUserDialog* self;
	self = _data14_->self;
	if (rid == 2) {
		GtkEntry* _tmp0_;
		const gchar* _tmp1_;
		const gchar* _tmp2_;
		GtkEntry* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
		ChatClient* _tmp7_;
		GtkEntry* _tmp8_;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		GtkEntry* _tmp11_;
		const gchar* _tmp12_;
		const gchar* _tmp13_;
		gint _tmp14_;
		gint _tmp15_;
		GtkEntry* _tmp16_;
		const gchar* _tmp17_;
		const gchar* _tmp18_;
		UserData* u = NULL;
		ChatClient* _tmp20_;
		GtkEntry* _tmp21_;
		const gchar* _tmp22_;
		const gchar* _tmp23_;
		GtkEntry* _tmp24_;
		const gchar* _tmp25_;
		const gchar* _tmp26_;
		UserData* _tmp27_;
		UserData* _tmp28_;
		ChatClient* _tmp58_;
		GtkDialog* _tmp59_;
		AppWin* _tmp60_;
		_tmp0_ = _data14_->cfpwd;
		_tmp1_ = gtk_entry_get_text (_tmp0_);
		_tmp2_ = _tmp1_;
		_tmp3_ = self->pwd;
		_tmp4_ = gtk_entry_get_text (_tmp3_);
		_tmp5_ = _tmp4_;
		if (g_strcmp0 (_tmp2_, _tmp5_) != 0) {
			GtkDialog* _tmp6_;
			_tmp6_ = self->dlg1;
			gtk_window_set_title ((GtkWindow*) _tmp6_, _ ("Confirm Fail!"));
			return;
		}
		_tmp7_ = client;
		_tmp8_ = self->name;
		_tmp9_ = gtk_entry_get_text (_tmp8_);
		_tmp10_ = _tmp9_;
		_tmp11_ = self->pwd;
		_tmp12_ = gtk_entry_get_text (_tmp11_);
		_tmp13_ = _tmp12_;
		_tmp14_ = self->sex;
		_tmp15_ = self->birthyear;
		_tmp16_ = self->desc;
		_tmp17_ = gtk_entry_get_text (_tmp16_);
		_tmp18_ = _tmp17_;
		if (chat_client_add_user (_tmp7_, _tmp10_, _tmp13_, _tmp14_, _tmp15_, _tmp18_) == 0) {
			GtkDialog* _tmp19_;
			_tmp19_ = self->dlg1;
			gtk_window_set_title ((GtkWindow*) _tmp19_, _ ("Register Fail!"));
			return;
		}
		_tmp20_ = client;
		_tmp21_ = self->name;
		_tmp22_ = gtk_entry_get_text (_tmp21_);
		_tmp23_ = _tmp22_;
		_tmp24_ = self->pwd;
		_tmp25_ = gtk_entry_get_text (_tmp24_);
		_tmp26_ = _tmp25_;
		_tmp27_ = chat_client_login (_tmp20_, _tmp23_, _tmp26_);
		u = _tmp27_;
		_tmp28_ = u;
		if (_tmp28_ != NULL) {
			FILE* _tmp29_;
			MyGrid* _tmp30_;
			UserData* _tmp31_;
			gint64 _tmp32_;
			MyGrid* _tmp33_;
			UserData* _tmp34_;
			const gchar* _tmp35_;
			gchar* _tmp36_;
			MyGrid* _tmp37_;
			UserData* _tmp38_;
			gint _tmp39_;
			MyGrid* _tmp40_;
			UserData* _tmp41_;
			gint _tmp42_;
			MyGrid* _tmp43_;
			UserData* _tmp44_;
			const gchar* _tmp45_;
			gchar* _tmp46_;
			MyGrid* _tmp47_;
			GtkButton* _tmp48_;
			UserData* _tmp49_;
			const gchar* _tmp50_;
			gchar* _tmp51_;
			gchar* _tmp52_;
			GtkEntry* _tmp53_;
			const gchar* _tmp54_;
			const gchar* _tmp55_;
			_tmp29_ = stdout;
			fprintf (_tmp29_, "login ok\n");
			_tmp30_ = grid1;
			_tmp31_ = u;
			_tmp32_ = (*_tmp31_).Id;
			_tmp30_->uid = _tmp32_;
			_tmp33_ = grid1;
			_tmp34_ = u;
			_tmp35_ = (*_tmp34_).Name;
			_tmp36_ = g_strdup (_tmp35_);
			_g_free0 (_tmp33_->uname);
			_tmp33_->uname = _tmp36_;
			_tmp37_ = grid1;
			_tmp38_ = u;
			_tmp39_ = (*_tmp38_).Sex;
			_tmp37_->usex = (gint16) _tmp39_;
			_tmp40_ = grid1;
			_tmp41_ = u;
			_tmp42_ = (*_tmp41_).Age;
			_tmp40_->uage = (gint16) _tmp42_;
			_tmp43_ = grid1;
			_tmp44_ = u;
			_tmp45_ = (*_tmp44_).Desc;
			_tmp46_ = g_strdup (_tmp45_);
			_g_free0 (_tmp43_->udesc);
			_tmp43_->udesc = _tmp46_;
			_tmp47_ = grid1;
			_tmp48_ = _tmp47_->user_btn;
			_tmp49_ = u;
			_tmp50_ = (*_tmp49_).Name;
			_tmp51_ = g_strconcat (_ ("About: "), _tmp50_, NULL);
			_tmp52_ = _tmp51_;
			gtk_button_set_label (_tmp48_, _tmp52_);
			_g_free0 (_tmp52_);
			_tmp53_ = self->name;
			_tmp54_ = gtk_entry_get_text (_tmp53_);
			_tmp55_ = _tmp54_;
			save_name (_tmp55_);
		} else {
			GtkDialog* _tmp56_;
			FILE* _tmp57_;
			_tmp56_ = self->dlg1;
			gtk_window_set_title ((GtkWindow*) _tmp56_, _ ("Name/Password Error!"));
			_tmp57_ = stdout;
			fprintf (_tmp57_, "login fail\n");
			_user_data_free0 (u);
			return;
		}
		_tmp58_ = client;
		chat_client_get_friends_async (_tmp58_);
		_tmp59_ = self->dlg1;
		gtk_widget_destroy ((GtkWidget*) _tmp59_);
		_tmp60_ = app;
		gtk_widget_show_all ((GtkWidget*) _tmp60_);
		_user_data_free0 (u);
	} else {
		gtk_main_quit ();
	}
}


static void
___lambda80__gtk_dialog_response (GtkDialog* _sender,
                                  gint response_id,
                                  gpointer self)
{
	__lambda80_ (self, response_id);
}


AddUserDialog*
add_user_dialog_construct (GType object_type)
{
	AddUserDialog * self = NULL;
	Block14Data* _data14_;
	AppWin* _tmp0_;
	GtkDialog* _tmp1_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp2_;
	GtkGrid* _tmp3_;
	GtkLabel* _tmp4_;
	GtkLabel* _tmp5_;
	GtkGrid* _tmp6_;
	GtkLabel* _tmp7_;
	GtkLabel* _tmp8_;
	GtkEntry* _tmp9_;
	GtkGrid* _tmp10_;
	GtkEntry* _tmp11_;
	GtkGrid* _tmp12_;
	GtkLabel* _tmp13_;
	GtkLabel* _tmp14_;
	GtkEntry* _tmp15_;
	GtkEntry* _tmp16_;
	GtkGrid* _tmp17_;
	GtkEntry* _tmp18_;
	GtkGrid* _tmp19_;
	GtkLabel* _tmp20_;
	GtkLabel* _tmp21_;
	GtkEntry* _tmp22_;
	GtkEntry* _tmp23_;
	GtkGrid* _tmp24_;
	GtkEntry* _tmp25_;
	GDateTime* date1 = NULL;
	GDateTime* _tmp26_;
	gint year1 = 0;
	GDateTime* _tmp27_;
	GtkComboBoxText* _tmp28_;
	GtkComboBoxText* _tmp37_;
	gint _tmp38_;
	GtkGrid* _tmp39_;
	GtkLabel* _tmp40_;
	GtkLabel* _tmp41_;
	GtkGrid* _tmp42_;
	GtkComboBoxText* _tmp43_;
	GtkComboBoxText* _tmp44_;
	GtkComboBoxText* _tmp45_;
	GtkGrid* _tmp46_;
	GtkLabel* _tmp47_;
	GtkLabel* _tmp48_;
	GtkGrid* _tmp49_;
	GtkGrid* _tmp50_;
	GtkLabel* _tmp51_;
	GtkLabel* _tmp52_;
	GtkEntry* _tmp53_;
	GtkGrid* _tmp54_;
	GtkEntry* _tmp55_;
	GtkBox* content = NULL;
	GtkDialog* _tmp56_;
	GtkBox* _tmp57_;
	GtkBox* _tmp58_;
	GtkGrid* _tmp59_;
	GtkDialog* _tmp60_;
	GtkDialog* _tmp61_;
	GtkDialog* _tmp62_;
	_data14_ = g_slice_new0 (Block14Data);
	_data14_->_ref_count_ = 1;
	self = (AddUserDialog*) g_object_new (object_type, NULL);
	_data14_->self = g_object_ref (self);
	_tmp0_ = app;
	_tmp1_ = (GtkDialog*) gtk_dialog_new_with_buttons (_ ("Register"), (GtkWindow*) _tmp0_, GTK_DIALOG_MODAL, NULL);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->dlg1);
	self->dlg1 = _tmp1_;
	_tmp2_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp2_);
	grid = _tmp2_;
	_tmp3_ = grid;
	_tmp4_ = (GtkLabel*) gtk_label_new (_ ("Input your information"));
	g_object_ref_sink (_tmp4_);
	_tmp5_ = _tmp4_;
	gtk_grid_attach (_tmp3_, (GtkWidget*) _tmp5_, 0, 0, 2, 1);
	_g_object_unref0 (_tmp5_);
	_tmp6_ = grid;
	_tmp7_ = (GtkLabel*) gtk_label_new (_ ("Name:"));
	g_object_ref_sink (_tmp7_);
	_tmp8_ = _tmp7_;
	gtk_grid_attach (_tmp6_, (GtkWidget*) _tmp8_, 0, 1, 1, 1);
	_g_object_unref0 (_tmp8_);
	_tmp9_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->name);
	self->name = _tmp9_;
	_tmp10_ = grid;
	_tmp11_ = self->name;
	gtk_grid_attach (_tmp10_, (GtkWidget*) _tmp11_, 1, 1, 1, 1);
	_tmp12_ = grid;
	_tmp13_ = (GtkLabel*) gtk_label_new (_ ("Password:"));
	g_object_ref_sink (_tmp13_);
	_tmp14_ = _tmp13_;
	gtk_grid_attach (_tmp12_, (GtkWidget*) _tmp14_, 0, 2, 1, 1);
	_g_object_unref0 (_tmp14_);
	_tmp15_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp15_);
	_g_object_unref0 (self->pwd);
	self->pwd = _tmp15_;
	_tmp16_ = self->pwd;
	gtk_entry_set_visibility (_tmp16_, FALSE);
	_tmp17_ = grid;
	_tmp18_ = self->pwd;
	gtk_grid_attach (_tmp17_, (GtkWidget*) _tmp18_, 1, 2, 1, 1);
	_tmp19_ = grid;
	_tmp20_ = (GtkLabel*) gtk_label_new (_ ("Confirm Password:"));
	g_object_ref_sink (_tmp20_);
	_tmp21_ = _tmp20_;
	gtk_grid_attach (_tmp19_, (GtkWidget*) _tmp21_, 0, 3, 1, 1);
	_g_object_unref0 (_tmp21_);
	_tmp22_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp22_);
	_data14_->cfpwd = _tmp22_;
	_tmp23_ = _data14_->cfpwd;
	gtk_entry_set_visibility (_tmp23_, FALSE);
	_tmp24_ = grid;
	_tmp25_ = _data14_->cfpwd;
	gtk_grid_attach (_tmp24_, (GtkWidget*) _tmp25_, 1, 3, 1, 1);
	_tmp26_ = g_date_time_new_now_local ();
	date1 = _tmp26_;
	_tmp27_ = date1;
	year1 = g_date_time_get_year (_tmp27_);
	_tmp28_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp28_);
	_data14_->yearSelect = _tmp28_;
	{
		gint i = 0;
		i = 5;
		{
			gboolean _tmp29_ = FALSE;
			_tmp29_ = TRUE;
			while (TRUE) {
				gint _tmp31_;
				GtkComboBoxText* _tmp32_;
				gint _tmp33_;
				gint _tmp34_;
				gchar* _tmp35_;
				gchar* _tmp36_;
				if (!_tmp29_) {
					gint _tmp30_;
					_tmp30_ = i;
					i = _tmp30_ + 1;
				}
				_tmp29_ = FALSE;
				_tmp31_ = i;
				if (!(_tmp31_ < 100)) {
					break;
				}
				_tmp32_ = _data14_->yearSelect;
				_tmp33_ = year1;
				_tmp34_ = i;
				_tmp35_ = g_strdup_printf ("%i", _tmp33_ - _tmp34_);
				_tmp36_ = _tmp35_;
				gtk_combo_box_text_append_text (_tmp32_, _tmp36_);
				_g_free0 (_tmp36_);
			}
		}
	}
	_tmp37_ = _data14_->yearSelect;
	gtk_combo_box_set_active ((GtkComboBox*) _tmp37_, 10);
	_tmp38_ = year1;
	self->birthyear = _tmp38_ - 15;
	_tmp39_ = grid;
	_tmp40_ = (GtkLabel*) gtk_label_new (_ ("Born Year:"));
	g_object_ref_sink (_tmp40_);
	_tmp41_ = _tmp40_;
	gtk_grid_attach (_tmp39_, (GtkWidget*) _tmp41_, 0, 4, 1, 1);
	_g_object_unref0 (_tmp41_);
	_tmp42_ = grid;
	_tmp43_ = _data14_->yearSelect;
	gtk_grid_attach (_tmp42_, (GtkWidget*) _tmp43_, 1, 4, 1, 1);
	_tmp44_ = _data14_->yearSelect;
	g_signal_connect_data ((GtkComboBox*) _tmp44_, "changed", (GCallback) ___lambda78__gtk_combo_box_changed, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	_tmp45_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp45_);
	_data14_->sexSelect = _tmp45_;
	gtk_combo_box_text_append_text (_data14_->sexSelect, _ ("Man"));
	gtk_combo_box_text_append_text (_data14_->sexSelect, _ ("Woman"));
	gtk_combo_box_set_active ((GtkComboBox*) _data14_->sexSelect, 0);
	_tmp46_ = grid;
	_tmp47_ = (GtkLabel*) gtk_label_new (_ ("Sex:"));
	g_object_ref_sink (_tmp47_);
	_tmp48_ = _tmp47_;
	gtk_grid_attach (_tmp46_, (GtkWidget*) _tmp48_, 0, 5, 1, 1);
	_g_object_unref0 (_tmp48_);
	_tmp49_ = grid;
	gtk_grid_attach (_tmp49_, (GtkWidget*) _data14_->sexSelect, 1, 5, 1, 1);
	g_signal_connect_data ((GtkComboBox*) _data14_->sexSelect, "changed", (GCallback) ___lambda79__gtk_combo_box_changed, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	_tmp50_ = grid;
	_tmp51_ = (GtkLabel*) gtk_label_new (_ ("Description:"));
	g_object_ref_sink (_tmp51_);
	_tmp52_ = _tmp51_;
	gtk_grid_attach (_tmp50_, (GtkWidget*) _tmp52_, 0, 6, 1, 1);
	_g_object_unref0 (_tmp52_);
	_tmp53_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp53_);
	_g_object_unref0 (self->desc);
	self->desc = _tmp53_;
	_tmp54_ = grid;
	_tmp55_ = self->desc;
	gtk_grid_attach (_tmp54_, (GtkWidget*) _tmp55_, 1, 6, 1, 1);
	_tmp56_ = self->dlg1;
	_tmp57_ = gtk_dialog_get_content_area (_tmp56_);
	_tmp58_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp57_, gtk_box_get_type ()) ? ((GtkBox*) _tmp57_) : NULL);
	content = _tmp58_;
	_tmp59_ = grid;
	gtk_box_pack_start (content, (GtkWidget*) _tmp59_, TRUE, TRUE, (guint) 0);
	_tmp60_ = self->dlg1;
	gtk_dialog_add_button (_tmp60_, _ ("Register"), 2);
	_tmp61_ = self->dlg1;
	gtk_dialog_add_button (_tmp61_, _ ("Cancel"), 3);
	_tmp62_ = self->dlg1;
	g_signal_connect_data (_tmp62_, "response", (GCallback) ___lambda80__gtk_dialog_response, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	_g_object_unref0 (content);
	_g_date_time_unref0 (date1);
	_g_object_unref0 (grid);
	block14_data_unref (_data14_);
	_data14_ = NULL;
	return self;
}


AddUserDialog*
add_user_dialog_new (void)
{
	return add_user_dialog_construct (TYPE_ADD_USER_DIALOG);
}


void
add_user_dialog_show (AddUserDialog* self)
{
	GtkDialog* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->dlg1;
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
}


static void
add_user_dialog_class_init (AddUserDialogClass * klass)
{
	add_user_dialog_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = add_user_dialog_finalize;
}


static void
add_user_dialog_instance_init (AddUserDialog * self)
{
	self->sex = 1;
}


static void
add_user_dialog_finalize (GObject * obj)
{
	AddUserDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ADD_USER_DIALOG, AddUserDialog);
	_g_object_unref0 (self->dlg1);
	_g_object_unref0 (self->name);
	_g_object_unref0 (self->pwd);
	_g_object_unref0 (self->desc);
	G_OBJECT_CLASS (add_user_dialog_parent_class)->finalize (obj);
}


GType
add_user_dialog_get_type (void)
{
	static volatile gsize add_user_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&add_user_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AddUserDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) add_user_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AddUserDialog), 0, (GInstanceInitFunc) add_user_dialog_instance_init, NULL };
		GType add_user_dialog_type_id;
		add_user_dialog_type_id = g_type_register_static (G_TYPE_OBJECT, "AddUserDialog", &g_define_type_info, 0);
		g_once_init_leave (&add_user_dialog_type_id__volatile, add_user_dialog_type_id);
	}
	return add_user_dialog_type_id__volatile;
}



