/* multisend.vala.c generated by valac 0.42.6, the Vala compiler
 * generated from multisend.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <json-glib/json-glib.h>
#include <gio/gio.h>
#include <gdk/gdk.h>


#define TYPE_ID_ARRAY (id_array_get_type ())
typedef struct _IDArray IDArray;

#define TYPE_MULTI_SEND_UI (multi_send_ui_get_type ())
#define MULTI_SEND_UI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MULTI_SEND_UI, MultiSendUi))
#define MULTI_SEND_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MULTI_SEND_UI, MultiSendUiClass))
#define IS_MULTI_SEND_UI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MULTI_SEND_UI))
#define IS_MULTI_SEND_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MULTI_SEND_UI))
#define MULTI_SEND_UI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MULTI_SEND_UI, MultiSendUiClass))

typedef struct _MultiSendUi MultiSendUi;
typedef struct _MultiSendUiClass MultiSendUiClass;
typedef struct _MultiSendUiPrivate MultiSendUiPrivate;

#define TYPE_GROUP_POPUP (group_popup_get_type ())
#define GROUP_POPUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GROUP_POPUP, GroupPopup))
#define GROUP_POPUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GROUP_POPUP, GroupPopupClass))
#define IS_GROUP_POPUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GROUP_POPUP))
#define IS_GROUP_POPUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GROUP_POPUP))
#define GROUP_POPUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GROUP_POPUP, GroupPopupClass))

typedef struct _GroupPopup GroupPopup;
typedef struct _GroupPopupClass GroupPopupClass;
enum  {
	MULTI_SEND_UI_0_PROPERTY,
	MULTI_SEND_UI_NUM_PROPERTIES
};
static GParamSpec* multi_send_ui_properties[MULTI_SEND_UI_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_MY_GRID (my_grid_get_type ())
#define MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_GRID, MyGrid))
#define MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_GRID, MyGridClass))
#define IS_MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_GRID))
#define IS_MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_GRID))
#define MY_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_GRID, MyGridClass))

typedef struct _MyGrid MyGrid;
typedef struct _MyGridClass MyGridClass;
typedef struct _MyGridPrivate MyGridPrivate;

#define TYPE_USER_MSG (user_msg_get_type ())
typedef struct _UserMsg UserMsg;
#define _user_msg_free0(var) ((var == NULL) ? NULL : (var = (user_msg_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _id_array_free0(var) ((var == NULL) ? NULL : (var = (id_array_free (var), NULL)))
typedef struct _Block15Data Block15Data;
typedef struct _Block16Data Block16Data;

#define TYPE_CHAT_CLIENT (chat_client_get_type ())
#define CHAT_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CHAT_CLIENT, ChatClient))
#define CHAT_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CHAT_CLIENT, ChatClientClass))
#define IS_CHAT_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CHAT_CLIENT))
#define IS_CHAT_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CHAT_CLIENT))
#define CHAT_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CHAT_CLIENT, ChatClientClass))

typedef struct _ChatClient ChatClient;
typedef struct _ChatClientClass ChatClientClass;
typedef struct _Block17Data Block17Data;
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _Block18Data Block18Data;
typedef struct _GroupPopupPrivate GroupPopupPrivate;
enum  {
	GROUP_POPUP_0_PROPERTY,
	GROUP_POPUP_NUM_PROPERTIES
};
static GParamSpec* group_popup_properties[GROUP_POPUP_NUM_PROPERTIES];

struct _IDArray {
	gint64* ids;
	gint ids_length1;
	gint _ids_size_;
};

struct _MultiSendUi {
	GObject parent_instance;
	MultiSendUiPrivate * priv;
};

struct _MultiSendUiClass {
	GObjectClass parent_class;
};

struct _MultiSendUiPrivate {
	GtkDialog* frame1;
	GtkGrid* grid_main;
	GtkListBox* friends;
	GtkListBox* groups;
	GtkEntry* entry1;
	GtkButton* send1;
	GtkButton* save1;
	GeeHashSet* ids;
	GeeHashMap* group_map;
	GRecMutex __lock_group_map;
	GroupPopup* popup1;
};

struct _UserMsg {
	gint64 id;
	gint sex;
	gchar* name;
	gchar* desc;
	gint age;
	gchar* msg_offline;
	gchar* timestamp_offline;
};

struct _MyGrid {
	GObject parent_instance;
	MyGridPrivate * priv;
	GtkEntry* port1;
	GtkGrid* mygrid;
	GeeHashMap* frds1;
	GtkCssProvider* provider1;
	GtkCssProvider* mark1;
	GtkCssProvider* name_css;
	gint mark_num;
	GtkCssProvider* button1;
	GtkCssProvider* link_css1;
	GtkButton* strangers_btn;
	GtkButton* user_btn;
	GtkButton* msend_btn;
	gchar* man_icon;
	gchar* woman_icon;
	gint64 uid;
	gint16 usex;
	gchar* uname;
	gchar* udesc;
	gint16 uage;
	gchar* host;
};

struct _MyGridClass {
	GObjectClass parent_class;
};

struct _Block15Data {
	int _ref_count_;
	MultiSendUi* self;
	GeeHashSet* set1;
};

struct _Block16Data {
	int _ref_count_;
	MultiSendUi* self;
	GtkEntry* name1;
};

struct _Block17Data {
	int _ref_count_;
	MultiSendUi* self;
	GtkCheckButton* button1;
	UserMsg u1;
};

struct _Block18Data {
	int _ref_count_;
	MultiSendUi* self;
	gchar* name;
};

struct _GroupPopup {
	GtkMenu parent_instance;
	GroupPopupPrivate * priv;
};

struct _GroupPopupClass {
	GtkMenuClass parent_class;
};

struct _GroupPopupPrivate {
	gchar* g_name;
};


static gint MultiSendUi_private_offset;
static gpointer multi_send_ui_parent_class = NULL;
extern MyGrid* grid1;
extern ChatClient* client;
static gint GroupPopup_private_offset;
static gpointer group_popup_parent_class = NULL;
extern MultiSendUi* msend_ui;

GType id_array_get_type (void) G_GNUC_CONST;
IDArray* id_array_dup (const IDArray* self);
void id_array_free (IDArray* self);
void id_array_copy (const IDArray* self,
                    IDArray* dest);
void id_array_destroy (IDArray* self);
static gint64* _vala_array_dup1 (gint64* self,
                          int length);
GType multi_send_ui_get_type (void) G_GNUC_CONST;
GType group_popup_get_type (void) G_GNUC_CONST;
MultiSendUi* multi_send_ui_new (void);
MultiSendUi* multi_send_ui_construct (GType object_type);
static gboolean __lambda42_ (MultiSendUi* self,
                      gint64* a,
                      gint64* b);
static gboolean _int64_equal (const gint64 * s1,
                       const gint64 * s2);
static gboolean ___lambda42__gee_equal_data_func (gconstpointer a,
                                           gconstpointer b,
                                           gpointer self);
static gint64* _int64_dup (gint64* self);
GroupPopup* group_popup_new (void);
GroupPopup* group_popup_construct (GType object_type);
static void multi_send_ui_set_css (MultiSendUi* self);
static void multi_send_ui_set_lists (MultiSendUi* self);
static void multi_send_ui_set_send_callback (MultiSendUi* self);
static void multi_send_ui_set_save_callback (MultiSendUi* self);
static void multi_send_ui_set_group_callback (MultiSendUi* self);
static void multi_send_ui_set_popup (MultiSendUi* self);
static void __lambda52_ (MultiSendUi* self);
static void multi_send_ui_on_select_destroy (MultiSendUi* self);
static void ___lambda52__gtk_widget_destroy (GtkWidget* _sender,
                                      gpointer self);
static void __lambda47_ (MultiSendUi* self,
                  GtkListBoxRow* r);
GType my_grid_get_type (void) G_GNUC_CONST;
GType user_msg_get_type (void) G_GNUC_CONST;
UserMsg* user_msg_dup (const UserMsg* self);
void user_msg_free (UserMsg* self);
void user_msg_copy (const UserMsg* self,
                    UserMsg* dest);
void user_msg_destroy (UserMsg* self);
static void multi_send_ui_ask_group (MultiSendUi* self,
                              const gchar* msg1,
                              gint64* ids1,
                              int ids1_length1);
static void ___lambda47__gtk_list_box_row_selected (GtkListBox* _sender,
                                             GtkListBoxRow* row,
                                             gpointer self);
static Block15Data* block15_data_ref (Block15Data* _data15_);
static void block15_data_unref (void * _userdata_);
static gboolean __lambda48_ (MultiSendUi* self,
                      const gchar* a,
                      const gchar* b);
static gboolean ___lambda48__gee_equal_data_func (gconstpointer a,
                                           gconstpointer b,
                                           gpointer self);
static void ___lambda49_ (Block15Data* _data15_,
                   GtkWidget* w);
static void ____lambda49__gtk_callback (GtkWidget* widget,
                                 gpointer self);
static void ____lambda50_ (Block15Data* _data15_,
                    GtkWidget* w);
static void _____lambda50__gtk_callback (GtkWidget* widget,
                                  gpointer self);
static void __lambda45_ (MultiSendUi* self);
static Block16Data* block16_data_ref (Block16Data* _data16_);
static void block16_data_unref (void * _userdata_);
static void __lambda46_ (Block16Data* _data16_);
static void ___lambda46__gtk_entry_activate (GtkEntry* _sender,
                                      gpointer self);
static void ___lambda45__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda44_ (MultiSendUi* self);
void my_grid_show_sended_msg_to (MyGrid* self,
                                 gint64 to,
                                 const gchar* msg);
GType chat_client_get_type (void) G_GNUC_CONST;
void chat_client_multi_send (ChatClient* self,
                             gint64* to,
                             int to_length1,
                             const gchar* msg);
static void ___lambda44__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
void multi_send_ui_show (MultiSendUi* self);
static void multi_send_ui_load_groups (MultiSendUi* self);
static void multi_send_ui_add_friend (MultiSendUi* self,
                               UserMsg* u1);
static Block17Data* block17_data_ref (Block17Data* _data17_);
static void block17_data_unref (void * _userdata_);
static void __lambda43_ (Block17Data* _data17_);
static void ___lambda43__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                             gpointer self);
static void multi_send_ui_save_groups (MultiSendUi* self,
                                const gchar* data);
static gint64* _vala_array_dup2 (gint64* self,
                          int length);
gchar* get_cfg_dir (const gchar* name);
void multi_send_ui_remove_group_by_name (MultiSendUi* self,
                                         const gchar* name);
static Block18Data* block18_data_ref (Block18Data* _data18_);
static void block18_data_unref (void * _userdata_);
static void __lambda41_ (Block18Data* _data18_,
                  GtkWidget* w);
static void ___lambda41__gtk_callback (GtkWidget* widget,
                                gpointer self);
static gboolean __lambda51_ (MultiSendUi* self,
                      GdkEventButton* e);
void group_popup_set_name (GroupPopup* self,
                           const gchar* name);
static gboolean ___lambda51__gtk_widget_button_release_event (GtkWidget* _sender,
                                                       GdkEventButton* event,
                                                       gpointer self);
static void multi_send_ui_finalize (GObject * obj);
static void __lambda40_ (GroupPopup* self);
static void ___lambda40__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void group_popup_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);


static gint64*
_vala_array_dup1 (gint64* self,
                  int length)
{
	return g_memdup (self, length * sizeof (gint64));
}


void
id_array_copy (const IDArray* self,
               IDArray* dest)
{
	gint64* _tmp0_;
	gint _tmp0__length1;
	gint64* _tmp1_;
	gint _tmp1__length1;
	_tmp0_ = (*self).ids;
	_tmp0__length1 = (*self).ids_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup1 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	(*dest).ids = (g_free ((*dest).ids), NULL);
	(*dest).ids = _tmp1_;
	(*dest).ids_length1 = _tmp1__length1;
	(*dest)._ids_size_ = (*dest).ids_length1;
}


void
id_array_destroy (IDArray* self)
{
	(*self).ids = (g_free ((*self).ids), NULL);
}


IDArray*
id_array_dup (const IDArray* self)
{
	IDArray* dup;
	dup = g_new0 (IDArray, 1);
	id_array_copy (self, dup);
	return dup;
}


void
id_array_free (IDArray* self)
{
	id_array_destroy (self);
	g_free (self);
}


GType
id_array_get_type (void)
{
	static volatile gsize id_array_type_id__volatile = 0;
	if (g_once_init_enter (&id_array_type_id__volatile)) {
		GType id_array_type_id;
		id_array_type_id = g_boxed_type_register_static ("IDArray", (GBoxedCopyFunc) id_array_dup, (GBoxedFreeFunc) id_array_free);
		g_once_init_leave (&id_array_type_id__volatile, id_array_type_id);
	}
	return id_array_type_id__volatile;
}


static inline gpointer
multi_send_ui_get_instance_private (MultiSendUi* self)
{
	return G_STRUCT_MEMBER_P (self, MultiSendUi_private_offset);
}


static gboolean
_int64_equal (const gint64 * s1,
              const gint64 * s2)
{
	if (s1 == s2) {
		return TRUE;
	}
	if (s1 == NULL) {
		return FALSE;
	}
	if (s2 == NULL) {
		return FALSE;
	}
	return (*s1) == (*s2);
}


static gboolean
__lambda42_ (MultiSendUi* self,
             gint64* a,
             gint64* b)
{
	gboolean result = FALSE;
	result = _int64_equal (a, b) == TRUE;
	return result;
}


static gboolean
___lambda42__gee_equal_data_func (gconstpointer a,
                                  gconstpointer b,
                                  gpointer self)
{
	gboolean result;
	result = __lambda42_ ((MultiSendUi*) self, (gint64*) a, (gint64*) b);
	return result;
}


static gint64*
_int64_dup (gint64* self)
{
	gint64* dup;
	dup = g_new0 (gint64, 1);
	memcpy (dup, self, sizeof (gint64));
	return dup;
}


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


static void
__lambda52_ (MultiSendUi* self)
{
	GError* _inner_error0_ = NULL;
	{
		GeeHashMap* _tmp0_;
		_tmp0_ = self->priv->group_map;
		g_rec_mutex_lock (&self->priv->__lock_group_map);
		{
			multi_send_ui_on_select_destroy (self);
		}
		__finally4:
		{
			GeeHashMap* _tmp1_;
			_tmp1_ = self->priv->group_map;
			g_rec_mutex_unlock (&self->priv->__lock_group_map);
		}
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
	}
}


static void
___lambda52__gtk_widget_destroy (GtkWidget* _sender,
                                 gpointer self)
{
	__lambda52_ ((MultiSendUi*) self);
}


MultiSendUi*
multi_send_ui_construct (GType object_type)
{
	MultiSendUi * self = NULL;
	GtkDialog* _tmp0_;
	GtkDialog* _tmp1_;
	GtkDialog* _tmp2_;
	GtkListBox* _tmp3_;
	GtkListBox* _tmp4_;
	GtkEntry* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
	GtkButton* _tmp8_;
	GtkButton* _tmp9_;
	GeeHashSet* _tmp10_;
	GeeHashMap* _tmp11_;
	GroupPopup* _tmp12_;
	GtkGrid* grid1 = NULL;
	GtkGrid* _tmp13_;
	GtkBox* box1 = NULL;
	GtkDialog* _tmp14_;
	GtkBox* _tmp15_;
	GtkBox* _tmp16_;
	GtkLabel* label1 = NULL;
	GtkLabel* _tmp17_;
	GtkLabel* label2 = NULL;
	GtkLabel* _tmp18_;
	GtkScrolledWindow* scrollWin1 = NULL;
	GtkScrolledWindow* _tmp19_;
	GtkScrolledWindow* _tmp20_;
	GtkScrolledWindow* _tmp21_;
	GtkScrolledWindow* _tmp22_;
	GtkListBox* _tmp23_;
	GtkScrolledWindow* _tmp24_;
	GtkLabel* lb1 = NULL;
	GtkLabel* _tmp25_;
	GtkButton* _tmp26_;
	GtkLabel* lb2 = NULL;
	GtkLabel* _tmp27_;
	GtkScrolledWindow* _tmp28_;
	GtkScrolledWindow* _tmp29_;
	GtkScrolledWindow* _tmp30_;
	GtkScrolledWindow* _tmp31_;
	GtkListBox* _tmp32_;
	GtkScrolledWindow* _tmp33_;
	GtkGrid* bottom_grid = NULL;
	GtkGrid* _tmp34_;
	GtkLabel* _tmp35_;
	GtkLabel* _tmp36_;
	GtkEntry* _tmp37_;
	GtkEntry* _tmp38_;
	GtkButton* _tmp39_;
	GtkGrid* _tmp40_;
	GtkDialog* _tmp41_;
	self = (MultiSendUi*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkDialog*) gtk_dialog_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->frame1);
	self->priv->frame1 = _tmp0_;
	_tmp1_ = self->priv->frame1;
	gtk_window_set_modal ((GtkWindow*) _tmp1_, TRUE);
	_tmp2_ = self->priv->frame1;
	gtk_window_set_title ((GtkWindow*) _tmp2_, _ ("MultiSend"));
	_tmp3_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->friends);
	self->priv->friends = _tmp3_;
	_tmp4_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->priv->groups);
	self->priv->groups = _tmp4_;
	_tmp5_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->entry1);
	self->priv->entry1 = _tmp5_;
	_tmp6_ = (GtkButton*) gtk_button_new_with_label (_ ("Send"));
	g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->send1);
	self->priv->send1 = _tmp6_;
	_tmp7_ = (GtkButton*) gtk_button_new_with_label ("=>");
	g_object_ref_sink (_tmp7_);
	_g_object_unref0 (self->priv->save1);
	self->priv->save1 = _tmp7_;
	_tmp8_ = self->priv->save1;
	gtk_widget_set_size_request ((GtkWidget*) _tmp8_, 24, 12);
	_tmp9_ = self->priv->save1;
	g_object_set ((GtkWidget*) _tmp9_, "expand", FALSE, NULL);
	_tmp10_ = gee_hash_set_new (G_TYPE_INT64, (GBoxedCopyFunc) _int64_dup, (GDestroyNotify) g_free, NULL, NULL, NULL, ___lambda42__gee_equal_data_func, g_object_ref (self), g_object_unref);
	_g_object_unref0 (self->priv->ids);
	self->priv->ids = _tmp10_;
	_tmp11_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, TYPE_ID_ARRAY, (GBoxedCopyFunc) id_array_dup, (GDestroyNotify) id_array_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->group_map);
	self->priv->group_map = _tmp11_;
	_tmp12_ = group_popup_new ();
	g_object_ref_sink (_tmp12_);
	_g_object_unref0 (self->priv->popup1);
	self->priv->popup1 = _tmp12_;
	_tmp13_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp13_);
	grid1 = _tmp13_;
	_tmp14_ = self->priv->frame1;
	_tmp15_ = gtk_dialog_get_content_area (_tmp14_);
	_tmp16_ = _g_object_ref0 (_tmp15_);
	box1 = _tmp16_;
	gtk_box_pack_start (box1, (GtkWidget*) grid1, TRUE, TRUE, (guint) 0);
	_tmp17_ = (GtkLabel*) gtk_label_new (_ ("My Friends"));
	g_object_ref_sink (_tmp17_);
	label1 = _tmp17_;
	_tmp18_ = (GtkLabel*) gtk_label_new (_ ("Groups"));
	g_object_ref_sink (_tmp18_);
	label2 = _tmp18_;
	gtk_grid_attach (grid1, (GtkWidget*) label1, 1, 0, 1, 1);
	gtk_grid_attach (grid1, (GtkWidget*) label2, 3, 0, 1, 1);
	_tmp19_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp19_);
	scrollWin1 = _tmp19_;
	_tmp20_ = scrollWin1;
	gtk_widget_set_size_request ((GtkWidget*) _tmp20_, 200, 300);
	_tmp21_ = scrollWin1;
	g_object_set ((GtkWidget*) _tmp21_, "expand", TRUE, NULL);
	_tmp22_ = scrollWin1;
	_tmp23_ = self->priv->friends;
	gtk_container_add ((GtkContainer*) _tmp22_, (GtkWidget*) _tmp23_);
	_tmp24_ = scrollWin1;
	gtk_grid_attach (grid1, (GtkWidget*) _tmp24_, 1, 1, 1, 3);
	_tmp25_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp25_);
	lb1 = _tmp25_;
	g_object_set ((GtkWidget*) lb1, "expand", TRUE, NULL);
	gtk_grid_attach (grid1, (GtkWidget*) lb1, 2, 1, 1, 1);
	_tmp26_ = self->priv->save1;
	gtk_grid_attach (grid1, (GtkWidget*) _tmp26_, 2, 2, 1, 1);
	_tmp27_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp27_);
	lb2 = _tmp27_;
	g_object_set ((GtkWidget*) lb2, "expand", TRUE, NULL);
	gtk_grid_attach (grid1, (GtkWidget*) lb2, 2, 3, 1, 1);
	_tmp28_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp28_);
	_g_object_unref0 (scrollWin1);
	scrollWin1 = _tmp28_;
	_tmp29_ = scrollWin1;
	gtk_widget_set_size_request ((GtkWidget*) _tmp29_, 200, 400);
	_tmp30_ = scrollWin1;
	g_object_set ((GtkWidget*) _tmp30_, "expand", TRUE, NULL);
	_tmp31_ = scrollWin1;
	_tmp32_ = self->priv->groups;
	gtk_container_add ((GtkContainer*) _tmp31_, (GtkWidget*) _tmp32_);
	_tmp33_ = scrollWin1;
	gtk_grid_attach (grid1, (GtkWidget*) _tmp33_, 3, 1, 1, 3);
	_tmp34_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp34_);
	bottom_grid = _tmp34_;
	gtk_grid_attach (grid1, (GtkWidget*) bottom_grid, 0, 4, 5, 1);
	gtk_widget_set_hexpand ((GtkWidget*) bottom_grid, TRUE);
	_tmp35_ = (GtkLabel*) gtk_label_new (_ ("Text:"));
	g_object_ref_sink (_tmp35_);
	_tmp36_ = _tmp35_;
	gtk_grid_attach (bottom_grid, (GtkWidget*) _tmp36_, 0, 0, 1, 1);
	_g_object_unref0 (_tmp36_);
	_tmp37_ = self->priv->entry1;
	gtk_grid_attach (bottom_grid, (GtkWidget*) _tmp37_, 1, 0, 1, 1);
	_tmp38_ = self->priv->entry1;
	gtk_widget_set_hexpand ((GtkWidget*) _tmp38_, TRUE);
	_tmp39_ = self->priv->send1;
	gtk_grid_attach (bottom_grid, (GtkWidget*) _tmp39_, 2, 0, 1, 1);
	gtk_widget_show_all ((GtkWidget*) bottom_grid);
	gtk_widget_show_all ((GtkWidget*) grid1);
	_tmp40_ = _g_object_ref0 (grid1);
	_g_object_unref0 (self->priv->grid_main);
	self->priv->grid_main = _tmp40_;
	multi_send_ui_set_css (self);
	multi_send_ui_set_lists (self);
	multi_send_ui_set_send_callback (self);
	multi_send_ui_set_save_callback (self);
	multi_send_ui_set_group_callback (self);
	multi_send_ui_set_popup (self);
	_tmp41_ = self->priv->frame1;
	g_signal_connect_object ((GtkWidget*) _tmp41_, "destroy", (GCallback) ___lambda52__gtk_widget_destroy, self, 0);
	_g_object_unref0 (bottom_grid);
	_g_object_unref0 (lb2);
	_g_object_unref0 (lb1);
	_g_object_unref0 (scrollWin1);
	_g_object_unref0 (label2);
	_g_object_unref0 (label1);
	_g_object_unref0 (box1);
	_g_object_unref0 (grid1);
	return self;
}


MultiSendUi*
multi_send_ui_new (void)
{
	return multi_send_ui_construct (TYPE_MULTI_SEND_UI);
}


static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static void
__lambda47_ (MultiSendUi* self,
             GtkListBoxRow* r)
{
	GeeHashMap* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	IDArray* array1 = NULL;
	GeeHashMap* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gpointer _tmp6_;
	gchar* msg = NULL;
	gchar* _tmp7_;
	const gchar* _tmp35_;
	IDArray* _tmp36_;
	gint64* _tmp37_;
	gint _tmp37__length1;
	_tmp0_ = self->priv->group_map;
	_tmp1_ = gtk_widget_get_name ((GtkWidget*) r);
	_tmp2_ = _tmp1_;
	if (gee_abstract_map_has_key ((GeeAbstractMap*) _tmp0_, _tmp2_) == FALSE) {
		return;
	}
	_tmp3_ = self->priv->group_map;
	_tmp4_ = gtk_widget_get_name ((GtkWidget*) r);
	_tmp5_ = _tmp4_;
	_tmp6_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp3_, _tmp5_);
	array1 = (IDArray*) _tmp6_;
	_tmp7_ = g_strdup ("");
	msg = _tmp7_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp8_ = FALSE;
			_tmp8_ = TRUE;
			while (TRUE) {
				gint _tmp10_;
				IDArray* _tmp11_;
				gint64* _tmp12_;
				gint _tmp12__length1;
				gchar* id1 = NULL;
				IDArray* _tmp13_;
				gint64* _tmp14_;
				gint _tmp14__length1;
				gint _tmp15_;
				gint64 _tmp16_;
				gchar* _tmp17_;
				gchar* name1 = NULL;
				MyGrid* _tmp18_;
				GeeHashMap* _tmp19_;
				const gchar* _tmp20_;
				gpointer _tmp21_;
				UserMsg* _tmp22_;
				const gchar* _tmp23_;
				gchar* _tmp24_;
				gchar* _tmp25_;
				const gchar* _tmp26_;
				gint _tmp27_;
				gchar* _tmp28_;
				gchar* _tmp29_;
				const gchar* _tmp30_;
				const gchar* _tmp31_;
				gchar* _tmp32_;
				gchar* _tmp33_;
				gchar* _tmp34_;
				if (!_tmp8_) {
					gint _tmp9_;
					_tmp9_ = i;
					i = _tmp9_ + 1;
				}
				_tmp8_ = FALSE;
				_tmp10_ = i;
				_tmp11_ = array1;
				_tmp12_ = (*_tmp11_).ids;
				_tmp12__length1 = (*_tmp11_).ids_length1;
				if (!(_tmp10_ < _tmp12__length1)) {
					break;
				}
				_tmp13_ = array1;
				_tmp14_ = (*_tmp13_).ids;
				_tmp14__length1 = (*_tmp13_).ids_length1;
				_tmp15_ = i;
				_tmp16_ = _tmp14_[_tmp15_];
				_tmp17_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp16_);
				id1 = _tmp17_;
				_tmp18_ = grid1;
				_tmp19_ = _tmp18_->frds1;
				_tmp20_ = id1;
				_tmp21_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp19_, _tmp20_);
				_tmp22_ = (UserMsg*) _tmp21_;
				_tmp23_ = (*_tmp22_).name;
				_tmp24_ = g_strdup (_tmp23_);
				_tmp25_ = _tmp24_;
				_user_msg_free0 (_tmp22_);
				name1 = _tmp25_;
				_tmp26_ = msg;
				_tmp27_ = i;
				_tmp28_ = g_strdup_printf ("%i", _tmp27_ + 1);
				_tmp29_ = _tmp28_;
				_tmp30_ = name1;
				_tmp31_ = string_to_string (_tmp30_);
				_tmp32_ = g_strconcat (_tmp29_, ". ", _tmp31_, "\n", NULL);
				_tmp33_ = _tmp32_;
				_tmp34_ = g_strconcat (_tmp26_, _tmp33_, NULL);
				_g_free0 (msg);
				msg = _tmp34_;
				_g_free0 (_tmp33_);
				_g_free0 (_tmp29_);
				_g_free0 (name1);
				_g_free0 (id1);
			}
		}
	}
	_tmp35_ = msg;
	_tmp36_ = array1;
	_tmp37_ = (*_tmp36_).ids;
	_tmp37__length1 = (*_tmp36_).ids_length1;
	multi_send_ui_ask_group (self, _tmp35_, _tmp37_, _tmp37__length1);
	_g_free0 (msg);
	_id_array_free0 (array1);
}


static void
___lambda47__gtk_list_box_row_selected (GtkListBox* _sender,
                                        GtkListBoxRow* row,
                                        gpointer self)
{
	__lambda47_ ((MultiSendUi*) self, row);
}


static void
multi_send_ui_set_group_callback (MultiSendUi* self)
{
	GtkListBox* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->groups;
	g_signal_connect_object (_tmp0_, "row-selected", (GCallback) ___lambda47__gtk_list_box_row_selected, self, 0);
}


static Block15Data*
block15_data_ref (Block15Data* _data15_)
{
	g_atomic_int_inc (&_data15_->_ref_count_);
	return _data15_;
}


static void
block15_data_unref (void * _userdata_)
{
	Block15Data* _data15_;
	_data15_ = (Block15Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data15_->_ref_count_)) {
		MultiSendUi* self;
		self = _data15_->self;
		_g_object_unref0 (_data15_->set1);
		_g_object_unref0 (self);
		g_slice_free (Block15Data, _data15_);
	}
}


static gboolean
__lambda48_ (MultiSendUi* self,
             const gchar* a,
             const gchar* b)
{
	gboolean result = FALSE;
	g_return_val_if_fail (a != NULL, FALSE);
	g_return_val_if_fail (b != NULL, FALSE);
	result = g_strcmp0 (a, b) == 0;
	return result;
}


static gboolean
___lambda48__gee_equal_data_func (gconstpointer a,
                                  gconstpointer b,
                                  gpointer self)
{
	gboolean result;
	result = __lambda48_ ((MultiSendUi*) self, (const gchar*) a, (const gchar*) b);
	return result;
}


static void
___lambda49_ (Block15Data* _data15_,
              GtkWidget* w)
{
	MultiSendUi* self;
	GtkListBoxRow* r = NULL;
	GtkListBoxRow* _tmp0_;
	GtkCheckButton* cb1 = NULL;
	GtkListBoxRow* _tmp1_;
	GtkWidget* _tmp2_;
	GtkCheckButton* _tmp3_;
	GeeHashSet* _tmp4_;
	GtkCheckButton* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	self = _data15_->self;
	g_return_if_fail (w != NULL);
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (w, gtk_list_box_row_get_type ()) ? ((GtkListBoxRow*) w) : NULL);
	r = _tmp0_;
	_tmp1_ = r;
	_tmp2_ = gtk_bin_get_child ((GtkBin*) _tmp1_);
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, gtk_check_button_get_type ()) ? ((GtkCheckButton*) _tmp2_) : NULL);
	cb1 = _tmp3_;
	_tmp4_ = _data15_->set1;
	_tmp5_ = cb1;
	_tmp6_ = gtk_widget_get_name ((GtkWidget*) _tmp5_);
	_tmp7_ = _tmp6_;
	if (gee_abstract_collection_contains ((GeeAbstractCollection*) _tmp4_, _tmp7_)) {
		GtkCheckButton* _tmp8_;
		_tmp8_ = cb1;
		gtk_toggle_button_set_active ((GtkToggleButton*) _tmp8_, TRUE);
	}
	_g_object_unref0 (cb1);
	_g_object_unref0 (r);
}


static void
____lambda49__gtk_callback (GtkWidget* widget,
                            gpointer self)
{
	___lambda49_ (self, widget);
}


static void
____lambda50_ (Block15Data* _data15_,
               GtkWidget* w)
{
	MultiSendUi* self;
	GtkListBoxRow* r = NULL;
	GtkListBoxRow* _tmp0_;
	GtkCheckButton* cb1 = NULL;
	GtkListBoxRow* _tmp1_;
	GtkWidget* _tmp2_;
	GtkCheckButton* _tmp3_;
	GeeHashSet* _tmp4_;
	GtkCheckButton* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	self = _data15_->self;
	g_return_if_fail (w != NULL);
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (w, gtk_list_box_row_get_type ()) ? ((GtkListBoxRow*) w) : NULL);
	r = _tmp0_;
	_tmp1_ = r;
	_tmp2_ = gtk_bin_get_child ((GtkBin*) _tmp1_);
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, gtk_check_button_get_type ()) ? ((GtkCheckButton*) _tmp2_) : NULL);
	cb1 = _tmp3_;
	_tmp4_ = _data15_->set1;
	_tmp5_ = cb1;
	_tmp6_ = gtk_widget_get_name ((GtkWidget*) _tmp5_);
	_tmp7_ = _tmp6_;
	if (gee_abstract_collection_contains ((GeeAbstractCollection*) _tmp4_, _tmp7_)) {
		GtkCheckButton* _tmp8_;
		_tmp8_ = cb1;
		gtk_toggle_button_set_active ((GtkToggleButton*) _tmp8_, FALSE);
	}
	_g_object_unref0 (cb1);
	_g_object_unref0 (r);
}


static void
_____lambda50__gtk_callback (GtkWidget* widget,
                             gpointer self)
{
	____lambda50_ (self, widget);
}


static void
multi_send_ui_ask_group (MultiSendUi* self,
                         const gchar* msg1,
                         gint64* ids1,
                         int ids1_length1)
{
	Block15Data* _data15_;
	GeeHashSet* _tmp0_;
	GtkDialog* dlg1 = NULL;
	GtkDialog* _tmp9_;
	GtkDialog* _tmp10_;
	GtkDialog* _tmp11_;
	GtkDialog* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	GtkScrolledWindow* scrollWin1 = NULL;
	GtkScrolledWindow* _tmp17_;
	GtkScrolledWindow* _tmp18_;
	GtkScrolledWindow* _tmp19_;
	GtkLabel* _tmp20_;
	GtkLabel* _tmp21_;
	GtkDialog* _tmp22_;
	GtkBox* _tmp23_;
	GtkScrolledWindow* _tmp24_;
	GtkScrolledWindow* _tmp25_;
	GtkDialog* _tmp26_;
	GtkDialog* _tmp27_;
	GtkDialog* _tmp28_;
	gint ret = 0;
	GtkDialog* _tmp29_;
	gint _tmp30_;
	GtkDialog* _tmp34_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (msg1 != NULL);
	_data15_ = g_slice_new0 (Block15Data);
	_data15_->_ref_count_ = 1;
	_data15_->self = g_object_ref (self);
	_tmp0_ = gee_hash_set_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, ___lambda48__gee_equal_data_func, g_object_ref (self), g_object_unref);
	_data15_->set1 = _tmp0_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_;
				GeeHashSet* _tmp4_;
				gint _tmp5_;
				gint64 _tmp6_;
				gchar* _tmp7_;
				gchar* _tmp8_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				if (!(_tmp3_ < ids1_length1)) {
					break;
				}
				_tmp4_ = _data15_->set1;
				_tmp5_ = i;
				_tmp6_ = ids1[_tmp5_];
				_tmp7_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp6_);
				_tmp8_ = _tmp7_;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp4_, _tmp8_);
				_g_free0 (_tmp8_);
			}
		}
	}
	_tmp9_ = (GtkDialog*) gtk_dialog_new ();
	g_object_ref_sink (_tmp9_);
	dlg1 = _tmp9_;
	_tmp10_ = dlg1;
	gtk_window_set_modal ((GtkWindow*) _tmp10_, TRUE);
	_tmp11_ = dlg1;
	gtk_window_set_keep_above ((GtkWindow*) _tmp11_, TRUE);
	_tmp12_ = dlg1;
	_tmp13_ = g_strconcat (_ ("MultiSend"), " - ", NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp14_, _ ("Group Members:"), NULL);
	_tmp16_ = _tmp15_;
	gtk_window_set_title ((GtkWindow*) _tmp12_, _tmp16_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	_tmp17_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp17_);
	scrollWin1 = _tmp17_;
	_tmp18_ = scrollWin1;
	gtk_widget_set_size_request ((GtkWidget*) _tmp18_, 240, 320);
	_tmp19_ = scrollWin1;
	_tmp20_ = (GtkLabel*) gtk_label_new (msg1);
	g_object_ref_sink (_tmp20_);
	_tmp21_ = _tmp20_;
	gtk_container_add ((GtkContainer*) _tmp19_, (GtkWidget*) _tmp21_);
	_g_object_unref0 (_tmp21_);
	_tmp22_ = dlg1;
	_tmp23_ = gtk_dialog_get_content_area (_tmp22_);
	_tmp24_ = scrollWin1;
	gtk_box_pack_start (_tmp23_, (GtkWidget*) _tmp24_, TRUE, TRUE, (guint) 0);
	_tmp25_ = scrollWin1;
	gtk_widget_show_all ((GtkWidget*) _tmp25_);
	_tmp26_ = dlg1;
	gtk_dialog_add_button (_tmp26_, _ ("Select"), 1);
	_tmp27_ = dlg1;
	gtk_dialog_add_button (_tmp27_, _ ("UnSelect"), 2);
	_tmp28_ = dlg1;
	gtk_dialog_add_button (_tmp28_, _ ("Cancel"), -1);
	_tmp29_ = dlg1;
	ret = gtk_dialog_run (_tmp29_);
	_tmp30_ = ret;
	if (_tmp30_ == 1) {
		GtkListBox* _tmp31_;
		_tmp31_ = self->priv->friends;
		gtk_container_foreach ((GtkContainer*) _tmp31_, ____lambda49__gtk_callback, _data15_);
	} else {
		gint _tmp32_;
		_tmp32_ = ret;
		if (_tmp32_ == 2) {
			GtkListBox* _tmp33_;
			_tmp33_ = self->priv->friends;
			gtk_container_foreach ((GtkContainer*) _tmp33_, _____lambda50__gtk_callback, _data15_);
		}
	}
	_tmp34_ = dlg1;
	gtk_widget_destroy ((GtkWidget*) _tmp34_);
	_g_object_unref0 (scrollWin1);
	_g_object_unref0 (dlg1);
	block15_data_unref (_data15_);
	_data15_ = NULL;
}


static Block16Data*
block16_data_ref (Block16Data* _data16_)
{
	g_atomic_int_inc (&_data16_->_ref_count_);
	return _data16_;
}


static void
block16_data_unref (void * _userdata_)
{
	Block16Data* _data16_;
	_data16_ = (Block16Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data16_->_ref_count_)) {
		MultiSendUi* self;
		self = _data16_->self;
		_g_object_unref0 (_data16_->name1);
		_g_object_unref0 (self);
		g_slice_free (Block16Data, _data16_);
	}
}


static void
__lambda46_ (Block16Data* _data16_)
{
	MultiSendUi* self;
	gchar* gname = NULL;
	GtkEntry* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	GeeHashMap* _tmp4_;
	const gchar* _tmp5_;
	GtkLabel* label1 = NULL;
	const gchar* _tmp6_;
	GtkLabel* _tmp7_;
	GtkListBox* _tmp8_;
	GtkEntry* _tmp9_;
	GtkEntry* _tmp10_;
	GtkListBox* _tmp11_;
	GtkLabel* _tmp12_;
	GtkLabel* _tmp13_;
	gint64* idsi = NULL;
	GeeHashSet* _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	gint64* _tmp17_;
	gint idsi_length1;
	gint _idsi_size_;
	gint i = 0;
	GeeHashMap* _tmp29_;
	const gchar* _tmp30_;
	gint64* _tmp31_;
	gint _tmp31__length1;
	IDArray _tmp32_ = {0};
	GtkLabel* _tmp33_;
	GtkContainer* _tmp34_;
	GtkContainer* _tmp35_;
	const gchar* _tmp36_;
	self = _data16_->self;
	_tmp0_ = _data16_->name1;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	gname = _tmp3_;
	_tmp4_ = self->priv->group_map;
	_tmp5_ = gname;
	if (gee_abstract_map_has_key ((GeeAbstractMap*) _tmp4_, _tmp5_)) {
		_g_free0 (gname);
		return;
	}
	_tmp6_ = gname;
	_tmp7_ = (GtkLabel*) gtk_label_new (_tmp6_);
	g_object_ref_sink (_tmp7_);
	label1 = _tmp7_;
	_tmp8_ = self->priv->groups;
	_tmp9_ = _data16_->name1;
	gtk_container_remove ((GtkContainer*) _tmp8_, (GtkWidget*) _tmp9_);
	_tmp10_ = _data16_->name1;
	gtk_widget_destroy ((GtkWidget*) _tmp10_);
	_tmp11_ = self->priv->groups;
	_tmp12_ = label1;
	gtk_container_add ((GtkContainer*) _tmp11_, (GtkWidget*) _tmp12_);
	_tmp13_ = label1;
	gtk_widget_show ((GtkWidget*) _tmp13_);
	_tmp14_ = self->priv->ids;
	_tmp15_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_new0 (gint64, _tmp16_);
	idsi = _tmp17_;
	idsi_length1 = _tmp16_;
	_idsi_size_ = idsi_length1;
	i = 0;
	{
		GeeIterator* _id1_it = NULL;
		GeeHashSet* _tmp18_;
		GeeIterator* _tmp19_;
		_tmp18_ = self->priv->ids;
		_tmp19_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) _tmp18_);
		_id1_it = _tmp19_;
		while (TRUE) {
			GeeIterator* _tmp20_;
			gint64 id1 = 0LL;
			GeeIterator* _tmp21_;
			gpointer _tmp22_;
			gint64* _tmp23_;
			gint64 _tmp24_;
			gint64* _tmp25_;
			gint _tmp25__length1;
			gint _tmp26_;
			gint64 _tmp27_;
			gint _tmp28_;
			_tmp20_ = _id1_it;
			if (!gee_iterator_next (_tmp20_)) {
				break;
			}
			_tmp21_ = _id1_it;
			_tmp22_ = gee_iterator_get (_tmp21_);
			_tmp23_ = (gint64*) _tmp22_;
			_tmp24_ = *_tmp23_;
			_g_free0 (_tmp23_);
			id1 = _tmp24_;
			_tmp25_ = idsi;
			_tmp25__length1 = idsi_length1;
			_tmp26_ = i;
			_tmp27_ = id1;
			_tmp25_[_tmp26_] = _tmp27_;
			_tmp28_ = i;
			i = _tmp28_ + 1;
		}
		_g_object_unref0 (_id1_it);
	}
	_tmp29_ = self->priv->group_map;
	_tmp30_ = gname;
	_tmp31_ = idsi;
	_tmp31__length1 = idsi_length1;
	_tmp32_.ids = (g_free (_tmp32_.ids), NULL);
	_tmp32_.ids = _tmp31_;
	_tmp32_.ids_length1 = _tmp31__length1;
	_tmp32_._ids_size_ = _tmp32_.ids_length1;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp29_, _tmp30_, &_tmp32_);
	_tmp33_ = label1;
	_tmp34_ = gtk_widget_get_parent ((GtkWidget*) _tmp33_);
	_tmp35_ = _tmp34_;
	_tmp36_ = gname;
	gtk_widget_set_name ((GtkWidget*) (G_TYPE_CHECK_INSTANCE_TYPE (_tmp35_, gtk_list_box_row_get_type ()) ? ((GtkListBoxRow*) _tmp35_) : NULL), _tmp36_);
	idsi = (g_free (idsi), NULL);
	_g_object_unref0 (label1);
	_g_free0 (gname);
}


static void
___lambda46__gtk_entry_activate (GtkEntry* _sender,
                                 gpointer self)
{
	__lambda46_ (self);
}


static void
__lambda45_ (MultiSendUi* self)
{
	Block16Data* _data16_;
	GeeHashSet* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GtkEntry* _tmp3_;
	GtkListBox* _tmp4_;
	GtkEntry* _tmp5_;
	GtkEntry* _tmp6_;
	GeeHashSet* _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	GtkEntry* _tmp14_;
	GtkEntry* _tmp15_;
	GtkEntry* _tmp16_;
	_data16_ = g_slice_new0 (Block16Data);
	_data16_->_ref_count_ = 1;
	_data16_->self = g_object_ref (self);
	_tmp0_ = self->priv->ids;
	_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ == 0) {
		block16_data_unref (_data16_);
		_data16_ = NULL;
		return;
	}
	_tmp3_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp3_);
	_data16_->name1 = _tmp3_;
	_tmp4_ = self->priv->groups;
	_tmp5_ = _data16_->name1;
	gtk_container_add ((GtkContainer*) _tmp4_, (GtkWidget*) _tmp5_);
	_tmp6_ = _data16_->name1;
	_tmp7_ = self->priv->ids;
	_tmp8_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strdup_printf ("%i", _tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, " persons group", NULL);
	_tmp13_ = _tmp12_;
	gtk_entry_set_text (_tmp6_, _tmp13_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	_tmp14_ = _data16_->name1;
	gtk_widget_show ((GtkWidget*) _tmp14_);
	_tmp15_ = _data16_->name1;
	gtk_entry_grab_focus_without_selecting (_tmp15_);
	_tmp16_ = _data16_->name1;
	g_signal_connect_data (_tmp16_, "activate", (GCallback) ___lambda46__gtk_entry_activate, block16_data_ref (_data16_), (GClosureNotify) block16_data_unref, 0);
	block16_data_unref (_data16_);
	_data16_ = NULL;
}


static void
___lambda45__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
	__lambda45_ ((MultiSendUi*) self);
}


static void
multi_send_ui_set_save_callback (MultiSendUi* self)
{
	GtkButton* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->save1;
	g_signal_connect_object (_tmp0_, "clicked", (GCallback) ___lambda45__gtk_button_clicked, self, 0);
}


static void
__lambda44_ (MultiSendUi* self)
{
	gint64* idsi = NULL;
	GeeHashSet* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint64* _tmp3_;
	gint idsi_length1;
	gint _idsi_size_;
	gint i = 0;
	GtkEntry* _tmp20_;
	const gchar* _tmp21_;
	const gchar* _tmp22_;
	gint _tmp23_;
	gint _tmp24_;
	ChatClient* _tmp25_;
	gint64* _tmp26_;
	gint _tmp26__length1;
	GtkEntry* _tmp27_;
	const gchar* _tmp28_;
	const gchar* _tmp29_;
	GtkEntry* _tmp30_;
	_tmp0_ = self->priv->ids;
	_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_new0 (gint64, _tmp2_);
	idsi = _tmp3_;
	idsi_length1 = _tmp2_;
	_idsi_size_ = idsi_length1;
	i = 0;
	{
		GeeIterator* _id1_it = NULL;
		GeeHashSet* _tmp4_;
		GeeIterator* _tmp5_;
		_tmp4_ = self->priv->ids;
		_tmp5_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) _tmp4_);
		_id1_it = _tmp5_;
		while (TRUE) {
			GeeIterator* _tmp6_;
			gint64 id1 = 0LL;
			GeeIterator* _tmp7_;
			gpointer _tmp8_;
			gint64* _tmp9_;
			gint64 _tmp10_;
			gint64* _tmp11_;
			gint _tmp11__length1;
			gint _tmp12_;
			gint64 _tmp13_;
			MyGrid* _tmp14_;
			gint64 _tmp15_;
			GtkEntry* _tmp16_;
			const gchar* _tmp17_;
			const gchar* _tmp18_;
			gint _tmp19_;
			_tmp6_ = _id1_it;
			if (!gee_iterator_next (_tmp6_)) {
				break;
			}
			_tmp7_ = _id1_it;
			_tmp8_ = gee_iterator_get (_tmp7_);
			_tmp9_ = (gint64*) _tmp8_;
			_tmp10_ = *_tmp9_;
			_g_free0 (_tmp9_);
			id1 = _tmp10_;
			_tmp11_ = idsi;
			_tmp11__length1 = idsi_length1;
			_tmp12_ = i;
			_tmp13_ = id1;
			_tmp11_[_tmp12_] = _tmp13_;
			_tmp14_ = grid1;
			_tmp15_ = id1;
			_tmp16_ = self->priv->entry1;
			_tmp17_ = gtk_entry_get_text (_tmp16_);
			_tmp18_ = _tmp17_;
			my_grid_show_sended_msg_to (_tmp14_, _tmp15_, _tmp18_);
			_tmp19_ = i;
			i = _tmp19_ + 1;
		}
		_g_object_unref0 (_id1_it);
	}
	_tmp20_ = self->priv->entry1;
	_tmp21_ = gtk_entry_get_text (_tmp20_);
	_tmp22_ = _tmp21_;
	_tmp23_ = strlen (_tmp22_);
	_tmp24_ = _tmp23_;
	if (_tmp24_ == 0) {
		idsi = (g_free (idsi), NULL);
		return;
	}
	_tmp25_ = client;
	_tmp26_ = idsi;
	_tmp26__length1 = idsi_length1;
	_tmp27_ = self->priv->entry1;
	_tmp28_ = gtk_entry_get_text (_tmp27_);
	_tmp29_ = _tmp28_;
	chat_client_multi_send (_tmp25_, _tmp26_, _tmp26__length1, _tmp29_);
	_tmp30_ = self->priv->entry1;
	gtk_entry_set_text (_tmp30_, "");
	idsi = (g_free (idsi), NULL);
}


static void
___lambda44__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
	__lambda44_ ((MultiSendUi*) self);
}


static void
multi_send_ui_set_send_callback (MultiSendUi* self)
{
	GtkButton* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->send1;
	g_signal_connect_object (_tmp0_, "clicked", (GCallback) ___lambda44__gtk_button_clicked, self, 0);
}


static void
multi_send_ui_set_css (MultiSendUi* self)
{
	GtkCssProvider* cssp = NULL;
	GtkCssProvider* _tmp0_;
	GtkStyleContext* sc = NULL;
	GtkListBox* _tmp1_;
	GtkStyleContext* _tmp2_;
	GtkStyleContext* _tmp3_;
	GtkStyleContext* _tmp4_;
	GtkListBox* _tmp5_;
	GtkStyleContext* _tmp6_;
	GtkStyleContext* _tmp7_;
	GtkStyleContext* _tmp8_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_css_provider_new ();
	cssp = _tmp0_;
	_tmp1_ = self->priv->friends;
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) _tmp1_);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	sc = _tmp3_;
	_tmp4_ = sc;
	gtk_style_context_add_provider (_tmp4_, (GtkStyleProvider*) cssp, (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
	_tmp5_ = self->priv->groups;
	_tmp6_ = gtk_widget_get_style_context ((GtkWidget*) _tmp5_);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	_g_object_unref0 (sc);
	sc = _tmp7_;
	_tmp8_ = sc;
	gtk_style_context_add_provider (_tmp8_, (GtkStyleProvider*) cssp, (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
	gtk_css_provider_load_from_data (cssp, "\n" \
"list{\n" \
"\tbackground-color:#FFFFFF;\n" \
"\tcolor:#000000;\n" \
"\tborder-width:1px;\n" \
"\tborder-style:solid;\n" \
"\tborder-color:black;\n" \
"}\n", (gssize) -1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (sc);
		_g_object_unref0 (cssp);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (sc);
	_g_object_unref0 (cssp);
}


void
multi_send_ui_show (MultiSendUi* self)
{
	GtkDialog* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->frame1;
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
	multi_send_ui_load_groups (self);
}


static void
multi_send_ui_set_lists (MultiSendUi* self)
{
	gchar* suid = NULL;
	MyGrid* _tmp0_;
	gint64 _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = grid1;
	_tmp1_ = _tmp0_->uid;
	_tmp2_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp1_);
	suid = _tmp2_;
	{
		GeeIterator* _id1_it = NULL;
		MyGrid* _tmp3_;
		GeeHashMap* _tmp4_;
		GeeSet* _tmp5_;
		GeeSet* _tmp6_;
		GeeSet* _tmp7_;
		GeeIterator* _tmp8_;
		GeeIterator* _tmp9_;
		_tmp3_ = grid1;
		_tmp4_ = _tmp3_->frds1;
		_tmp5_ = gee_abstract_map_get_keys ((GeeAbstractMap*) _tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = _tmp6_;
		_tmp8_ = gee_iterable_iterator ((GeeIterable*) _tmp7_);
		_tmp9_ = _tmp8_;
		_g_object_unref0 (_tmp7_);
		_id1_it = _tmp9_;
		while (TRUE) {
			GeeIterator* _tmp10_;
			gchar* id1 = NULL;
			GeeIterator* _tmp11_;
			gpointer _tmp12_;
			const gchar* _tmp13_;
			const gchar* _tmp14_;
			MyGrid* _tmp15_;
			GeeHashMap* _tmp16_;
			const gchar* _tmp17_;
			gpointer _tmp18_;
			UserMsg* _tmp19_;
			UserMsg _tmp20_;
			_tmp10_ = _id1_it;
			if (!gee_iterator_next (_tmp10_)) {
				break;
			}
			_tmp11_ = _id1_it;
			_tmp12_ = gee_iterator_get (_tmp11_);
			id1 = (gchar*) _tmp12_;
			_tmp13_ = suid;
			_tmp14_ = id1;
			if (g_strcmp0 (_tmp13_, _tmp14_) == 0) {
				_g_free0 (id1);
				continue;
			}
			_tmp15_ = grid1;
			_tmp16_ = _tmp15_->frds1;
			_tmp17_ = id1;
			_tmp18_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp16_, _tmp17_);
			_tmp19_ = (UserMsg*) _tmp18_;
			_tmp20_ = *_tmp19_;
			multi_send_ui_add_friend (self, &_tmp20_);
			_user_msg_free0 (_tmp19_);
			_g_free0 (id1);
		}
		_g_object_unref0 (_id1_it);
	}
	_g_free0 (suid);
}


static Block17Data*
block17_data_ref (Block17Data* _data17_)
{
	g_atomic_int_inc (&_data17_->_ref_count_);
	return _data17_;
}


static void
block17_data_unref (void * _userdata_)
{
	Block17Data* _data17_;
	_data17_ = (Block17Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data17_->_ref_count_)) {
		MultiSendUi* self;
		self = _data17_->self;
		_g_object_unref0 (_data17_->button1);
		user_msg_destroy (&_data17_->u1);
		_g_object_unref0 (self);
		g_slice_free (Block17Data, _data17_);
	}
}


static void
__lambda43_ (Block17Data* _data17_)
{
	MultiSendUi* self;
	gboolean _tmp0_;
	gboolean _tmp1_;
	self = _data17_->self;
	_tmp0_ = gtk_toggle_button_get_active ((GtkToggleButton*) _data17_->button1);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		GeeHashSet* _tmp2_;
		UserMsg _tmp3_;
		gint64 _tmp4_;
		_tmp2_ = self->priv->ids;
		_tmp3_ = _data17_->u1;
		_tmp4_ = _tmp3_.id;
		if (gee_abstract_collection_contains ((GeeAbstractCollection*) _tmp2_, &_tmp4_) == FALSE) {
			GeeHashSet* _tmp5_;
			UserMsg _tmp6_;
			gint64 _tmp7_;
			_tmp5_ = self->priv->ids;
			_tmp6_ = _data17_->u1;
			_tmp7_ = _tmp6_.id;
			gee_abstract_collection_add ((GeeAbstractCollection*) _tmp5_, &_tmp7_);
		}
	} else {
		GeeHashSet* _tmp8_;
		UserMsg _tmp9_;
		gint64 _tmp10_;
		_tmp8_ = self->priv->ids;
		_tmp9_ = _data17_->u1;
		_tmp10_ = _tmp9_.id;
		if (gee_abstract_collection_contains ((GeeAbstractCollection*) _tmp8_, &_tmp10_)) {
			GeeHashSet* _tmp11_;
			UserMsg _tmp12_;
			gint64 _tmp13_;
			_tmp11_ = self->priv->ids;
			_tmp12_ = _data17_->u1;
			_tmp13_ = _tmp12_.id;
			gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp11_, &_tmp13_);
		}
	}
}


static void
___lambda43__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                        gpointer self)
{
	__lambda43_ (self);
}


static void
multi_send_ui_add_friend (MultiSendUi* self,
                          UserMsg* u1)
{
	Block17Data* _data17_;
	UserMsg _tmp0_;
	UserMsg _tmp1_ = {0};
	UserMsg _tmp2_;
	const gchar* _tmp3_;
	GtkCheckButton* _tmp4_;
	UserMsg _tmp5_;
	gint64 _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	GtkListBox* _tmp9_;
	GtkContainer* _tmp10_;
	GtkContainer* _tmp11_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (u1 != NULL);
	_data17_ = g_slice_new0 (Block17Data);
	_data17_->_ref_count_ = 1;
	_data17_->self = g_object_ref (self);
	_tmp0_ = *u1;
	user_msg_copy (&_tmp0_, &_tmp1_);
	user_msg_destroy (&_data17_->u1);
	_data17_->u1 = _tmp1_;
	_tmp2_ = _data17_->u1;
	_tmp3_ = _tmp2_.name;
	_tmp4_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp3_);
	g_object_ref_sink (_tmp4_);
	_data17_->button1 = _tmp4_;
	_tmp5_ = _data17_->u1;
	_tmp6_ = _tmp5_.id;
	_tmp7_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp6_);
	_tmp8_ = _tmp7_;
	gtk_widget_set_name ((GtkWidget*) _data17_->button1, _tmp8_);
	_g_free0 (_tmp8_);
	_tmp9_ = self->priv->friends;
	gtk_container_add ((GtkContainer*) _tmp9_, (GtkWidget*) _data17_->button1);
	gtk_widget_show ((GtkWidget*) _data17_->button1);
	_tmp10_ = gtk_widget_get_parent ((GtkWidget*) _data17_->button1);
	_tmp11_ = _tmp10_;
	gtk_list_box_row_set_selectable (G_TYPE_CHECK_INSTANCE_TYPE (_tmp11_, gtk_list_box_row_get_type ()) ? ((GtkListBoxRow*) _tmp11_) : NULL, FALSE);
	g_signal_connect_data ((GtkToggleButton*) _data17_->button1, "toggled", (GCallback) ___lambda43__gtk_toggle_button_toggled, block17_data_ref (_data17_), (GClosureNotify) block17_data_unref, 0);
	block17_data_unref (_data17_);
	_data17_ = NULL;
}


static gint64*
_vala_array_dup2 (gint64* self,
                  int length)
{
	return g_memdup (self, length * sizeof (gint64));
}


static gpointer
_g_variant_ref0 (gpointer self)
{
	return self ? g_variant_ref (self) : NULL;
}


static void
multi_send_ui_on_select_destroy (MultiSendUi* self)
{
	GeeHashMap* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GVariant** arrayv = NULL;
	GeeHashMap* _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	GVariant** _tmp6_;
	gint arrayv_length1;
	gint _arrayv_size_;
	gint n = 0;
	GVariant* res = NULL;
	GVariant** _tmp47_;
	gint _tmp47__length1;
	GVariant* _tmp48_;
	gsize len1 = 0UL;
	gchar* data1 = NULL;
	GVariant* _tmp49_;
	gsize _tmp50_ = 0UL;
	gchar* _tmp51_;
	const gchar* _tmp52_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->group_map;
	_tmp1_ = gee_abstract_map_get_size ((GeeAbstractMap*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ == 0) {
		multi_send_ui_save_groups (self, "\n");
		return;
	}
	_tmp3_ = self->priv->group_map;
	_tmp4_ = gee_abstract_map_get_size ((GeeAbstractMap*) _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_new0 (GVariant*, _tmp5_ + 1);
	arrayv = _tmp6_;
	arrayv_length1 = _tmp5_;
	_arrayv_size_ = arrayv_length1;
	n = 0;
	{
		GeeIterator* _k1_it = NULL;
		GeeHashMap* _tmp7_;
		GeeSet* _tmp8_;
		GeeSet* _tmp9_;
		GeeSet* _tmp10_;
		GeeIterator* _tmp11_;
		GeeIterator* _tmp12_;
		_tmp7_ = self->priv->group_map;
		_tmp8_ = gee_abstract_map_get_keys ((GeeAbstractMap*) _tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = _tmp9_;
		_tmp11_ = gee_iterable_iterator ((GeeIterable*) _tmp10_);
		_tmp12_ = _tmp11_;
		_g_object_unref0 (_tmp10_);
		_k1_it = _tmp12_;
		while (TRUE) {
			GeeIterator* _tmp13_;
			gchar* k1 = NULL;
			GeeIterator* _tmp14_;
			gpointer _tmp15_;
			gint64* v = NULL;
			GeeHashMap* _tmp16_;
			const gchar* _tmp17_;
			gpointer _tmp18_;
			IDArray* _tmp19_;
			gint64* _tmp20_;
			gint _tmp20__length1;
			gint64* _tmp21_;
			gint _tmp21__length1;
			gint64* _tmp22_;
			gint _tmp22__length1;
			gint v_length1;
			gint _v_size_;
			GVariant** data = NULL;
			gint64* _tmp23_;
			gint _tmp23__length1;
			GVariant** _tmp24_;
			gint data_length1;
			gint _data_size_;
			GVariant* ids = NULL;
			GVariant** _tmp35_;
			gint _tmp35__length1;
			GVariant* _tmp36_;
			GVariant* name = NULL;
			const gchar* _tmp37_;
			GVariant* _tmp38_;
			GVariant* objv = NULL;
			GVariant* _tmp39_;
			GVariant* _tmp40_;
			GVariant* _tmp41_;
			GVariant** _tmp42_;
			gint _tmp42__length1;
			gint _tmp43_;
			GVariant* _tmp44_;
			GVariant* _tmp45_;
			gint _tmp46_;
			_tmp13_ = _k1_it;
			if (!gee_iterator_next (_tmp13_)) {
				break;
			}
			_tmp14_ = _k1_it;
			_tmp15_ = gee_iterator_get (_tmp14_);
			k1 = (gchar*) _tmp15_;
			_tmp16_ = self->priv->group_map;
			_tmp17_ = k1;
			_tmp18_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp16_, _tmp17_);
			_tmp19_ = (IDArray*) _tmp18_;
			_tmp20_ = (*_tmp19_).ids;
			_tmp20__length1 = (*_tmp19_).ids_length1;
			_tmp21_ = (_tmp20_ != NULL) ? _vala_array_dup2 (_tmp20_, _tmp20__length1) : ((gpointer) _tmp20_);
			_tmp21__length1 = _tmp20__length1;
			_tmp22_ = _tmp21_;
			_tmp22__length1 = _tmp21__length1;
			_id_array_free0 (_tmp19_);
			v = _tmp22_;
			v_length1 = _tmp22__length1;
			_v_size_ = v_length1;
			_tmp23_ = v;
			_tmp23__length1 = v_length1;
			_tmp24_ = g_new0 (GVariant*, _tmp23__length1 + 1);
			data = _tmp24_;
			data_length1 = _tmp23__length1;
			_data_size_ = data_length1;
			{
				gint i = 0;
				i = 0;
				{
					gboolean _tmp25_ = FALSE;
					_tmp25_ = TRUE;
					while (TRUE) {
						gint _tmp27_;
						gint64* _tmp28_;
						gint _tmp28__length1;
						GVariant** _tmp29_;
						gint _tmp29__length1;
						gint _tmp30_;
						gint64* _tmp31_;
						gint _tmp31__length1;
						gint _tmp32_;
						gint64 _tmp33_;
						GVariant* _tmp34_;
						if (!_tmp25_) {
							gint _tmp26_;
							_tmp26_ = i;
							i = _tmp26_ + 1;
						}
						_tmp25_ = FALSE;
						_tmp27_ = i;
						_tmp28_ = v;
						_tmp28__length1 = v_length1;
						if (!(_tmp27_ < _tmp28__length1)) {
							break;
						}
						_tmp29_ = data;
						_tmp29__length1 = data_length1;
						_tmp30_ = i;
						_tmp31_ = v;
						_tmp31__length1 = v_length1;
						_tmp32_ = i;
						_tmp33_ = _tmp31_[_tmp32_];
						_tmp34_ = g_variant_new_int64 (_tmp33_);
						g_variant_ref_sink (_tmp34_);
						_g_variant_unref0 (_tmp29_[_tmp30_]);
						_tmp29_[_tmp30_] = _tmp34_;
					}
				}
			}
			_tmp35_ = data;
			_tmp35__length1 = data_length1;
			_tmp36_ = g_variant_new_tuple (_tmp35_, _tmp35__length1);
			g_variant_ref_sink (_tmp36_);
			ids = _tmp36_;
			_tmp37_ = k1;
			_tmp38_ = g_variant_new_string (_tmp37_);
			g_variant_ref_sink (_tmp38_);
			name = _tmp38_;
			_tmp39_ = name;
			_tmp40_ = ids;
			_tmp41_ = g_variant_new_parsed ("{'Name':%v,'Ids':%v}", _tmp39_, _tmp40_, NULL);
			g_variant_ref_sink (_tmp41_);
			objv = _tmp41_;
			_tmp42_ = arrayv;
			_tmp42__length1 = arrayv_length1;
			_tmp43_ = n;
			_tmp44_ = objv;
			_tmp45_ = _g_variant_ref0 (_tmp44_);
			_g_variant_unref0 (_tmp42_[_tmp43_]);
			_tmp42_[_tmp43_] = _tmp45_;
			_tmp46_ = n;
			n = _tmp46_ + 1;
			_g_variant_unref0 (objv);
			_g_variant_unref0 (name);
			_g_variant_unref0 (ids);
			data = (_vala_array_free (data, data_length1, (GDestroyNotify) g_variant_unref), NULL);
			v = (g_free (v), NULL);
			_g_free0 (k1);
		}
		_g_object_unref0 (_k1_it);
	}
	_tmp47_ = arrayv;
	_tmp47__length1 = arrayv_length1;
	_tmp48_ = g_variant_new_tuple (_tmp47_, _tmp47__length1);
	g_variant_ref_sink (_tmp48_);
	res = _tmp48_;
	_tmp49_ = res;
	_tmp51_ = json_gvariant_serialize_data (_tmp49_, &_tmp50_);
	len1 = _tmp50_;
	data1 = _tmp51_;
	_tmp52_ = data1;
	multi_send_ui_save_groups (self, _tmp52_);
	_g_free0 (data1);
	_g_variant_unref0 (res);
	arrayv = (_vala_array_free (arrayv, arrayv_length1, (GDestroyNotify) g_variant_unref), NULL);
}


static void
multi_send_ui_save_groups (MultiSendUi* self,
                           const gchar* data)
{
	gchar* filename = NULL;
	MyGrid* _tmp0_;
	gint64 _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	GFile* fp = NULL;
	const gchar* _tmp8_;
	GFile* _tmp9_;
	GFileOutputStream* fs = NULL;
	GDataOutputStream* dos = NULL;
	GFileOutputStream* _tmp20_;
	GDataOutputStream* _tmp21_;
	GDataOutputStream* _tmp22_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (data != NULL);
	_tmp0_ = grid1;
	_tmp1_ = _tmp0_->uid;
	_tmp2_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = get_cfg_dir (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_build_path (G_DIR_SEPARATOR_S, _tmp5_, "groups.json", NULL);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	filename = _tmp7_;
	_tmp8_ = filename;
	_tmp9_ = g_file_new_for_path (_tmp8_);
	fp = _tmp9_;
	{
		GFileOutputStream* _tmp10_ = NULL;
		GFile* _tmp11_;
		GFileOutputStream* _tmp12_;
		GFileOutputStream* _tmp13_;
		_tmp11_ = fp;
		_tmp12_ = g_file_create (_tmp11_, G_FILE_CREATE_PRIVATE, NULL, &_inner_error0_);
		_tmp10_ = _tmp12_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch5_g_error;
		}
		_tmp13_ = _tmp10_;
		_tmp10_ = NULL;
		_g_object_unref0 (fs);
		fs = _tmp13_;
		_g_object_unref0 (_tmp10_);
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e1 = NULL;
		e1 = _inner_error0_;
		_inner_error0_ = NULL;
		{
			GFileOutputStream* _tmp14_ = NULL;
			GFile* _tmp15_;
			GFileOutputStream* _tmp16_;
			GFileOutputStream* _tmp17_;
			_tmp15_ = fp;
			_tmp16_ = g_file_replace (_tmp15_, NULL, FALSE, G_FILE_CREATE_PRIVATE, NULL, &_inner_error0_);
			_tmp14_ = _tmp16_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				goto __catch6_g_error;
			}
			_tmp17_ = _tmp14_;
			_tmp14_ = NULL;
			_g_object_unref0 (fs);
			fs = _tmp17_;
			_g_object_unref0 (_tmp14_);
		}
		goto __finally6;
		__catch6_g_error:
		{
			GError* e2 = NULL;
			GError* _tmp18_;
			const gchar* _tmp19_;
			e2 = _inner_error0_;
			_inner_error0_ = NULL;
			_tmp18_ = e2;
			_tmp19_ = _tmp18_->message;
			g_print ("write name Error: %s\n", _tmp19_);
			_g_error_free0 (e2);
			_g_error_free0 (e1);
			_g_object_unref0 (fs);
			_g_object_unref0 (fp);
			_g_free0 (filename);
			return;
		}
		__finally6:
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_error_free0 (e1);
			_g_error_free0 (e1);
			_g_object_unref0 (fs);
			_g_object_unref0 (fp);
			_g_free0 (filename);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_g_error_free0 (e1);
	}
	__finally5:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (fs);
		_g_object_unref0 (fp);
		_g_free0 (filename);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp20_ = fs;
	_tmp21_ = g_data_output_stream_new (G_TYPE_CHECK_INSTANCE_TYPE (_tmp20_, g_output_stream_get_type ()) ? ((GOutputStream*) _tmp20_) : NULL);
	dos = _tmp21_;
	_tmp22_ = dos;
	g_data_output_stream_put_string (_tmp22_, data, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (dos);
		_g_object_unref0 (fs);
		_g_object_unref0 (fp);
		_g_free0 (filename);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (dos);
	_g_object_unref0 (fs);
	_g_object_unref0 (fp);
	_g_free0 (filename);
}


static void
multi_send_ui_load_groups (MultiSendUi* self)
{
	gchar* filename = NULL;
	MyGrid* _tmp0_;
	gint64 _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	GFile* fp = NULL;
	const gchar* _tmp8_;
	GFile* _tmp9_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = grid1;
	_tmp1_ = _tmp0_->uid;
	_tmp2_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = get_cfg_dir (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_build_path (G_DIR_SEPARATOR_S, _tmp5_, "groups.json", NULL);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	filename = _tmp7_;
	_tmp8_ = filename;
	_tmp9_ = g_file_new_for_path (_tmp8_);
	fp = _tmp9_;
	{
		GFileInputStream* fs = NULL;
		GFile* _tmp10_;
		GFileInputStream* _tmp11_;
		GDataInputStream* dis = NULL;
		GFileInputStream* _tmp12_;
		GDataInputStream* _tmp13_;
		gchar* data = NULL;
		GDataInputStream* _tmp14_;
		gchar* _tmp15_;
		const gchar* _tmp16_;
		_tmp10_ = fp;
		_tmp11_ = g_file_read (_tmp10_, NULL, &_inner_error0_);
		fs = _tmp11_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch7_g_error;
		}
		_tmp12_ = fs;
		_tmp13_ = g_data_input_stream_new (G_TYPE_CHECK_INSTANCE_TYPE (_tmp12_, g_input_stream_get_type ()) ? ((GInputStream*) _tmp12_) : NULL);
		dis = _tmp13_;
		_tmp14_ = dis;
		_tmp15_ = g_data_input_stream_read_line (_tmp14_, NULL, NULL, &_inner_error0_);
		data = _tmp15_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (dis);
			_g_object_unref0 (fs);
			goto __catch7_g_error;
		}
		_tmp16_ = data;
		if (_tmp16_ != NULL) {
			GVariant* variant1 = NULL;
			const gchar* _tmp17_;
			GVariant* _tmp18_;
			_tmp17_ = data;
			_tmp18_ = json_gvariant_deserialize_data (_tmp17_, (gssize) -1, NULL, &_inner_error0_);
			if (_tmp18_ != NULL) {
				g_variant_ref_sink (_tmp18_);
			}
			variant1 = _tmp18_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (data);
				_g_object_unref0 (dis);
				_g_object_unref0 (fs);
				goto __catch7_g_error;
			}
			{
				gsize i = 0UL;
				i = (gsize) 0;
				{
					gboolean _tmp19_ = FALSE;
					_tmp19_ = TRUE;
					while (TRUE) {
						gsize _tmp21_;
						GVariant* _tmp22_;
						GVariant* g1 = NULL;
						GVariant* _tmp23_;
						gsize _tmp24_;
						GVariant* _tmp25_;
						GVariant* _tmp26_;
						GVariant* _tmp27_;
						GVariant* _tmp28_;
						gchar* name = NULL;
						GVariant* _tmp29_;
						GVariant* _tmp30_;
						GVariant* _tmp31_;
						const gchar* _tmp32_;
						gchar* _tmp33_;
						gchar* _tmp34_;
						GVariant* values = NULL;
						GVariant* _tmp35_;
						GVariant* _tmp36_;
						gint64* ids = NULL;
						GVariant* _tmp37_;
						gint64* _tmp38_;
						gint ids_length1;
						gint _ids_size_;
						GeeHashMap* _tmp51_;
						const gchar* _tmp52_;
						gint64* _tmp53_;
						gint _tmp53__length1;
						IDArray _tmp54_ = {0};
						GtkLabel* label1 = NULL;
						const gchar* _tmp55_;
						GtkLabel* _tmp56_;
						GtkListBox* _tmp57_;
						GtkLabel* _tmp58_;
						GtkLabel* _tmp59_;
						GtkLabel* _tmp60_;
						GtkContainer* _tmp61_;
						GtkContainer* _tmp62_;
						const gchar* _tmp63_;
						if (!_tmp19_) {
							gsize _tmp20_;
							_tmp20_ = i;
							i = _tmp20_ + 1;
						}
						_tmp19_ = FALSE;
						_tmp21_ = i;
						_tmp22_ = variant1;
						if (!(_tmp21_ < g_variant_n_children (_tmp22_))) {
							break;
						}
						_tmp23_ = variant1;
						_tmp24_ = i;
						_tmp25_ = g_variant_get_child_value (_tmp23_, _tmp24_);
						_tmp26_ = _tmp25_;
						_tmp27_ = g_variant_get_child_value (_tmp26_, (gsize) 0);
						_tmp28_ = _tmp27_;
						_g_variant_unref0 (_tmp26_);
						g1 = _tmp28_;
						_tmp29_ = g1;
						_tmp30_ = g_variant_lookup_value (_tmp29_, "Name", NULL);
						_tmp31_ = _tmp30_;
						_tmp32_ = g_variant_get_string (_tmp31_, NULL);
						_tmp33_ = g_strdup (_tmp32_);
						_tmp34_ = _tmp33_;
						_g_variant_unref0 (_tmp31_);
						name = _tmp34_;
						_tmp35_ = g1;
						_tmp36_ = g_variant_lookup_value (_tmp35_, "Ids", NULL);
						values = _tmp36_;
						_tmp37_ = values;
						_tmp38_ = g_new0 (gint64, g_variant_n_children (_tmp37_));
						ids = _tmp38_;
						ids_length1 = g_variant_n_children (_tmp37_);
						_ids_size_ = ids_length1;
						{
							gint n = 0;
							n = 0;
							{
								gboolean _tmp39_ = FALSE;
								_tmp39_ = TRUE;
								while (TRUE) {
									gint _tmp41_;
									gint64* _tmp42_;
									gint _tmp42__length1;
									GVariant* v1 = NULL;
									GVariant* _tmp43_;
									gint _tmp44_;
									GVariant* _tmp45_;
									gint64* _tmp46_;
									gint _tmp46__length1;
									gint _tmp47_;
									GVariant* _tmp48_;
									GVariant* _tmp49_;
									GVariant* _tmp50_;
									if (!_tmp39_) {
										gint _tmp40_;
										_tmp40_ = n;
										n = _tmp40_ + 1;
									}
									_tmp39_ = FALSE;
									_tmp41_ = n;
									_tmp42_ = ids;
									_tmp42__length1 = ids_length1;
									if (!(_tmp41_ < _tmp42__length1)) {
										break;
									}
									_tmp43_ = values;
									_tmp44_ = n;
									_tmp45_ = g_variant_get_child_value (_tmp43_, (gsize) _tmp44_);
									v1 = _tmp45_;
									_tmp46_ = ids;
									_tmp46__length1 = ids_length1;
									_tmp47_ = n;
									_tmp48_ = v1;
									_tmp49_ = g_variant_get_child_value (_tmp48_, (gsize) 0);
									_tmp50_ = _tmp49_;
									_tmp46_[_tmp47_] = g_variant_get_int64 (_tmp50_);
									_g_variant_unref0 (_tmp50_);
									_g_variant_unref0 (v1);
								}
							}
						}
						_tmp51_ = self->priv->group_map;
						_tmp52_ = name;
						_tmp53_ = ids;
						_tmp53__length1 = ids_length1;
						_tmp54_.ids = (g_free (_tmp54_.ids), NULL);
						_tmp54_.ids = _tmp53_;
						_tmp54_.ids_length1 = _tmp53__length1;
						_tmp54_._ids_size_ = _tmp54_.ids_length1;
						gee_abstract_map_set ((GeeAbstractMap*) _tmp51_, _tmp52_, &_tmp54_);
						_tmp55_ = name;
						_tmp56_ = (GtkLabel*) gtk_label_new (_tmp55_);
						g_object_ref_sink (_tmp56_);
						label1 = _tmp56_;
						_tmp57_ = self->priv->groups;
						_tmp58_ = label1;
						gtk_container_add ((GtkContainer*) _tmp57_, (GtkWidget*) _tmp58_);
						_tmp59_ = label1;
						gtk_widget_show ((GtkWidget*) _tmp59_);
						_tmp60_ = label1;
						_tmp61_ = gtk_widget_get_parent ((GtkWidget*) _tmp60_);
						_tmp62_ = _tmp61_;
						_tmp63_ = name;
						gtk_widget_set_name ((GtkWidget*) (G_TYPE_CHECK_INSTANCE_TYPE (_tmp62_, gtk_list_box_row_get_type ()) ? ((GtkListBoxRow*) _tmp62_) : NULL), _tmp63_);
						_g_object_unref0 (label1);
						ids = (g_free (ids), NULL);
						_g_variant_unref0 (values);
						_g_free0 (name);
						_g_variant_unref0 (g1);
					}
				}
			}
			_g_variant_unref0 (variant1);
		}
		_g_free0 (data);
		_g_object_unref0 (dis);
		_g_object_unref0 (fs);
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		GError* _tmp64_;
		const gchar* _tmp65_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp64_ = e;
		_tmp65_ = _tmp64_->message;
		g_print ("load name Error: %s\n", _tmp65_);
		_g_error_free0 (e);
	}
	__finally7:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (fp);
		_g_free0 (filename);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (fp);
	_g_free0 (filename);
}


static Block18Data*
block18_data_ref (Block18Data* _data18_)
{
	g_atomic_int_inc (&_data18_->_ref_count_);
	return _data18_;
}


static void
block18_data_unref (void * _userdata_)
{
	Block18Data* _data18_;
	_data18_ = (Block18Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data18_->_ref_count_)) {
		MultiSendUi* self;
		self = _data18_->self;
		_g_free0 (_data18_->name);
		_g_object_unref0 (self);
		g_slice_free (Block18Data, _data18_);
	}
}


static void
__lambda41_ (Block18Data* _data18_,
             GtkWidget* w)
{
	MultiSendUi* self;
	GtkListBoxRow* r = NULL;
	GtkListBoxRow* _tmp0_;
	GtkListBoxRow* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	self = _data18_->self;
	g_return_if_fail (w != NULL);
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (w, gtk_list_box_row_get_type ()) ? ((GtkListBoxRow*) w) : NULL);
	r = _tmp0_;
	_tmp1_ = r;
	_tmp2_ = gtk_widget_get_name ((GtkWidget*) _tmp1_);
	_tmp3_ = _tmp2_;
	if (g_strcmp0 (_tmp3_, _data18_->name) == 0) {
		GtkListBox* _tmp4_;
		GtkListBoxRow* _tmp5_;
		GtkListBoxRow* _tmp6_;
		GtkListBox* _tmp7_;
		_tmp4_ = self->priv->groups;
		_tmp5_ = r;
		gtk_container_remove ((GtkContainer*) _tmp4_, (GtkWidget*) _tmp5_);
		_tmp6_ = r;
		gtk_widget_destroy ((GtkWidget*) _tmp6_);
		_tmp7_ = self->priv->groups;
		gtk_widget_show_all ((GtkWidget*) _tmp7_);
	}
	_g_object_unref0 (r);
}


static void
___lambda41__gtk_callback (GtkWidget* widget,
                           gpointer self)
{
	__lambda41_ (self, widget);
}


void
multi_send_ui_remove_group_by_name (MultiSendUi* self,
                                    const gchar* name)
{
	Block18Data* _data18_;
	gchar* _tmp0_;
	GeeHashMap* _tmp1_;
	GtkListBox* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_data18_ = g_slice_new0 (Block18Data);
	_data18_->_ref_count_ = 1;
	_data18_->self = g_object_ref (self);
	_tmp0_ = g_strdup (name);
	_g_free0 (_data18_->name);
	_data18_->name = _tmp0_;
	_tmp1_ = self->priv->group_map;
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp1_, _data18_->name, NULL);
	_tmp2_ = self->priv->groups;
	gtk_container_foreach ((GtkContainer*) _tmp2_, ___lambda41__gtk_callback, _data18_);
	block18_data_unref (_data18_);
	_data18_ = NULL;
}


static gboolean
__lambda51_ (MultiSendUi* self,
             GdkEventButton* e)
{
	gboolean result = FALSE;
	guint _tmp0_;
	GtkListBoxRow* r = NULL;
	GtkListBox* _tmp1_;
	gdouble _tmp2_;
	GtkListBoxRow* _tmp3_;
	GtkListBoxRow* _tmp4_;
	GtkListBox* _tmp5_;
	GtkListBoxRow* _tmp6_;
	GroupPopup* _tmp7_;
	GtkListBoxRow* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	GroupPopup* _tmp11_;
	g_return_val_if_fail (e != NULL, FALSE);
	_tmp0_ = e->button;
	if (_tmp0_ != ((guint) 3)) {
		result = FALSE;
		return result;
	}
	_tmp1_ = self->priv->groups;
	_tmp2_ = e->y;
	_tmp3_ = gtk_list_box_get_row_at_y (_tmp1_, (gint) _tmp2_);
	_tmp4_ = _g_object_ref0 (_tmp3_);
	r = _tmp4_;
	_tmp5_ = self->priv->groups;
	_tmp6_ = r;
	gtk_list_box_select_row (_tmp5_, _tmp6_);
	_tmp7_ = self->priv->popup1;
	_tmp8_ = r;
	_tmp9_ = gtk_widget_get_name ((GtkWidget*) _tmp8_);
	_tmp10_ = _tmp9_;
	group_popup_set_name (_tmp7_, _tmp10_);
	_tmp11_ = self->priv->popup1;
	gtk_menu_popup_at_pointer ((GtkMenu*) _tmp11_, (GdkEvent*) e);
	result = TRUE;
	_g_object_unref0 (r);
	return result;
}


static gboolean
___lambda51__gtk_widget_button_release_event (GtkWidget* _sender,
                                              GdkEventButton* event,
                                              gpointer self)
{
	gboolean result;
	result = __lambda51_ ((MultiSendUi*) self, event);
	return result;
}


static void
multi_send_ui_set_popup (MultiSendUi* self)
{
	GtkListBox* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->groups;
	g_signal_connect_object ((GtkWidget*) _tmp0_, "button-release-event", (GCallback) ___lambda51__gtk_widget_button_release_event, self, 0);
}


static void
multi_send_ui_class_init (MultiSendUiClass * klass)
{
	multi_send_ui_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &MultiSendUi_private_offset);
	G_OBJECT_CLASS (klass)->finalize = multi_send_ui_finalize;
}


static void
multi_send_ui_instance_init (MultiSendUi * self)
{
	self->priv = multi_send_ui_get_instance_private (self);
	g_rec_mutex_init (&self->priv->__lock_group_map);
}


static void
multi_send_ui_finalize (GObject * obj)
{
	MultiSendUi * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MULTI_SEND_UI, MultiSendUi);
	_g_object_unref0 (self->priv->frame1);
	_g_object_unref0 (self->priv->grid_main);
	_g_object_unref0 (self->priv->friends);
	_g_object_unref0 (self->priv->groups);
	_g_object_unref0 (self->priv->entry1);
	_g_object_unref0 (self->priv->send1);
	_g_object_unref0 (self->priv->save1);
	_g_object_unref0 (self->priv->ids);
	g_rec_mutex_clear (&self->priv->__lock_group_map);
	_g_object_unref0 (self->priv->group_map);
	_g_object_unref0 (self->priv->popup1);
	G_OBJECT_CLASS (multi_send_ui_parent_class)->finalize (obj);
}


GType
multi_send_ui_get_type (void)
{
	static volatile gsize multi_send_ui_type_id__volatile = 0;
	if (g_once_init_enter (&multi_send_ui_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MultiSendUiClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) multi_send_ui_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MultiSendUi), 0, (GInstanceInitFunc) multi_send_ui_instance_init, NULL };
		GType multi_send_ui_type_id;
		multi_send_ui_type_id = g_type_register_static (G_TYPE_OBJECT, "MultiSendUi", &g_define_type_info, 0);
		MultiSendUi_private_offset = g_type_add_instance_private (multi_send_ui_type_id, sizeof (MultiSendUiPrivate));
		g_once_init_leave (&multi_send_ui_type_id__volatile, multi_send_ui_type_id);
	}
	return multi_send_ui_type_id__volatile;
}


static inline gpointer
group_popup_get_instance_private (GroupPopup* self)
{
	return G_STRUCT_MEMBER_P (self, GroupPopup_private_offset);
}


void
group_popup_set_name (GroupPopup* self,
                      const gchar* name)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = g_strdup (name);
	_g_free0 (self->priv->g_name);
	self->priv->g_name = _tmp0_;
}


static void
__lambda40_ (GroupPopup* self)
{
	MultiSendUi* _tmp0_;
	const gchar* _tmp1_;
	_tmp0_ = msend_ui;
	_tmp1_ = self->priv->g_name;
	multi_send_ui_remove_group_by_name (_tmp0_, _tmp1_);
}


static void
___lambda40__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda40_ ((GroupPopup*) self);
}


GroupPopup*
group_popup_construct (GType object_type)
{
	GroupPopup * self = NULL;
	GtkMenuItem* item2 = NULL;
	GtkMenuItem* _tmp0_;
	self = (GroupPopup*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_ ("Delete"));
	g_object_ref_sink (_tmp0_);
	item2 = _tmp0_;
	g_signal_connect_object (item2, "activate", (GCallback) ___lambda40__gtk_menu_item_activate, self, 0);
	gtk_menu_shell_append ((GtkMenuShell*) self, item2);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (item2);
	return self;
}


GroupPopup*
group_popup_new (void)
{
	return group_popup_construct (TYPE_GROUP_POPUP);
}


static void
group_popup_class_init (GroupPopupClass * klass)
{
	group_popup_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &GroupPopup_private_offset);
	G_OBJECT_CLASS (klass)->finalize = group_popup_finalize;
}


static void
group_popup_instance_init (GroupPopup * self)
{
	self->priv = group_popup_get_instance_private (self);
}


static void
group_popup_finalize (GObject * obj)
{
	GroupPopup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GROUP_POPUP, GroupPopup);
	_g_free0 (self->priv->g_name);
	G_OBJECT_CLASS (group_popup_parent_class)->finalize (obj);
}


GType
group_popup_get_type (void)
{
	static volatile gsize group_popup_type_id__volatile = 0;
	if (g_once_init_enter (&group_popup_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GroupPopupClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) group_popup_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GroupPopup), 0, (GInstanceInitFunc) group_popup_instance_init, NULL };
		GType group_popup_type_id;
		group_popup_type_id = g_type_register_static (gtk_menu_get_type (), "GroupPopup", &g_define_type_info, 0);
		GroupPopup_private_offset = g_type_add_instance_private (group_popup_type_id, sizeof (GroupPopupPrivate));
		g_once_init_leave (&group_popup_type_id__volatile, group_popup_type_id);
	}
	return group_popup_type_id__volatile;
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



