/* popup.vala.c generated by valac 0.42.6, the Vala compiler
 * generated from popup.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>


#define TYPE_MY_FRIEND_MENU (my_friend_menu_get_type ())
#define MY_FRIEND_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_FRIEND_MENU, MyFriendMenu))
#define MY_FRIEND_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_FRIEND_MENU, MyFriendMenuClass))
#define IS_MY_FRIEND_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_FRIEND_MENU))
#define IS_MY_FRIEND_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_FRIEND_MENU))
#define MY_FRIEND_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_FRIEND_MENU, MyFriendMenuClass))

typedef struct _MyFriendMenu MyFriendMenu;
typedef struct _MyFriendMenuClass MyFriendMenuClass;
typedef struct _MyFriendMenuPrivate MyFriendMenuPrivate;
enum  {
	MY_FRIEND_MENU_0_PROPERTY,
	MY_FRIEND_MENU_NUM_PROPERTIES
};
static GParamSpec* my_friend_menu_properties[MY_FRIEND_MENU_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_MY_GRID (my_grid_get_type ())
#define MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_GRID, MyGrid))
#define MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_GRID, MyGridClass))
#define IS_MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_GRID))
#define IS_MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_GRID))
#define MY_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_GRID, MyGridClass))

typedef struct _MyGrid MyGrid;
typedef struct _MyGridClass MyGridClass;

#define TYPE_CHAT_CLIENT (chat_client_get_type ())
#define CHAT_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CHAT_CLIENT, ChatClient))
#define CHAT_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CHAT_CLIENT, ChatClientClass))
#define IS_CHAT_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CHAT_CLIENT))
#define IS_CHAT_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CHAT_CLIENT))
#define CHAT_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CHAT_CLIENT, ChatClientClass))

typedef struct _ChatClient ChatClient;
typedef struct _ChatClientClass ChatClientClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _MyFriendMenu {
	GtkMenu parent_instance;
	MyFriendMenuPrivate * priv;
};

struct _MyFriendMenuClass {
	GtkMenuClass parent_class;
};

struct _MyFriendMenuPrivate {
	gchar* friend_id;
};


extern MyFriendMenu* popup1;
MyFriendMenu* popup1 = NULL;
static gint MyFriendMenu_private_offset;
static gpointer my_friend_menu_parent_class = NULL;
extern MyGrid* grid1;
extern ChatClient* client;

GType my_friend_menu_get_type (void) G_GNUC_CONST;
void my_friend_menu_set_id (MyFriendMenu* self,
                            const gchar* id);
MyFriendMenu* my_friend_menu_new (void);
MyFriendMenu* my_friend_menu_construct (GType object_type);
static void __lambda21_ (MyFriendMenu* self);
GType my_grid_get_type (void) G_GNUC_CONST;
void my_grid_user_online (MyGrid* self,
                          gint64 uid1);
GType chat_client_get_type (void) G_GNUC_CONST;
void chat_client_tell (ChatClient* self,
                       gint64 to);
static void ___lambda21__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda22_ (MyFriendMenu* self);
void my_grid_remove_friend (MyGrid* self,
                            const gchar* fid);
static void ___lambda22__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void my_friend_menu_finalize (GObject * obj);


static inline gpointer
my_friend_menu_get_instance_private (MyFriendMenu* self)
{
	return G_STRUCT_MEMBER_P (self, MyFriendMenu_private_offset);
}


void
my_friend_menu_set_id (MyFriendMenu* self,
                       const gchar* id)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (id != NULL);
	_tmp0_ = g_strdup (id);
	_g_free0 (self->priv->friend_id);
	self->priv->friend_id = _tmp0_;
}


static void
__lambda21_ (MyFriendMenu* self)
{
	MyGrid* _tmp0_;
	const gchar* _tmp1_;
	ChatClient* _tmp2_;
	const gchar* _tmp3_;
	_tmp0_ = grid1;
	_tmp1_ = self->priv->friend_id;
	my_grid_user_online (_tmp0_, g_ascii_strtoll (_tmp1_, NULL, 0));
	_tmp2_ = client;
	_tmp3_ = self->priv->friend_id;
	chat_client_tell (_tmp2_, g_ascii_strtoll (_tmp3_, NULL, 0));
}


static void
___lambda21__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda21_ ((MyFriendMenu*) self);
}


static void
__lambda22_ (MyFriendMenu* self)
{
	MyGrid* _tmp0_;
	const gchar* _tmp1_;
	_tmp0_ = grid1;
	_tmp1_ = self->priv->friend_id;
	my_grid_remove_friend (_tmp0_, _tmp1_);
}


static void
___lambda22__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda22_ ((MyFriendMenu*) self);
}


MyFriendMenu*
my_friend_menu_construct (GType object_type)
{
	MyFriendMenu * self = NULL;
	GtkMenuItem* item1 = NULL;
	GtkMenuItem* _tmp0_;
	GtkMenuItem* item2 = NULL;
	GtkMenuItem* _tmp1_;
	self = (MyFriendMenu*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_ ("Test Online"));
	g_object_ref_sink (_tmp0_);
	item1 = _tmp0_;
	g_signal_connect_object (item1, "activate", (GCallback) ___lambda21__gtk_menu_item_activate, self, 0);
	gtk_menu_shell_append ((GtkMenuShell*) self, item1);
	_tmp1_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_ ("Delete"));
	g_object_ref_sink (_tmp1_);
	item2 = _tmp1_;
	g_signal_connect_object (item2, "activate", (GCallback) ___lambda22__gtk_menu_item_activate, self, 0);
	gtk_menu_shell_append ((GtkMenuShell*) self, item2);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (item2);
	_g_object_unref0 (item1);
	return self;
}


MyFriendMenu*
my_friend_menu_new (void)
{
	return my_friend_menu_construct (TYPE_MY_FRIEND_MENU);
}


static void
my_friend_menu_class_init (MyFriendMenuClass * klass)
{
	my_friend_menu_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &MyFriendMenu_private_offset);
	G_OBJECT_CLASS (klass)->finalize = my_friend_menu_finalize;
}


static void
my_friend_menu_instance_init (MyFriendMenu * self)
{
	self->priv = my_friend_menu_get_instance_private (self);
}


static void
my_friend_menu_finalize (GObject * obj)
{
	MyFriendMenu * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MY_FRIEND_MENU, MyFriendMenu);
	_g_free0 (self->priv->friend_id);
	G_OBJECT_CLASS (my_friend_menu_parent_class)->finalize (obj);
}


GType
my_friend_menu_get_type (void)
{
	static volatile gsize my_friend_menu_type_id__volatile = 0;
	if (g_once_init_enter (&my_friend_menu_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyFriendMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_friend_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyFriendMenu), 0, (GInstanceInitFunc) my_friend_menu_instance_init, NULL };
		GType my_friend_menu_type_id;
		my_friend_menu_type_id = g_type_register_static (gtk_menu_get_type (), "MyFriendMenu", &g_define_type_info, 0);
		MyFriendMenu_private_offset = g_type_add_instance_private (my_friend_menu_type_id, sizeof (MyFriendMenuPrivate));
		g_once_init_leave (&my_friend_menu_type_id__volatile, my_friend_menu_type_id);
	}
	return my_friend_menu_type_id__volatile;
}



