/* adduser.c generated by valac 0.40.8, the Vala compiler
 * generated from adduser.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_ADD_USER_DIALOG (add_user_dialog_get_type ())
#define ADD_USER_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ADD_USER_DIALOG, AddUserDialog))
#define ADD_USER_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ADD_USER_DIALOG, AddUserDialogClass))
#define IS_ADD_USER_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ADD_USER_DIALOG))
#define IS_ADD_USER_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ADD_USER_DIALOG))
#define ADD_USER_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ADD_USER_DIALOG, AddUserDialogClass))

typedef struct _AddUserDialog AddUserDialog;
typedef struct _AddUserDialogClass AddUserDialogClass;
typedef struct _AddUserDialogPrivate AddUserDialogPrivate;
enum  {
	ADD_USER_DIALOG_0_PROPERTY,
	ADD_USER_DIALOG_NUM_PROPERTIES
};
static GParamSpec* add_user_dialog_properties[ADD_USER_DIALOG_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block8Data Block8Data;

#define TYPE_APP_WIN (app_win_get_type ())
#define APP_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APP_WIN, AppWin))
#define APP_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APP_WIN, AppWinClass))
#define IS_APP_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APP_WIN))
#define IS_APP_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APP_WIN))
#define APP_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APP_WIN, AppWinClass))

typedef struct _AppWin AppWin;
typedef struct _AppWinClass AppWinClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_RPC_CLIENT (rpc_client_get_type ())
#define RPC_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RPC_CLIENT, RpcClient))
#define RPC_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RPC_CLIENT, RpcClientClass))
#define IS_RPC_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RPC_CLIENT))
#define IS_RPC_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RPC_CLIENT))
#define RPC_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RPC_CLIENT, RpcClientClass))

typedef struct _RpcClient RpcClient;
typedef struct _RpcClientClass RpcClientClass;

#define TYPE_USER_DATA (user_data_get_type ())
typedef struct _UserData UserData;

#define TYPE_MY_GRID (my_grid_get_type ())
#define MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_GRID, MyGrid))
#define MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_GRID, MyGridClass))
#define IS_MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_GRID))
#define IS_MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_GRID))
#define MY_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_GRID, MyGridClass))

typedef struct _MyGrid MyGrid;
typedef struct _MyGridClass MyGridClass;
typedef struct _MyGridPrivate MyGridPrivate;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _AddUserDialog {
	GObject parent_instance;
	AddUserDialogPrivate * priv;
	GtkDialog* dlg1;
	GtkEntry* name;
	GtkEntry* pwd;
	gint birthyear;
	GtkEntry* desc;
	gint sex;
};

struct _AddUserDialogClass {
	GObjectClass parent_class;
};

struct _Block8Data {
	int _ref_count_;
	AddUserDialog* self;
	GtkComboBoxText* yearSelect;
	GtkComboBoxText* sexSelect;
};

struct _UserData {
	gint64 id;
	gint16 sex;
	gchar* name;
	gchar* desc;
	gint16 age;
	gchar* msg_offline;
	gchar* timestamp_offline;
};

struct _MyGrid {
	GObject parent_instance;
	MyGridPrivate * priv;
	GtkEntry* port1;
	GtkGrid* mygrid;
	GtkCssProvider* provider1;
	GtkCssProvider* mark1;
	GtkCssProvider* button1;
	GtkCssProvider* link_css1;
	GtkButton* strangers_btn;
	GtkButton* user_btn;
	gchar* man_icon;
	gchar* woman_icon;
	gint64 uid;
	gint16 usex;
	gchar* uname;
	gchar* udesc;
	gint16 uage;
};

struct _MyGridClass {
	GObjectClass parent_class;
};


static gpointer add_user_dialog_parent_class = NULL;
extern AppWin* app;
extern RpcClient* rpc1;
extern MyGrid* grid1;

GType add_user_dialog_get_type (void) G_GNUC_CONST;
AddUserDialog* add_user_dialog_new (void);
AddUserDialog* add_user_dialog_construct (GType object_type);
static Block8Data* block8_data_ref (Block8Data* _data8_);
static void block8_data_unref (void * _userdata_);
GType app_win_get_type (void) G_GNUC_CONST;
static void __lambda43_ (Block8Data* _data8_);
static void ___lambda43__gtk_combo_box_changed (GtkComboBox* _sender,
                                         gpointer self);
static void __lambda44_ (Block8Data* _data8_);
static void ___lambda44__gtk_combo_box_changed (GtkComboBox* _sender,
                                         gpointer self);
static void __lambda45_ (AddUserDialog* self,
                  gint rid);
GType rpc_client_get_type (void) G_GNUC_CONST;
gboolean rpc_client_add_user (RpcClient* self,
                              const gchar* name,
                              const gchar* pwd,
                              gint sex,
                              gint birthyear,
                              const gchar* desc);
GType user_data_get_type (void) G_GNUC_CONST;
UserData* user_data_dup (const UserData* self);
void user_data_free (UserData* self);
void user_data_copy (const UserData* self,
                     UserData* dest);
void user_data_destroy (UserData* self);
gint64 rpc_client_login (RpcClient* self,
                         const gchar* name,
                         const gchar* pwd,
                         UserData* u);
GType my_grid_get_type (void) G_GNUC_CONST;
gboolean rpc_client_get_friends_async (RpcClient* self);
static void ___lambda45__gtk_dialog_response (GtkDialog* _sender,
                                       gint response_id,
                                       gpointer self);
void add_user_dialog_show (AddUserDialog* self);
static void add_user_dialog_finalize (GObject * obj);


static Block8Data*
block8_data_ref (Block8Data* _data8_)
{
	g_atomic_int_inc (&_data8_->_ref_count_);
	return _data8_;
}


static void
block8_data_unref (void * _userdata_)
{
	Block8Data* _data8_;
	_data8_ = (Block8Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data8_->_ref_count_)) {
		AddUserDialog* self;
		self = _data8_->self;
		_g_object_unref0 (_data8_->sexSelect);
		_g_object_unref0 (_data8_->yearSelect);
		_g_object_unref0 (self);
		g_slice_free (Block8Data, _data8_);
	}
}


static void
__lambda43_ (Block8Data* _data8_)
{
	AddUserDialog* self;
	gchar* title = NULL;
	GtkComboBoxText* _tmp0_;
	gchar* _tmp1_;
	gint64 _tmp2_;
	self = _data8_->self;
	_tmp0_ = _data8_->yearSelect;
	_tmp1_ = gtk_combo_box_text_get_active_text (_tmp0_);
	title = _tmp1_;
	_tmp2_ = g_ascii_strtoll (title, NULL, 0);
	self->birthyear = (gint) _tmp2_;
	_g_free0 (title);
}


static void
___lambda43__gtk_combo_box_changed (GtkComboBox* _sender,
                                    gpointer self)
{
	__lambda43_ (self);
}


static void
__lambda44_ (Block8Data* _data8_)
{
	AddUserDialog* self;
	gint _tmp0_;
	gint _tmp1_;
	self = _data8_->self;
	_tmp0_ = gtk_combo_box_get_active ((GtkComboBox*) _data8_->sexSelect);
	_tmp1_ = _tmp0_;
	self->sex = _tmp1_ + 1;
}


static void
___lambda44__gtk_combo_box_changed (GtkComboBox* _sender,
                                    gpointer self)
{
	__lambda44_ (self);
}


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


static void
__lambda45_ (AddUserDialog* self,
             gint rid)
{
	if (rid == 2) {
		RpcClient* _tmp0_;
		GtkEntry* _tmp1_;
		const gchar* _tmp2_;
		const gchar* _tmp3_;
		GtkEntry* _tmp4_;
		const gchar* _tmp5_;
		const gchar* _tmp6_;
		gint _tmp7_;
		gint _tmp8_;
		GtkEntry* _tmp9_;
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		UserData u = {0};
		gint64 res = 0LL;
		RpcClient* _tmp13_;
		GtkEntry* _tmp14_;
		const gchar* _tmp15_;
		const gchar* _tmp16_;
		GtkEntry* _tmp17_;
		const gchar* _tmp18_;
		const gchar* _tmp19_;
		UserData _tmp20_ = {0};
		gint64 _tmp21_;
		gint64 _tmp22_;
		RpcClient* _tmp46_;
		GtkDialog* _tmp47_;
		AppWin* _tmp48_;
		_tmp0_ = rpc1;
		_tmp1_ = self->name;
		_tmp2_ = gtk_entry_get_text (_tmp1_);
		_tmp3_ = _tmp2_;
		_tmp4_ = self->pwd;
		_tmp5_ = gtk_entry_get_text (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = self->sex;
		_tmp8_ = self->birthyear;
		_tmp9_ = self->desc;
		_tmp10_ = gtk_entry_get_text (_tmp9_);
		_tmp11_ = _tmp10_;
		if (rpc_client_add_user (_tmp0_, _tmp3_, _tmp6_, _tmp7_, _tmp8_, _tmp11_) == FALSE) {
			GtkDialog* _tmp12_;
			_tmp12_ = self->dlg1;
			gtk_window_set_title ((GtkWindow*) _tmp12_, "注册发生错误！");
			return;
		}
		_tmp13_ = rpc1;
		_tmp14_ = self->name;
		_tmp15_ = gtk_entry_get_text (_tmp14_);
		_tmp16_ = _tmp15_;
		_tmp17_ = self->pwd;
		_tmp18_ = gtk_entry_get_text (_tmp17_);
		_tmp19_ = _tmp18_;
		_tmp21_ = rpc_client_login (_tmp13_, _tmp16_, _tmp19_, &_tmp20_);
		user_data_destroy (&u);
		u = _tmp20_;
		res = _tmp21_;
		_tmp22_ = res;
		if (_tmp22_ > ((gint64) 0)) {
			FILE* _tmp23_;
			MyGrid* _tmp24_;
			gint64 _tmp25_;
			MyGrid* _tmp26_;
			UserData _tmp27_;
			const gchar* _tmp28_;
			gchar* _tmp29_;
			MyGrid* _tmp30_;
			UserData _tmp31_;
			gint16 _tmp32_;
			MyGrid* _tmp33_;
			UserData _tmp34_;
			gint16 _tmp35_;
			MyGrid* _tmp36_;
			UserData _tmp37_;
			const gchar* _tmp38_;
			gchar* _tmp39_;
			MyGrid* _tmp40_;
			GtkButton* _tmp41_;
			UserData _tmp42_;
			const gchar* _tmp43_;
			_tmp23_ = stdout;
			fprintf (_tmp23_, "login ok\n");
			_tmp24_ = grid1;
			_tmp25_ = res;
			_tmp24_->uid = _tmp25_;
			_tmp26_ = grid1;
			_tmp27_ = u;
			_tmp28_ = _tmp27_.name;
			_tmp29_ = g_strdup (_tmp28_);
			_g_free0 (_tmp26_->uname);
			_tmp26_->uname = _tmp29_;
			_tmp30_ = grid1;
			_tmp31_ = u;
			_tmp32_ = _tmp31_.sex;
			_tmp30_->usex = _tmp32_;
			_tmp33_ = grid1;
			_tmp34_ = u;
			_tmp35_ = _tmp34_.age;
			_tmp33_->uage = _tmp35_;
			_tmp36_ = grid1;
			_tmp37_ = u;
			_tmp38_ = _tmp37_.desc;
			_tmp39_ = g_strdup (_tmp38_);
			_g_free0 (_tmp36_->udesc);
			_tmp36_->udesc = _tmp39_;
			_tmp40_ = grid1;
			_tmp41_ = _tmp40_->user_btn;
			_tmp42_ = u;
			_tmp43_ = _tmp42_.name;
			gtk_button_set_label (_tmp41_, _tmp43_);
		} else {
			GtkDialog* _tmp44_;
			FILE* _tmp45_;
			_tmp44_ = self->dlg1;
			gtk_window_set_title ((GtkWindow*) _tmp44_, "用户／密码错误。");
			_tmp45_ = stdout;
			fprintf (_tmp45_, "login fail\n");
			user_data_destroy (&u);
			return;
		}
		_tmp46_ = rpc1;
		if (rpc_client_get_friends_async (_tmp46_) == FALSE) {
			g_print ("RPC error");
			gtk_main_quit ();
		}
		_tmp47_ = self->dlg1;
		gtk_widget_hide ((GtkWidget*) _tmp47_);
		_tmp48_ = app;
		gtk_widget_show_all ((GtkWidget*) _tmp48_);
		user_data_destroy (&u);
	} else {
		gtk_main_quit ();
	}
}


static void
___lambda45__gtk_dialog_response (GtkDialog* _sender,
                                  gint response_id,
                                  gpointer self)
{
	__lambda45_ ((AddUserDialog*) self, response_id);
}


AddUserDialog*
add_user_dialog_construct (GType object_type)
{
	AddUserDialog * self = NULL;
	Block8Data* _data8_;
	AppWin* _tmp0_;
	GtkDialog* _tmp1_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp2_;
	GtkGrid* _tmp3_;
	GtkLabel* _tmp4_;
	GtkLabel* _tmp5_;
	GtkGrid* _tmp6_;
	GtkLabel* _tmp7_;
	GtkLabel* _tmp8_;
	GtkEntry* _tmp9_;
	GtkGrid* _tmp10_;
	GtkEntry* _tmp11_;
	GtkGrid* _tmp12_;
	GtkLabel* _tmp13_;
	GtkLabel* _tmp14_;
	GtkEntry* _tmp15_;
	GtkEntry* _tmp16_;
	GtkGrid* _tmp17_;
	GtkEntry* _tmp18_;
	GDateTime* date1 = NULL;
	GDateTime* _tmp19_;
	gint year1 = 0;
	GDateTime* _tmp20_;
	GtkComboBoxText* _tmp21_;
	GtkComboBoxText* _tmp30_;
	gint _tmp31_;
	GtkGrid* _tmp32_;
	GtkLabel* _tmp33_;
	GtkLabel* _tmp34_;
	GtkGrid* _tmp35_;
	GtkComboBoxText* _tmp36_;
	GtkComboBoxText* _tmp37_;
	GtkComboBoxText* _tmp38_;
	GtkGrid* _tmp39_;
	GtkLabel* _tmp40_;
	GtkLabel* _tmp41_;
	GtkGrid* _tmp42_;
	GtkGrid* _tmp43_;
	GtkLabel* _tmp44_;
	GtkLabel* _tmp45_;
	GtkEntry* _tmp46_;
	GtkGrid* _tmp47_;
	GtkEntry* _tmp48_;
	GtkBox* content = NULL;
	GtkDialog* _tmp49_;
	GtkBox* _tmp50_;
	GtkBox* _tmp51_;
	GtkGrid* _tmp52_;
	GtkDialog* _tmp53_;
	GtkDialog* _tmp54_;
	GtkDialog* _tmp55_;
	_data8_ = g_slice_new0 (Block8Data);
	_data8_->_ref_count_ = 1;
	self = (AddUserDialog*) g_object_new (object_type, NULL);
	_data8_->self = g_object_ref (self);
	_tmp0_ = app;
	_tmp1_ = (GtkDialog*) gtk_dialog_new_with_buttons ("注册", (GtkWindow*) _tmp0_, GTK_DIALOG_MODAL, NULL);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->dlg1);
	self->dlg1 = _tmp1_;
	_tmp2_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp2_);
	grid = _tmp2_;
	_tmp3_ = grid;
	_tmp4_ = (GtkLabel*) gtk_label_new ("输入注册信息");
	g_object_ref_sink (_tmp4_);
	_tmp5_ = _tmp4_;
	gtk_grid_attach (_tmp3_, (GtkWidget*) _tmp5_, 0, 0, 2, 1);
	_g_object_unref0 (_tmp5_);
	_tmp6_ = grid;
	_tmp7_ = (GtkLabel*) gtk_label_new ("名　　称：");
	g_object_ref_sink (_tmp7_);
	_tmp8_ = _tmp7_;
	gtk_grid_attach (_tmp6_, (GtkWidget*) _tmp8_, 0, 1, 1, 1);
	_g_object_unref0 (_tmp8_);
	_tmp9_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->name);
	self->name = _tmp9_;
	_tmp10_ = grid;
	_tmp11_ = self->name;
	gtk_grid_attach (_tmp10_, (GtkWidget*) _tmp11_, 1, 1, 1, 1);
	_tmp12_ = grid;
	_tmp13_ = (GtkLabel*) gtk_label_new ("密　　码：");
	g_object_ref_sink (_tmp13_);
	_tmp14_ = _tmp13_;
	gtk_grid_attach (_tmp12_, (GtkWidget*) _tmp14_, 0, 2, 1, 1);
	_g_object_unref0 (_tmp14_);
	_tmp15_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp15_);
	_g_object_unref0 (self->pwd);
	self->pwd = _tmp15_;
	_tmp16_ = self->pwd;
	gtk_entry_set_visibility (_tmp16_, FALSE);
	_tmp17_ = grid;
	_tmp18_ = self->pwd;
	gtk_grid_attach (_tmp17_, (GtkWidget*) _tmp18_, 1, 2, 1, 1);
	_tmp19_ = g_date_time_new_now_local ();
	date1 = _tmp19_;
	_tmp20_ = date1;
	year1 = g_date_time_get_year (_tmp20_);
	_tmp21_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp21_);
	_data8_->yearSelect = _tmp21_;
	{
		gint i = 0;
		i = 5;
		{
			gboolean _tmp22_ = FALSE;
			_tmp22_ = TRUE;
			while (TRUE) {
				gint _tmp24_;
				GtkComboBoxText* _tmp25_;
				gint _tmp26_;
				gint _tmp27_;
				gchar* _tmp28_;
				gchar* _tmp29_;
				if (!_tmp22_) {
					gint _tmp23_;
					_tmp23_ = i;
					i = _tmp23_ + 1;
				}
				_tmp22_ = FALSE;
				_tmp24_ = i;
				if (!(_tmp24_ < 100)) {
					break;
				}
				_tmp25_ = _data8_->yearSelect;
				_tmp26_ = year1;
				_tmp27_ = i;
				_tmp28_ = g_strdup_printf ("%i", _tmp26_ - _tmp27_);
				_tmp29_ = _tmp28_;
				gtk_combo_box_text_append_text (_tmp25_, _tmp29_);
				_g_free0 (_tmp29_);
			}
		}
	}
	_tmp30_ = _data8_->yearSelect;
	gtk_combo_box_set_active ((GtkComboBox*) _tmp30_, 10);
	_tmp31_ = year1;
	self->birthyear = _tmp31_ - 15;
	_tmp32_ = grid;
	_tmp33_ = (GtkLabel*) gtk_label_new ("出生年份：");
	g_object_ref_sink (_tmp33_);
	_tmp34_ = _tmp33_;
	gtk_grid_attach (_tmp32_, (GtkWidget*) _tmp34_, 0, 3, 1, 1);
	_g_object_unref0 (_tmp34_);
	_tmp35_ = grid;
	_tmp36_ = _data8_->yearSelect;
	gtk_grid_attach (_tmp35_, (GtkWidget*) _tmp36_, 1, 3, 1, 1);
	_tmp37_ = _data8_->yearSelect;
	g_signal_connect_data ((GtkComboBox*) _tmp37_, "changed", (GCallback) ___lambda43__gtk_combo_box_changed, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
	_tmp38_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp38_);
	_data8_->sexSelect = _tmp38_;
	gtk_combo_box_text_append_text (_data8_->sexSelect, "男性");
	gtk_combo_box_text_append_text (_data8_->sexSelect, "女性");
	gtk_combo_box_set_active ((GtkComboBox*) _data8_->sexSelect, 0);
	_tmp39_ = grid;
	_tmp40_ = (GtkLabel*) gtk_label_new ("性别：");
	g_object_ref_sink (_tmp40_);
	_tmp41_ = _tmp40_;
	gtk_grid_attach (_tmp39_, (GtkWidget*) _tmp41_, 0, 4, 1, 1);
	_g_object_unref0 (_tmp41_);
	_tmp42_ = grid;
	gtk_grid_attach (_tmp42_, (GtkWidget*) _data8_->sexSelect, 1, 4, 1, 1);
	g_signal_connect_data ((GtkComboBox*) _data8_->sexSelect, "changed", (GCallback) ___lambda44__gtk_combo_box_changed, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
	_tmp43_ = grid;
	_tmp44_ = (GtkLabel*) gtk_label_new ("自我描述：");
	g_object_ref_sink (_tmp44_);
	_tmp45_ = _tmp44_;
	gtk_grid_attach (_tmp43_, (GtkWidget*) _tmp45_, 0, 5, 1, 1);
	_g_object_unref0 (_tmp45_);
	_tmp46_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp46_);
	_g_object_unref0 (self->desc);
	self->desc = _tmp46_;
	_tmp47_ = grid;
	_tmp48_ = self->desc;
	gtk_grid_attach (_tmp47_, (GtkWidget*) _tmp48_, 1, 5, 1, 1);
	_tmp49_ = self->dlg1;
	_tmp50_ = gtk_dialog_get_content_area (_tmp49_);
	_tmp51_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp50_, gtk_box_get_type ()) ? ((GtkBox*) _tmp50_) : NULL);
	content = _tmp51_;
	_tmp52_ = grid;
	gtk_box_pack_start (content, (GtkWidget*) _tmp52_, TRUE, TRUE, (guint) 0);
	_tmp53_ = self->dlg1;
	gtk_dialog_add_button (_tmp53_, "注册", 2);
	_tmp54_ = self->dlg1;
	gtk_dialog_add_button (_tmp54_, "取消", 3);
	_tmp55_ = self->dlg1;
	g_signal_connect_object (_tmp55_, "response", (GCallback) ___lambda45__gtk_dialog_response, self, 0);
	_g_object_unref0 (content);
	_g_date_time_unref0 (date1);
	_g_object_unref0 (grid);
	block8_data_unref (_data8_);
	_data8_ = NULL;
	return self;
}


AddUserDialog*
add_user_dialog_new (void)
{
	return add_user_dialog_construct (TYPE_ADD_USER_DIALOG);
}


void
add_user_dialog_show (AddUserDialog* self)
{
	GtkDialog* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->dlg1;
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
}


static void
add_user_dialog_class_init (AddUserDialogClass * klass)
{
	add_user_dialog_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = add_user_dialog_finalize;
}


static void
add_user_dialog_instance_init (AddUserDialog * self)
{
	self->sex = 1;
}


static void
add_user_dialog_finalize (GObject * obj)
{
	AddUserDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ADD_USER_DIALOG, AddUserDialog);
	_g_object_unref0 (self->dlg1);
	_g_object_unref0 (self->name);
	_g_object_unref0 (self->pwd);
	_g_object_unref0 (self->desc);
	G_OBJECT_CLASS (add_user_dialog_parent_class)->finalize (obj);
}


GType
add_user_dialog_get_type (void)
{
	static volatile gsize add_user_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&add_user_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AddUserDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) add_user_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AddUserDialog), 0, (GInstanceInitFunc) add_user_dialog_instance_init, NULL };
		GType add_user_dialog_type_id;
		add_user_dialog_type_id = g_type_register_static (G_TYPE_OBJECT, "AddUserDialog", &g_define_type_info, 0);
		g_once_init_leave (&add_user_dialog_type_id__volatile, add_user_dialog_type_id);
	}
	return add_user_dialog_type_id__volatile;
}



