/* jsonrpc.c generated by valac 0.40.8, the Vala compiler
 * generated from jsonrpc.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <jsonrpc-glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>


#define TYPE_RPC_CLIENT (rpc_client_get_type ())
#define RPC_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RPC_CLIENT, RpcClient))
#define RPC_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RPC_CLIENT, RpcClientClass))
#define IS_RPC_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RPC_CLIENT))
#define IS_RPC_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RPC_CLIENT))
#define RPC_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RPC_CLIENT, RpcClientClass))

typedef struct _RpcClient RpcClient;
typedef struct _RpcClientClass RpcClientClass;
typedef struct _RpcClientPrivate RpcClientPrivate;
enum  {
	RPC_CLIENT_0_PROPERTY,
	RPC_CLIENT_COUNTER_PROPERTY,
	RPC_CLIENT_NUM_PROPERTIES
};
static GParamSpec* rpc_client_properties[RPC_CLIENT_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_USER_DATA (user_data_get_type ())
typedef struct _UserData UserData;
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block5Data Block5Data;
typedef struct _Block6Data Block6Data;

#define TYPE_MY_GRID (my_grid_get_type ())
#define MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_GRID, MyGrid))
#define MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_GRID, MyGridClass))
#define IS_MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_GRID))
#define IS_MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_GRID))
#define MY_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_GRID, MyGridClass))

typedef struct _MyGrid MyGrid;
typedef struct _MyGridClass MyGridClass;
typedef struct _MyGridPrivate MyGridPrivate;
typedef struct _Block7Data Block7Data;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _RpcClient {
	GObject parent_instance;
	RpcClientPrivate * priv;
	JsonrpcClient* c;
};

struct _RpcClientClass {
	GObjectClass parent_class;
};

struct _RpcClientPrivate {
	gint _counter;
};

struct _UserData {
	gint64 id;
	gint16 sex;
	gchar* name;
	gchar* desc;
	gint16 age;
	gchar* msg_offline;
	gchar* timestamp_offline;
};

typedef void (*SearchCallback) (UserData* user1, gpointer user_data);
struct _Block5Data {
	int _ref_count_;
	RpcClient* self;
	SearchCallback f;
	gpointer f_target;
};

typedef void (*RpcClientcallback_add_row) (UserData* u1, gpointer user_data);
struct _Block6Data {
	int _ref_count_;
	RpcClient* self;
	RpcClientcallback_add_row add_row;
	gpointer add_row_target;
};

struct _MyGrid {
	GObject parent_instance;
	MyGridPrivate * priv;
	GtkEntry* port1;
	GtkGrid* mygrid;
	GtkCssProvider* provider1;
	GtkCssProvider* mark1;
	GtkCssProvider* button1;
	GtkCssProvider* link_css1;
	GtkButton* strangers_btn;
	GtkButton* user_btn;
	gchar* man_icon;
	gchar* woman_icon;
	gint64 uid;
	gint16 usex;
	gchar* uname;
	gchar* udesc;
	gint16 uage;
};

struct _MyGridClass {
	GObjectClass parent_class;
};

typedef void (*RpcClientQueryCallback) (UserData* u, gpointer user_data);
struct _Block7Data {
	int _ref_count_;
	RpcClient* self;
	gchar* msg;
	RpcClientQueryCallback f;
	gpointer f_target;
};


static gpointer rpc_client_parent_class = NULL;
extern MyGrid* grid1;
extern guint16 server_port;
extern guint16 proxy_port;

GType rpc_client_get_type (void) G_GNUC_CONST;
#define RPC_CLIENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_RPC_CLIENT, RpcClientPrivate))
gboolean rpc_client_connect (RpcClient* self,
                             const gchar* host,
                             guint16 port);
static void _g_object_unref0_ (gpointer var);
static inline void _g_list_free__g_object_unref0_ (GList* self);
GType user_data_get_type (void) G_GNUC_CONST;
UserData* user_data_dup (const UserData* self);
void user_data_free (UserData* self);
void user_data_copy (const UserData* self,
                     UserData* dest);
void user_data_destroy (UserData* self);
gint64 rpc_client_login (RpcClient* self,
                         const gchar* name,
                         const gchar* pwd,
                         UserData* u);
gboolean rpc_client_add_friend (RpcClient* self,
                                gint64 uid);
static void ___lambda9_ (RpcClient* self,
                  GObject* s,
                  GAsyncResult* r);
static void ____lambda9__gasync_ready_callback (GObject* source_object,
                                         GAsyncResult* res,
                                         gpointer self);
gboolean rpc_client_search_person (RpcClient* self,
                                   const gchar* key,
                                   GList* * persons);
static void _user_data_free0_ (gpointer var);
static inline void _g_list_free__user_data_free0_ (GList* self);
gboolean rpc_client_search_person_async (RpcClient* self,
                                         const gchar* key,
                                         SearchCallback f,
                                         gpointer f_target);
static Block5Data* block5_data_ref (Block5Data* _data5_);
static void block5_data_unref (void * _userdata_);
static void ___lambda10_ (Block5Data* _data5_,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda10__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_move_stranger_to_friend (RpcClient* self,
                                             gint64 fid);
gboolean rpc_client_get_stranger_msgs_async (RpcClient* self,
                                             RpcClientcallback_add_row add_row,
                                             gpointer add_row_target);
static Block6Data* block6_data_ref (Block6Data* _data6_);
static void block6_data_unref (void * _userdata_);
static void ___lambda11_ (Block6Data* _data6_,
                   GObject* s,
                   GAsyncResult* r);
GType my_grid_get_type (void) G_GNUC_CONST;
static void ____lambda11__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_get_friends_async (RpcClient* self);
static void ___lambda12_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
void my_grid_add_friend (MyGrid* self,
                         UserData* user1);
static void ____lambda12__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_ChatTo (RpcClient* self,
                            gint64 to,
                            const gchar* msg);
static void ___lambda19_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda19__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_tell (RpcClient* self,
                          gint64 to);
static void ___lambda13_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda13__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_set_http_id (RpcClient* self,
                                 gint64 uid);
static void ___lambda15_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda15__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_send_file (RpcClient* self,
                               gint64 to,
                               const gchar* pathname);
static void ___lambda20_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
void my_grid_add_text (MyGrid* self,
                       const gchar* text,
                       gboolean center,
                       gboolean markup);
static void ____lambda20__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_add_user (RpcClient* self,
                              const gchar* name,
                              const gchar* pwd,
                              gint sex,
                              gint birthyear,
                              const gchar* desc);
gboolean rpc_client_quit (RpcClient* self);
static void ___lambda21_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda21__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_get_proxy (RpcClient* self,
                               guint16* port);
gboolean rpc_client_set_proxy (RpcClient* self,
                               guint16 port);
static void ___lambda22_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda22__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_remove_friend (RpcClient* self,
                                   gint64 fid);
static void ___lambda18_ (RpcClient* self,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda18__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
gboolean rpc_client_offline_msg_with_id (RpcClient* self,
                                         gint64 uid,
                                         const gchar* msg,
                                         RpcClientQueryCallback f,
                                         gpointer f_target);
static Block7Data* block7_data_ref (Block7Data* _data7_);
static void block7_data_unref (void * _userdata_);
static void ___lambda23_ (Block7Data* _data7_,
                   GObject* s,
                   GAsyncResult* r);
static void ____lambda23__gasync_ready_callback (GObject* source_object,
                                          GAsyncResult* res,
                                          gpointer self);
RpcClient* rpc_client_new (void);
RpcClient* rpc_client_construct (GType object_type);
gint rpc_client_get_counter (RpcClient* self);
void rpc_client_set_counter (RpcClient* self,
                             gint value);
static void rpc_client_finalize (GObject * obj);
static void _vala_rpc_client_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec);
static void _vala_rpc_client_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec);


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


static void
_g_object_unref0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
}


gboolean
rpc_client_connect (RpcClient* self,
                    const gchar* host,
                    guint16 port)
{
	gboolean result = FALSE;
	gboolean _tmp18_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (host != NULL, FALSE);
	{
		GResolver* resolver = NULL;
		GResolver* _tmp0_;
		GList* addresses = NULL;
		GResolver* _tmp1_;
		GList* _tmp2_;
		GInetAddress* address = NULL;
		GList* _tmp3_;
		gconstpointer _tmp4_;
		GInetAddress* _tmp5_;
		GSocketClient* client = NULL;
		GSocketClient* _tmp6_;
		GSocketConnection* conn = NULL;
		GSocketClient* _tmp7_;
		GInetAddress* _tmp8_;
		GInetSocketAddress* _tmp9_;
		GInetSocketAddress* _tmp10_;
		GSocketConnection* _tmp11_;
		GSocketConnection* _tmp12_;
		GSocketConnection* _tmp13_;
		JsonrpcClient* _tmp14_;
		_tmp0_ = g_resolver_get_default ();
		resolver = _tmp0_;
		_tmp1_ = resolver;
		_tmp2_ = g_resolver_lookup_by_name (_tmp1_, host, NULL, &_inner_error_);
		addresses = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (resolver);
			goto __catch1_g_error;
		}
		_tmp3_ = addresses;
		_tmp4_ = g_list_nth_data (_tmp3_, (guint) 0);
		_tmp5_ = _g_object_ref0 ((GInetAddress*) _tmp4_);
		address = _tmp5_;
		_tmp6_ = g_socket_client_new ();
		client = _tmp6_;
		_tmp7_ = client;
		_tmp8_ = address;
		_tmp9_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp8_, port);
		_tmp10_ = _tmp9_;
		_tmp11_ = g_socket_client_connect (_tmp7_, (GSocketConnectable*) _tmp10_, NULL, &_inner_error_);
		_tmp12_ = _tmp11_;
		_g_object_unref0 (_tmp10_);
		conn = _tmp12_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (client);
			_g_object_unref0 (address);
			(addresses == NULL) ? NULL : (addresses = (_g_list_free__g_object_unref0_ (addresses), NULL));
			_g_object_unref0 (resolver);
			goto __catch1_g_error;
		}
		_tmp13_ = conn;
		_tmp14_ = jsonrpc_client_new ((GIOStream*) _tmp13_);
		_g_object_unref0 (self->c);
		self->c = _tmp14_;
		result = TRUE;
		_g_object_unref0 (conn);
		_g_object_unref0 (client);
		_g_object_unref0 (address);
		(addresses == NULL) ? NULL : (addresses = (_g_list_free__g_object_unref0_ (addresses), NULL));
		_g_object_unref0 (resolver);
		return result;
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		FILE* _tmp15_;
		GError* _tmp16_;
		const gchar* _tmp17_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp15_ = stdout;
		_tmp16_ = e;
		_tmp17_ = _tmp16_->message;
		fprintf (_tmp15_, "Error: %s\n", _tmp17_);
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	__finally1:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp18_;
}


gint64
rpc_client_login (RpcClient* self,
                  const gchar* name,
                  const gchar* pwd,
                  UserData* u)
{
	UserData _vala_u = {0};
	gint64 result = 0LL;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	GVariant* res = NULL;
	gint64 _tmp43_ = -1LL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0LL);
	g_return_val_if_fail (name != NULL, 0LL);
	g_return_val_if_fail (pwd != NULL, 0LL);
	_tmp0_ = g_variant_new_parsed ("{'Name':<%s>,'Pwd':<%s>}", name, pwd, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		gboolean ok = FALSE;
		JsonrpcClient* _tmp1_;
		GVariant* _tmp2_;
		GVariant* _tmp3_ = NULL;
		gboolean _tmp4_;
		gboolean _tmp5_;
		gint64 id = 0LL;
		GVariant* _tmp6_;
		GVariant* _tmp7_;
		GVariant* _tmp8_;
		gint64 _tmp9_;
		gint64 sex = 0LL;
		GVariant* _tmp10_;
		GVariant* _tmp11_;
		GVariant* _tmp12_;
		gint64 _tmp13_;
		gchar* uname = NULL;
		GVariant* _tmp14_;
		GVariant* _tmp15_;
		GVariant* _tmp16_;
		const gchar* _tmp17_;
		gchar* _tmp18_;
		gchar* _tmp19_;
		gchar* desc = NULL;
		GVariant* _tmp20_;
		GVariant* _tmp21_;
		GVariant* _tmp22_;
		const gchar* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		gint64 age = 0LL;
		GVariant* _tmp26_;
		GVariant* _tmp27_;
		GVariant* _tmp28_;
		gint64 _tmp29_;
		gint64 _tmp30_;
		gint64 _tmp31_;
		const gchar* _tmp32_;
		gchar* _tmp33_;
		const gchar* _tmp34_;
		gchar* _tmp35_;
		gint64 _tmp36_;
		gchar* _tmp37_;
		gchar* _tmp38_;
		UserData _tmp39_ = {0};
		_tmp1_ = self->c;
		_tmp2_ = params;
		_tmp4_ = jsonrpc_client_call (_tmp1_, "PClient.Login", _tmp2_, NULL, &_tmp3_, &_inner_error_);
		_g_variant_unref0 (res);
		res = _tmp3_;
		ok = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch2_g_error;
		}
		_tmp5_ = ok;
		if (_tmp5_ == FALSE) {
			result = (gint64) -1;
			_g_variant_unref0 (res);
			_g_variant_unref0 (params);
			if (u) {
				*u = _vala_u;
			} else {
				user_data_destroy (&_vala_u);
			}
			return result;
		}
		_tmp6_ = res;
		_tmp7_ = g_variant_lookup_value (_tmp6_, "Id", NULL);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_variant_get_int64 (_tmp8_);
		_g_variant_unref0 (_tmp8_);
		id = _tmp9_;
		_tmp10_ = res;
		_tmp11_ = g_variant_lookup_value (_tmp10_, "Sex", NULL);
		_tmp12_ = _tmp11_;
		_tmp13_ = g_variant_get_int64 (_tmp12_);
		_g_variant_unref0 (_tmp12_);
		sex = _tmp13_;
		_tmp14_ = res;
		_tmp15_ = g_variant_lookup_value (_tmp14_, "Name", NULL);
		_tmp16_ = _tmp15_;
		_tmp17_ = g_variant_get_string (_tmp16_, NULL);
		_tmp18_ = g_strdup (_tmp17_);
		_tmp19_ = _tmp18_;
		_g_variant_unref0 (_tmp16_);
		uname = _tmp19_;
		_tmp20_ = res;
		_tmp21_ = g_variant_lookup_value (_tmp20_, "Desc", NULL);
		_tmp22_ = _tmp21_;
		_tmp23_ = g_variant_get_string (_tmp22_, NULL);
		_tmp24_ = g_strdup (_tmp23_);
		_tmp25_ = _tmp24_;
		_g_variant_unref0 (_tmp22_);
		desc = _tmp25_;
		_tmp26_ = res;
		_tmp27_ = g_variant_lookup_value (_tmp26_, "Age", NULL);
		_tmp28_ = _tmp27_;
		_tmp29_ = g_variant_get_int64 (_tmp28_);
		_g_variant_unref0 (_tmp28_);
		age = _tmp29_;
		_tmp30_ = id;
		_tmp31_ = sex;
		_tmp32_ = uname;
		_tmp33_ = g_strdup (_tmp32_);
		_tmp34_ = desc;
		_tmp35_ = g_strdup (_tmp34_);
		_tmp36_ = age;
		_tmp37_ = g_strdup ("");
		_tmp38_ = g_strdup ("");
		_tmp39_.id = _tmp30_;
		_tmp39_.sex = (gint16) _tmp31_;
		_g_free0 (_tmp39_.name);
		_tmp39_.name = _tmp33_;
		_g_free0 (_tmp39_.desc);
		_tmp39_.desc = _tmp35_;
		_tmp39_.age = (gint16) _tmp36_;
		_g_free0 (_tmp39_.msg_offline);
		_tmp39_.msg_offline = _tmp37_;
		_g_free0 (_tmp39_.timestamp_offline);
		_tmp39_.timestamp_offline = _tmp38_;
		user_data_destroy (&_vala_u);
		_vala_u = _tmp39_;
		result = id;
		_g_free0 (desc);
		_g_free0 (uname);
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		if (u) {
			*u = _vala_u;
		} else {
			user_data_destroy (&_vala_u);
		}
		return result;
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		FILE* _tmp40_;
		GError* _tmp41_;
		const gchar* _tmp42_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp40_ = stdout;
		_tmp41_ = e;
		_tmp42_ = _tmp41_->message;
		fprintf (_tmp40_, "Error: %s\n", _tmp42_);
		result = (gint64) -1;
		_g_error_free0 (e);
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		if (u) {
			*u = _vala_u;
		} else {
			user_data_destroy (&_vala_u);
		}
		return result;
	}
	__finally2:
	_g_variant_unref0 (res);
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp43_;
}


static void
___lambda9_ (RpcClient* self,
             GObject* s,
             GAsyncResult* r)
{
	JsonrpcClient* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void
____lambda9__gasync_ready_callback (GObject* source_object,
                                    GAsyncResult* res,
                                    gpointer self)
{
	___lambda9_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_add_friend (RpcClient* self,
                       gint64 uid)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new ("(i)", uid, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.AddFriend", params, NULL, ____lambda9__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally3:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


static void
_user_data_free0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (user_data_free (var), NULL));
}


static inline void
_g_list_free__user_data_free0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _user_data_free0_);
}


static gpointer
_user_data_dup0 (gpointer self)
{
	return self ? user_data_dup (self) : NULL;
}


gboolean
rpc_client_search_person (RpcClient* self,
                          const gchar* key,
                          GList* * persons)
{
	GList* _vala_persons = NULL;
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	GVariant* res = NULL;
	gboolean _tmp56_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (key != NULL, FALSE);
	_tmp0_ = g_variant_new ("(s)", key, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		gboolean ok = FALSE;
		JsonrpcClient* _tmp1_;
		GVariant* _tmp2_;
		GVariant* _tmp3_ = NULL;
		gboolean _tmp4_;
		gboolean _tmp5_;
		GVariant* val = NULL;
		gsize size1 = 0UL;
		GVariant* _tmp6_;
		_tmp1_ = self->c;
		_tmp2_ = params;
		_tmp4_ = jsonrpc_client_call (_tmp1_, "PClient.SearchPersons", _tmp2_, NULL, &_tmp3_, &_inner_error_);
		_g_variant_unref0 (res);
		res = _tmp3_;
		ok = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch4_g_error;
		}
		_tmp5_ = ok;
		if (_tmp5_ == FALSE) {
			result = FALSE;
			_g_variant_unref0 (res);
			_g_variant_unref0 (params);
			if (persons) {
				*persons = _vala_persons;
			} else {
				(_vala_persons == NULL) ? NULL : (_vala_persons = (_g_list_free__user_data_free0_ (_vala_persons), NULL));
			}
			return result;
		}
		(_vala_persons == NULL) ? NULL : (_vala_persons = (_g_list_free__user_data_free0_ (_vala_persons), NULL));
		_vala_persons = NULL;
		_tmp6_ = res;
		size1 = g_variant_n_children (_tmp6_);
		{
			gsize i = 0UL;
			i = (gsize) 0;
			{
				gboolean _tmp7_ = FALSE;
				_tmp7_ = TRUE;
				while (TRUE) {
					gsize _tmp9_;
					gsize _tmp10_;
					GVariant* _tmp11_;
					gsize _tmp12_;
					GVariant* _tmp13_;
					GVariant* _tmp14_;
					GVariant* _tmp15_;
					gint64 id = 0LL;
					GVariant* _tmp16_;
					GVariant* _tmp17_;
					GVariant* _tmp18_;
					gint64 _tmp19_;
					gint64 sex = 0LL;
					GVariant* _tmp20_;
					GVariant* _tmp21_;
					GVariant* _tmp22_;
					gint64 _tmp23_;
					gchar* name = NULL;
					GVariant* _tmp24_;
					GVariant* _tmp25_;
					GVariant* _tmp26_;
					const gchar* _tmp27_;
					gchar* _tmp28_;
					gchar* _tmp29_;
					gchar* desc = NULL;
					GVariant* _tmp30_;
					GVariant* _tmp31_;
					GVariant* _tmp32_;
					const gchar* _tmp33_;
					gchar* _tmp34_;
					gchar* _tmp35_;
					gint64 age = 0LL;
					GVariant* _tmp36_;
					GVariant* _tmp37_;
					GVariant* _tmp38_;
					gint64 _tmp39_;
					UserData u1 = {0};
					gint64 _tmp40_;
					gint64 _tmp41_;
					const gchar* _tmp42_;
					gchar* _tmp43_;
					const gchar* _tmp44_;
					gchar* _tmp45_;
					gint64 _tmp46_;
					gchar* _tmp47_;
					gchar* _tmp48_;
					UserData _tmp49_ = {0};
					UserData _tmp50_;
					UserData _tmp51_;
					UserData* _tmp52_;
					if (!_tmp7_) {
						gsize _tmp8_;
						_tmp8_ = i;
						i = _tmp8_ + 1;
					}
					_tmp7_ = FALSE;
					_tmp9_ = i;
					_tmp10_ = size1;
					if (!(_tmp9_ < _tmp10_)) {
						break;
					}
					_tmp11_ = res;
					_tmp12_ = i;
					_tmp13_ = g_variant_get_child_value (_tmp11_, _tmp12_);
					_tmp14_ = _tmp13_;
					_tmp15_ = g_variant_get_child_value (_tmp14_, (gsize) 0);
					_g_variant_unref0 (val);
					val = _tmp15_;
					_g_variant_unref0 (_tmp14_);
					_tmp16_ = val;
					_tmp17_ = g_variant_lookup_value (_tmp16_, "Id", NULL);
					_tmp18_ = _tmp17_;
					_tmp19_ = g_variant_get_int64 (_tmp18_);
					_g_variant_unref0 (_tmp18_);
					id = _tmp19_;
					_tmp20_ = val;
					_tmp21_ = g_variant_lookup_value (_tmp20_, "Sex", NULL);
					_tmp22_ = _tmp21_;
					_tmp23_ = g_variant_get_int64 (_tmp22_);
					_g_variant_unref0 (_tmp22_);
					sex = _tmp23_;
					_tmp24_ = val;
					_tmp25_ = g_variant_lookup_value (_tmp24_, "Name", NULL);
					_tmp26_ = _tmp25_;
					_tmp27_ = g_variant_get_string (_tmp26_, NULL);
					_tmp28_ = g_strdup (_tmp27_);
					_tmp29_ = _tmp28_;
					_g_variant_unref0 (_tmp26_);
					name = _tmp29_;
					_tmp30_ = val;
					_tmp31_ = g_variant_lookup_value (_tmp30_, "Desc", NULL);
					_tmp32_ = _tmp31_;
					_tmp33_ = g_variant_get_string (_tmp32_, NULL);
					_tmp34_ = g_strdup (_tmp33_);
					_tmp35_ = _tmp34_;
					_g_variant_unref0 (_tmp32_);
					desc = _tmp35_;
					_tmp36_ = val;
					_tmp37_ = g_variant_lookup_value (_tmp36_, "Age", NULL);
					_tmp38_ = _tmp37_;
					_tmp39_ = g_variant_get_int64 (_tmp38_);
					_g_variant_unref0 (_tmp38_);
					age = _tmp39_;
					_tmp40_ = id;
					_tmp41_ = sex;
					_tmp42_ = name;
					_tmp43_ = g_strdup (_tmp42_);
					_tmp44_ = desc;
					_tmp45_ = g_strdup (_tmp44_);
					_tmp46_ = age;
					_tmp47_ = g_strdup ("");
					_tmp48_ = g_strdup ("");
					_tmp49_.id = _tmp40_;
					_tmp49_.sex = (gint16) _tmp41_;
					_g_free0 (_tmp49_.name);
					_tmp49_.name = _tmp43_;
					_g_free0 (_tmp49_.desc);
					_tmp49_.desc = _tmp45_;
					_tmp49_.age = (gint16) _tmp46_;
					_g_free0 (_tmp49_.msg_offline);
					_tmp49_.msg_offline = _tmp47_;
					_g_free0 (_tmp49_.timestamp_offline);
					_tmp49_.timestamp_offline = _tmp48_;
					u1 = _tmp49_;
					_tmp50_ = u1;
					_tmp51_ = _tmp50_;
					_tmp52_ = _user_data_dup0 (&_tmp51_);
					_vala_persons = g_list_append (_vala_persons, _tmp52_);
					user_data_destroy (&u1);
					_g_free0 (desc);
					_g_free0 (name);
				}
			}
		}
		result = TRUE;
		_g_variant_unref0 (val);
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		if (persons) {
			*persons = _vala_persons;
		} else {
			(_vala_persons == NULL) ? NULL : (_vala_persons = (_g_list_free__user_data_free0_ (_vala_persons), NULL));
		}
		return result;
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
		FILE* _tmp53_;
		GError* _tmp54_;
		const gchar* _tmp55_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp53_ = stdout;
		_tmp54_ = e;
		_tmp55_ = _tmp54_->message;
		fprintf (_tmp53_, "Error: %s\n", _tmp55_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		if (persons) {
			*persons = _vala_persons;
		} else {
			(_vala_persons == NULL) ? NULL : (_vala_persons = (_g_list_free__user_data_free0_ (_vala_persons), NULL));
		}
		return result;
	}
	__finally4:
	_g_variant_unref0 (res);
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp56_;
}


static Block5Data*
block5_data_ref (Block5Data* _data5_)
{
	g_atomic_int_inc (&_data5_->_ref_count_);
	return _data5_;
}


static void
block5_data_unref (void * _userdata_)
{
	Block5Data* _data5_;
	_data5_ = (Block5Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data5_->_ref_count_)) {
		RpcClient* self;
		self = _data5_->self;
		_g_object_unref0 (self);
		g_slice_free (Block5Data, _data5_);
	}
}


static void
___lambda10_ (Block5Data* _data5_,
              GObject* s,
              GAsyncResult* r)
{
	RpcClient* self;
	GVariant* res = NULL;
	JsonrpcClient* _tmp0_;
	GVariant* _tmp1_ = NULL;
	GVariant* val = NULL;
	gsize size1 = 0UL;
	GError * _inner_error_ = NULL;
	self = _data5_->self;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, &_tmp1_, &_inner_error_);
	_g_variant_unref0 (res);
	res = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_variant_unref0 (res);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	size1 = g_variant_n_children (res);
	{
		gsize i = 0UL;
		i = (gsize) 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gsize _tmp4_;
				gsize _tmp5_;
				gsize _tmp6_;
				GVariant* _tmp7_;
				GVariant* _tmp8_;
				GVariant* _tmp9_;
				gint64 id = 0LL;
				GVariant* _tmp10_;
				GVariant* _tmp11_;
				GVariant* _tmp12_;
				gint64 _tmp13_;
				gint64 sex = 0LL;
				GVariant* _tmp14_;
				GVariant* _tmp15_;
				GVariant* _tmp16_;
				gint64 _tmp17_;
				gchar* name = NULL;
				GVariant* _tmp18_;
				GVariant* _tmp19_;
				GVariant* _tmp20_;
				const gchar* _tmp21_;
				gchar* _tmp22_;
				gchar* _tmp23_;
				gchar* desc = NULL;
				GVariant* _tmp24_;
				GVariant* _tmp25_;
				GVariant* _tmp26_;
				const gchar* _tmp27_;
				gchar* _tmp28_;
				gchar* _tmp29_;
				gint64 age = 0LL;
				GVariant* _tmp30_;
				GVariant* _tmp31_;
				GVariant* _tmp32_;
				gint64 _tmp33_;
				UserData u1 = {0};
				gint64 _tmp34_;
				gint64 _tmp35_;
				const gchar* _tmp36_;
				gchar* _tmp37_;
				const gchar* _tmp38_;
				gchar* _tmp39_;
				gint64 _tmp40_;
				gchar* _tmp41_;
				gchar* _tmp42_;
				UserData _tmp43_ = {0};
				UserData _tmp44_;
				if (!_tmp2_) {
					gsize _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = size1;
				if (!(_tmp4_ < _tmp5_)) {
					break;
				}
				_tmp6_ = i;
				_tmp7_ = g_variant_get_child_value (res, _tmp6_);
				_tmp8_ = _tmp7_;
				_tmp9_ = g_variant_get_child_value (_tmp8_, (gsize) 0);
				_g_variant_unref0 (val);
				val = _tmp9_;
				_g_variant_unref0 (_tmp8_);
				_tmp10_ = val;
				_tmp11_ = g_variant_lookup_value (_tmp10_, "Id", NULL);
				_tmp12_ = _tmp11_;
				_tmp13_ = g_variant_get_int64 (_tmp12_);
				_g_variant_unref0 (_tmp12_);
				id = _tmp13_;
				_tmp14_ = val;
				_tmp15_ = g_variant_lookup_value (_tmp14_, "Sex", NULL);
				_tmp16_ = _tmp15_;
				_tmp17_ = g_variant_get_int64 (_tmp16_);
				_g_variant_unref0 (_tmp16_);
				sex = _tmp17_;
				_tmp18_ = val;
				_tmp19_ = g_variant_lookup_value (_tmp18_, "Name", NULL);
				_tmp20_ = _tmp19_;
				_tmp21_ = g_variant_get_string (_tmp20_, NULL);
				_tmp22_ = g_strdup (_tmp21_);
				_tmp23_ = _tmp22_;
				_g_variant_unref0 (_tmp20_);
				name = _tmp23_;
				_tmp24_ = val;
				_tmp25_ = g_variant_lookup_value (_tmp24_, "Desc", NULL);
				_tmp26_ = _tmp25_;
				_tmp27_ = g_variant_get_string (_tmp26_, NULL);
				_tmp28_ = g_strdup (_tmp27_);
				_tmp29_ = _tmp28_;
				_g_variant_unref0 (_tmp26_);
				desc = _tmp29_;
				_tmp30_ = val;
				_tmp31_ = g_variant_lookup_value (_tmp30_, "Age", NULL);
				_tmp32_ = _tmp31_;
				_tmp33_ = g_variant_get_int64 (_tmp32_);
				_g_variant_unref0 (_tmp32_);
				age = _tmp33_;
				_tmp34_ = id;
				_tmp35_ = sex;
				_tmp36_ = name;
				_tmp37_ = g_strdup (_tmp36_);
				_tmp38_ = desc;
				_tmp39_ = g_strdup (_tmp38_);
				_tmp40_ = age;
				_tmp41_ = g_strdup ("");
				_tmp42_ = g_strdup ("");
				_tmp43_.id = _tmp34_;
				_tmp43_.sex = (gint16) _tmp35_;
				_g_free0 (_tmp43_.name);
				_tmp43_.name = _tmp37_;
				_g_free0 (_tmp43_.desc);
				_tmp43_.desc = _tmp39_;
				_tmp43_.age = (gint16) _tmp40_;
				_g_free0 (_tmp43_.msg_offline);
				_tmp43_.msg_offline = _tmp41_;
				_g_free0 (_tmp43_.timestamp_offline);
				_tmp43_.timestamp_offline = _tmp42_;
				u1 = _tmp43_;
				_tmp44_ = u1;
				_data5_->f (&_tmp44_, _data5_->f_target);
				user_data_destroy (&u1);
				_g_free0 (desc);
				_g_free0 (name);
			}
		}
	}
	_g_variant_unref0 (val);
	_g_variant_unref0 (res);
}


static void
____lambda10__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda10_ (self, source_object, res);
	block5_data_unref (self);
}


gboolean
rpc_client_search_person_async (RpcClient* self,
                                const gchar* key,
                                SearchCallback f,
                                gpointer f_target)
{
	gboolean result = FALSE;
	Block5Data* _data5_;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (key != NULL, FALSE);
	_data5_ = g_slice_new0 (Block5Data);
	_data5_->_ref_count_ = 1;
	_data5_->self = g_object_ref (self);
	_data5_->f = f;
	_data5_->f_target = f_target;
	_tmp0_ = g_variant_new ("(s)", key, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.SearchPersons", params, NULL, ____lambda10__gasync_ready_callback, block5_data_ref (_data5_));
		result = TRUE;
		_g_variant_unref0 (params);
		block5_data_unref (_data5_);
		_data5_ = NULL;
		return result;
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		block5_data_unref (_data5_);
		_data5_ = NULL;
		return result;
	}
	__finally5:
	_g_variant_unref0 (params);
	block5_data_unref (_data5_);
	_data5_ = NULL;
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


gboolean
rpc_client_move_stranger_to_friend (RpcClient* self,
                                    gint64 fid)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	GVariant* res = NULL;
	gboolean _tmp7_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new ("(i)", fid, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		gboolean ok = FALSE;
		JsonrpcClient* _tmp1_;
		GVariant* _tmp2_ = NULL;
		gboolean _tmp3_;
		_tmp1_ = self->c;
		_tmp3_ = jsonrpc_client_call (_tmp1_, "PClient.MoveStrangerToFriend", params, NULL, &_tmp2_, &_inner_error_);
		_g_variant_unref0 (res);
		res = _tmp2_;
		ok = _tmp3_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch6_g_error;
		}
		result = ok;
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		FILE* _tmp4_;
		GError* _tmp5_;
		const gchar* _tmp6_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stdout;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "Error: %s\n", _tmp6_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		return result;
	}
	__finally6:
	_g_variant_unref0 (res);
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp7_;
}


static Block6Data*
block6_data_ref (Block6Data* _data6_)
{
	g_atomic_int_inc (&_data6_->_ref_count_);
	return _data6_;
}


static void
block6_data_unref (void * _userdata_)
{
	Block6Data* _data6_;
	_data6_ = (Block6Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data6_->_ref_count_)) {
		RpcClient* self;
		self = _data6_->self;
		_g_object_unref0 (self);
		g_slice_free (Block6Data, _data6_);
	}
}


static void
___lambda11_ (Block6Data* _data6_,
              GObject* s,
              GAsyncResult* r)
{
	RpcClient* self;
	GVariant* val = NULL;
	GVariant* res = NULL;
	JsonrpcClient* _tmp0_;
	GVariant* _tmp1_ = NULL;
	gsize size1 = 0UL;
	gsize _tmp61_;
	GError * _inner_error_ = NULL;
	self = _data6_->self;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, &_tmp1_, &_inner_error_);
	_g_variant_unref0 (res);
	res = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_variant_unref0 (res);
		_g_variant_unref0 (val);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	size1 = g_variant_n_children (res);
	{
		gsize i = 0UL;
		i = (gsize) 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gsize _tmp4_;
				gsize _tmp5_;
				gsize _tmp6_;
				GVariant* _tmp7_;
				GVariant* _tmp8_;
				GVariant* _tmp9_;
				gint64 id = 0LL;
				GVariant* _tmp10_;
				GVariant* _tmp11_;
				GVariant* _tmp12_;
				gint64 _tmp13_;
				gint64 sex = 0LL;
				GVariant* _tmp14_;
				GVariant* _tmp15_;
				GVariant* _tmp16_;
				gint64 _tmp17_;
				gchar* name = NULL;
				GVariant* _tmp18_;
				GVariant* _tmp19_;
				GVariant* _tmp20_;
				const gchar* _tmp21_;
				gchar* _tmp22_;
				gchar* _tmp23_;
				gchar* desc = NULL;
				GVariant* _tmp24_;
				GVariant* _tmp25_;
				GVariant* _tmp26_;
				const gchar* _tmp27_;
				gchar* _tmp28_;
				gchar* _tmp29_;
				gint64 age = 0LL;
				GVariant* _tmp30_;
				GVariant* _tmp31_;
				GVariant* _tmp32_;
				gint64 _tmp33_;
				GVariant* obj_offline = NULL;
				GVariant* _tmp34_;
				GVariant* _tmp35_;
				gchar* msg_offline = NULL;
				GVariant* _tmp36_;
				GVariant* _tmp37_;
				GVariant* _tmp38_;
				const gchar* _tmp39_;
				gchar* _tmp40_;
				gchar* _tmp41_;
				gchar* timestamp_offline = NULL;
				GVariant* _tmp42_;
				GVariant* _tmp43_;
				GVariant* _tmp44_;
				const gchar* _tmp45_;
				gchar* _tmp46_;
				gchar* _tmp47_;
				UserData u1 = {0};
				gint64 _tmp48_;
				gint64 _tmp49_;
				const gchar* _tmp50_;
				gchar* _tmp51_;
				const gchar* _tmp52_;
				gchar* _tmp53_;
				gint64 _tmp54_;
				const gchar* _tmp55_;
				gchar* _tmp56_;
				const gchar* _tmp57_;
				gchar* _tmp58_;
				UserData _tmp59_ = {0};
				UserData _tmp60_;
				if (!_tmp2_) {
					gsize _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = size1;
				if (!(_tmp4_ < _tmp5_)) {
					break;
				}
				_tmp6_ = i;
				_tmp7_ = g_variant_get_child_value (res, _tmp6_);
				_tmp8_ = _tmp7_;
				_tmp9_ = g_variant_get_child_value (_tmp8_, (gsize) 0);
				_g_variant_unref0 (val);
				val = _tmp9_;
				_g_variant_unref0 (_tmp8_);
				_tmp10_ = val;
				_tmp11_ = g_variant_lookup_value (_tmp10_, "Id", NULL);
				_tmp12_ = _tmp11_;
				_tmp13_ = g_variant_get_int64 (_tmp12_);
				_g_variant_unref0 (_tmp12_);
				id = _tmp13_;
				_tmp14_ = val;
				_tmp15_ = g_variant_lookup_value (_tmp14_, "Sex", NULL);
				_tmp16_ = _tmp15_;
				_tmp17_ = g_variant_get_int64 (_tmp16_);
				_g_variant_unref0 (_tmp16_);
				sex = _tmp17_;
				_tmp18_ = val;
				_tmp19_ = g_variant_lookup_value (_tmp18_, "Name", NULL);
				_tmp20_ = _tmp19_;
				_tmp21_ = g_variant_get_string (_tmp20_, NULL);
				_tmp22_ = g_strdup (_tmp21_);
				_tmp23_ = _tmp22_;
				_g_variant_unref0 (_tmp20_);
				name = _tmp23_;
				_tmp24_ = val;
				_tmp25_ = g_variant_lookup_value (_tmp24_, "Desc", NULL);
				_tmp26_ = _tmp25_;
				_tmp27_ = g_variant_get_string (_tmp26_, NULL);
				_tmp28_ = g_strdup (_tmp27_);
				_tmp29_ = _tmp28_;
				_g_variant_unref0 (_tmp26_);
				desc = _tmp29_;
				_tmp30_ = val;
				_tmp31_ = g_variant_lookup_value (_tmp30_, "Age", NULL);
				_tmp32_ = _tmp31_;
				_tmp33_ = g_variant_get_int64 (_tmp32_);
				_g_variant_unref0 (_tmp32_);
				age = _tmp33_;
				_tmp34_ = val;
				_tmp35_ = g_variant_lookup_value (_tmp34_, "MsgOffline", NULL);
				obj_offline = _tmp35_;
				_tmp36_ = obj_offline;
				_tmp37_ = g_variant_lookup_value (_tmp36_, "Msg", NULL);
				_tmp38_ = _tmp37_;
				_tmp39_ = g_variant_get_string (_tmp38_, NULL);
				_tmp40_ = g_strdup (_tmp39_);
				_tmp41_ = _tmp40_;
				_g_variant_unref0 (_tmp38_);
				msg_offline = _tmp41_;
				_tmp42_ = obj_offline;
				_tmp43_ = g_variant_lookup_value (_tmp42_, "Timestamp", NULL);
				_tmp44_ = _tmp43_;
				_tmp45_ = g_variant_get_string (_tmp44_, NULL);
				_tmp46_ = g_strdup (_tmp45_);
				_tmp47_ = _tmp46_;
				_g_variant_unref0 (_tmp44_);
				timestamp_offline = _tmp47_;
				_tmp48_ = id;
				_tmp49_ = sex;
				_tmp50_ = name;
				_tmp51_ = g_strdup (_tmp50_);
				_tmp52_ = desc;
				_tmp53_ = g_strdup (_tmp52_);
				_tmp54_ = age;
				_tmp55_ = msg_offline;
				_tmp56_ = g_strdup (_tmp55_);
				_tmp57_ = timestamp_offline;
				_tmp58_ = g_strdup (_tmp57_);
				_tmp59_.id = _tmp48_;
				_tmp59_.sex = (gint16) _tmp49_;
				_g_free0 (_tmp59_.name);
				_tmp59_.name = _tmp51_;
				_g_free0 (_tmp59_.desc);
				_tmp59_.desc = _tmp53_;
				_tmp59_.age = (gint16) _tmp54_;
				_g_free0 (_tmp59_.msg_offline);
				_tmp59_.msg_offline = _tmp56_;
				_g_free0 (_tmp59_.timestamp_offline);
				_tmp59_.timestamp_offline = _tmp58_;
				u1 = _tmp59_;
				_tmp60_ = u1;
				_data6_->add_row (&_tmp60_, _data6_->add_row_target);
				user_data_destroy (&u1);
				_g_free0 (timestamp_offline);
				_g_free0 (msg_offline);
				_g_variant_unref0 (obj_offline);
				_g_free0 (desc);
				_g_free0 (name);
			}
		}
	}
	_tmp61_ = size1;
	if (_tmp61_ > ((gsize) 0)) {
		GtkStyleContext* sc1 = NULL;
		MyGrid* _tmp62_;
		GtkButton* _tmp63_;
		GtkStyleContext* _tmp64_;
		GtkStyleContext* _tmp65_;
		GtkStyleContext* _tmp66_;
		MyGrid* _tmp67_;
		GtkCssProvider* _tmp68_;
		GtkStyleContext* _tmp69_;
		_tmp62_ = grid1;
		_tmp63_ = _tmp62_->strangers_btn;
		_tmp64_ = gtk_widget_get_style_context ((GtkWidget*) _tmp63_);
		_tmp65_ = _g_object_ref0 (_tmp64_);
		sc1 = _tmp65_;
		_tmp66_ = sc1;
		_tmp67_ = grid1;
		_tmp68_ = _tmp67_->button1;
		gtk_style_context_add_provider (_tmp66_, (GtkStyleProvider*) _tmp68_, (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
		_tmp69_ = sc1;
		gtk_style_context_add_class (_tmp69_, "off");
		_g_object_unref0 (sc1);
	}
	_g_variant_unref0 (res);
	_g_variant_unref0 (val);
}


static void
____lambda11__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda11_ (self, source_object, res);
	block6_data_unref (self);
}


gboolean
rpc_client_get_stranger_msgs_async (RpcClient* self,
                                    RpcClientcallback_add_row add_row,
                                    gpointer add_row_target)
{
	gboolean result = FALSE;
	Block6Data* _data6_;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_data6_ = g_slice_new0 (Block6Data);
	_data6_->_ref_count_ = 1;
	_data6_->self = g_object_ref (self);
	_data6_->add_row = add_row;
	_data6_->add_row_target = add_row_target;
	_tmp0_ = g_variant_new_bytestring ("");
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.GetStrangerMsgs", params, NULL, ____lambda11__gasync_ready_callback, block6_data_ref (_data6_));
		result = TRUE;
		_g_variant_unref0 (params);
		block6_data_unref (_data6_);
		_data6_ = NULL;
		return result;
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		block6_data_unref (_data6_);
		_data6_ = NULL;
		return result;
	}
	__finally7:
	_g_variant_unref0 (params);
	block6_data_unref (_data6_);
	_data6_ = NULL;
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


static void
___lambda12_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	GVariant* res = NULL;
	JsonrpcClient* _tmp0_;
	GVariant* _tmp1_ = NULL;
	GVariant* val = NULL;
	gsize size1 = 0UL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, &_tmp1_, &_inner_error_);
	_g_variant_unref0 (res);
	res = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_variant_unref0 (res);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	size1 = g_variant_n_children (res);
	{
		gsize i = 0UL;
		i = (gsize) 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gsize _tmp4_;
				gsize _tmp5_;
				gsize _tmp6_;
				GVariant* _tmp7_;
				GVariant* _tmp8_;
				GVariant* _tmp9_;
				gint64 id = 0LL;
				GVariant* _tmp10_;
				GVariant* _tmp11_;
				GVariant* _tmp12_;
				gint64 _tmp13_;
				gint64 sex = 0LL;
				GVariant* _tmp14_;
				GVariant* _tmp15_;
				GVariant* _tmp16_;
				gint64 _tmp17_;
				gchar* name = NULL;
				GVariant* _tmp18_;
				GVariant* _tmp19_;
				GVariant* _tmp20_;
				const gchar* _tmp21_;
				gchar* _tmp22_;
				gchar* _tmp23_;
				gchar* desc = NULL;
				GVariant* _tmp24_;
				GVariant* _tmp25_;
				GVariant* _tmp26_;
				const gchar* _tmp27_;
				gchar* _tmp28_;
				gchar* _tmp29_;
				gint64 age = 0LL;
				GVariant* _tmp30_;
				GVariant* _tmp31_;
				GVariant* _tmp32_;
				gint64 _tmp33_;
				GVariant* obj_offline = NULL;
				GVariant* _tmp34_;
				GVariant* _tmp35_;
				gchar* msg_offline = NULL;
				GVariant* _tmp36_;
				GVariant* _tmp37_;
				GVariant* _tmp38_;
				const gchar* _tmp39_;
				gchar* _tmp40_;
				gchar* _tmp41_;
				gchar* timestamp_offline = NULL;
				GVariant* _tmp42_;
				GVariant* _tmp43_;
				GVariant* _tmp44_;
				const gchar* _tmp45_;
				gchar* _tmp46_;
				gchar* _tmp47_;
				UserData u1 = {0};
				gint64 _tmp48_;
				gint64 _tmp49_;
				const gchar* _tmp50_;
				gchar* _tmp51_;
				const gchar* _tmp52_;
				gchar* _tmp53_;
				gint64 _tmp54_;
				const gchar* _tmp55_;
				gchar* _tmp56_;
				const gchar* _tmp57_;
				gchar* _tmp58_;
				UserData _tmp59_ = {0};
				MyGrid* _tmp60_;
				UserData _tmp61_;
				if (!_tmp2_) {
					gsize _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = size1;
				if (!(_tmp4_ < _tmp5_)) {
					break;
				}
				_tmp6_ = i;
				_tmp7_ = g_variant_get_child_value (res, _tmp6_);
				_tmp8_ = _tmp7_;
				_tmp9_ = g_variant_get_child_value (_tmp8_, (gsize) 0);
				_g_variant_unref0 (val);
				val = _tmp9_;
				_g_variant_unref0 (_tmp8_);
				_tmp10_ = val;
				_tmp11_ = g_variant_lookup_value (_tmp10_, "Id", NULL);
				_tmp12_ = _tmp11_;
				_tmp13_ = g_variant_get_int64 (_tmp12_);
				_g_variant_unref0 (_tmp12_);
				id = _tmp13_;
				_tmp14_ = val;
				_tmp15_ = g_variant_lookup_value (_tmp14_, "Sex", NULL);
				_tmp16_ = _tmp15_;
				_tmp17_ = g_variant_get_int64 (_tmp16_);
				_g_variant_unref0 (_tmp16_);
				sex = _tmp17_;
				_tmp18_ = val;
				_tmp19_ = g_variant_lookup_value (_tmp18_, "Name", NULL);
				_tmp20_ = _tmp19_;
				_tmp21_ = g_variant_get_string (_tmp20_, NULL);
				_tmp22_ = g_strdup (_tmp21_);
				_tmp23_ = _tmp22_;
				_g_variant_unref0 (_tmp20_);
				name = _tmp23_;
				_tmp24_ = val;
				_tmp25_ = g_variant_lookup_value (_tmp24_, "Desc", NULL);
				_tmp26_ = _tmp25_;
				_tmp27_ = g_variant_get_string (_tmp26_, NULL);
				_tmp28_ = g_strdup (_tmp27_);
				_tmp29_ = _tmp28_;
				_g_variant_unref0 (_tmp26_);
				desc = _tmp29_;
				_tmp30_ = val;
				_tmp31_ = g_variant_lookup_value (_tmp30_, "Age", NULL);
				_tmp32_ = _tmp31_;
				_tmp33_ = g_variant_get_int64 (_tmp32_);
				_g_variant_unref0 (_tmp32_);
				age = _tmp33_;
				_tmp34_ = val;
				_tmp35_ = g_variant_lookup_value (_tmp34_, "MsgOffline", NULL);
				obj_offline = _tmp35_;
				_tmp36_ = obj_offline;
				_tmp37_ = g_variant_lookup_value (_tmp36_, "Msg", NULL);
				_tmp38_ = _tmp37_;
				_tmp39_ = g_variant_get_string (_tmp38_, NULL);
				_tmp40_ = g_strdup (_tmp39_);
				_tmp41_ = _tmp40_;
				_g_variant_unref0 (_tmp38_);
				msg_offline = _tmp41_;
				_tmp42_ = obj_offline;
				_tmp43_ = g_variant_lookup_value (_tmp42_, "Timestamp", NULL);
				_tmp44_ = _tmp43_;
				_tmp45_ = g_variant_get_string (_tmp44_, NULL);
				_tmp46_ = g_strdup (_tmp45_);
				_tmp47_ = _tmp46_;
				_g_variant_unref0 (_tmp44_);
				timestamp_offline = _tmp47_;
				_tmp48_ = id;
				_tmp49_ = sex;
				_tmp50_ = name;
				_tmp51_ = g_strdup (_tmp50_);
				_tmp52_ = desc;
				_tmp53_ = g_strdup (_tmp52_);
				_tmp54_ = age;
				_tmp55_ = msg_offline;
				_tmp56_ = g_strdup (_tmp55_);
				_tmp57_ = timestamp_offline;
				_tmp58_ = g_strdup (_tmp57_);
				_tmp59_.id = _tmp48_;
				_tmp59_.sex = (gint16) _tmp49_;
				_g_free0 (_tmp59_.name);
				_tmp59_.name = _tmp51_;
				_g_free0 (_tmp59_.desc);
				_tmp59_.desc = _tmp53_;
				_tmp59_.age = (gint16) _tmp54_;
				_g_free0 (_tmp59_.msg_offline);
				_tmp59_.msg_offline = _tmp56_;
				_g_free0 (_tmp59_.timestamp_offline);
				_tmp59_.timestamp_offline = _tmp58_;
				u1 = _tmp59_;
				_tmp60_ = grid1;
				_tmp61_ = u1;
				my_grid_add_friend (_tmp60_, &_tmp61_);
				user_data_destroy (&u1);
				_g_free0 (timestamp_offline);
				_g_free0 (msg_offline);
				_g_variant_unref0 (obj_offline);
				_g_free0 (desc);
				_g_free0 (name);
			}
		}
	}
	_g_variant_unref0 (val);
	_g_variant_unref0 (res);
}


static void
____lambda12__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda12_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_get_friends_async (RpcClient* self)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new_bytestring ("");
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.GetFriends", params, NULL, ____lambda12__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally8;
	__catch8_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally8:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


static void
___lambda19_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	JsonrpcClient* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void
____lambda19__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda19_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_ChatTo (RpcClient* self,
                   gint64 to,
                   const gchar* msg)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (msg != NULL, FALSE);
	_tmp0_ = g_variant_new_parsed ("{'To':<%i>,'Msg':<%s>}", to, msg, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.ChatTo", params, NULL, ____lambda19__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally9;
	__catch9_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally9:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


static void
___lambda13_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	JsonrpcClient* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void
____lambda13__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda13_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_tell (RpcClient* self,
                 gint64 to)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new ("(i)", to, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.Tell", params, NULL, ____lambda13__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally10;
	__catch10_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally10:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


static void
___lambda15_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	JsonrpcClient* _tmp0_;
	guint16 _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp1_ = server_port;
	_tmp2_ = g_strdup_printf ("%hu", _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat ("http://localhost:", _tmp3_, "/", NULL);
	_tmp5_ = _tmp4_;
	gtk_show_uri (NULL, _tmp5_, (guint32) GDK_CURRENT_TIME, &_inner_error_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void
____lambda15__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda15_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_set_http_id (RpcClient* self,
                        gint64 uid)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new ("(i)", uid, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.HttpConnect", params, NULL, ____lambda15__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally11;
	__catch11_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally11:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


static void
___lambda20_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	{
		JsonrpcClient* _tmp0_;
		_tmp0_ = self->c;
		jsonrpc_client_call_finish (_tmp0_, r, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch13_g_error;
		}
	}
	goto __finally13;
	__catch13_g_error:
	{
		GError* e = NULL;
		MyGrid* _tmp1_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp1_ = grid1;
		my_grid_add_text (_tmp1_, "[文件传送被阻止]", TRUE, FALSE);
		_g_error_free0 (e);
	}
	__finally13:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void
____lambda20__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda20_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_send_file (RpcClient* self,
                      gint64 to,
                      const gchar* pathname)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pathname != NULL, FALSE);
	_tmp0_ = g_variant_new_parsed ("{'To':<%i>,'PathName':<%s>}", to, pathname, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.SendFile", params, NULL, ____lambda20__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally12;
	__catch12_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "sendfile Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally12:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


gboolean
rpc_client_add_user (RpcClient* self,
                     const gchar* name,
                     const gchar* pwd,
                     gint sex,
                     gint birthyear,
                     const gchar* desc)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	GVariant* res = NULL;
	gboolean _tmp10_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (name != NULL, FALSE);
	g_return_val_if_fail (pwd != NULL, FALSE);
	g_return_val_if_fail (desc != NULL, FALSE);
	_tmp0_ = g_variant_new_parsed ("{'Name':<%s>,'Sex':<%i>,'Birth':<%i>,'Desc':<%s>,'Pwd':<%s>}", name, sex, birthyear, desc, pwd, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		gboolean ok = FALSE;
		JsonrpcClient* _tmp1_;
		GVariant* _tmp2_;
		GVariant* _tmp3_ = NULL;
		gboolean _tmp4_;
		gboolean _tmp5_;
		GVariant* _tmp6_;
		_tmp1_ = self->c;
		_tmp2_ = params;
		_tmp4_ = jsonrpc_client_call (_tmp1_, "PClient.NewUser", _tmp2_, NULL, &_tmp3_, &_inner_error_);
		_g_variant_unref0 (res);
		res = _tmp3_;
		ok = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch14_g_error;
		}
		_tmp5_ = ok;
		if (_tmp5_ == FALSE) {
			result = FALSE;
			_g_variant_unref0 (res);
			_g_variant_unref0 (params);
			return result;
		}
		_tmp6_ = res;
		if (g_variant_get_int64 (_tmp6_) == ((gint64) 1)) {
			result = TRUE;
			_g_variant_unref0 (res);
			_g_variant_unref0 (params);
			return result;
		} else {
			result = FALSE;
			_g_variant_unref0 (res);
			_g_variant_unref0 (params);
			return result;
		}
	}
	goto __finally14;
	__catch14_g_error:
	{
		GError* e = NULL;
		FILE* _tmp7_;
		GError* _tmp8_;
		const gchar* _tmp9_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp7_ = stdout;
		_tmp8_ = e;
		_tmp9_ = _tmp8_->message;
		fprintf (_tmp7_, "Error: %s\n", _tmp9_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		return result;
	}
	__finally14:
	_g_variant_unref0 (res);
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp10_;
}


static void
___lambda21_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	JsonrpcClient* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void
____lambda21__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda21_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_quit (RpcClient* self)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new_bytestring ("");
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.Quit", params, NULL, ____lambda21__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally15;
	__catch15_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally15:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


gboolean
rpc_client_get_proxy (RpcClient* self,
                      guint16* port)
{
	guint16 _vala_port = 0U;
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	GVariant* res = NULL;
	gboolean _tmp10_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new_bytestring ("");
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		gboolean ok = FALSE;
		JsonrpcClient* _tmp1_;
		GVariant* _tmp2_;
		GVariant* _tmp3_ = NULL;
		gboolean _tmp4_;
		gboolean _tmp5_;
		GVariant* _tmp6_;
		_tmp1_ = self->c;
		_tmp2_ = params;
		_tmp4_ = jsonrpc_client_call (_tmp1_, "PClient.GetProxyPort", _tmp2_, NULL, &_tmp3_, &_inner_error_);
		_g_variant_unref0 (res);
		res = _tmp3_;
		ok = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch16_g_error;
		}
		_tmp5_ = ok;
		if (_tmp5_ == FALSE) {
			result = FALSE;
			_g_variant_unref0 (res);
			_g_variant_unref0 (params);
			if (port) {
				*port = _vala_port;
			}
			return result;
		}
		_tmp6_ = res;
		_vala_port = (guint16) g_variant_get_int64 (_tmp6_);
		result = TRUE;
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		if (port) {
			*port = _vala_port;
		}
		return result;
	}
	goto __finally16;
	__catch16_g_error:
	{
		GError* e = NULL;
		FILE* _tmp7_;
		GError* _tmp8_;
		const gchar* _tmp9_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp7_ = stdout;
		_tmp8_ = e;
		_tmp9_ = _tmp8_->message;
		fprintf (_tmp7_, "Error: %s\n", _tmp9_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (res);
		_g_variant_unref0 (params);
		if (port) {
			*port = _vala_port;
		}
		return result;
	}
	__finally16:
	_g_variant_unref0 (res);
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp10_;
}


static void
___lambda22_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	GVariant* res = NULL;
	JsonrpcClient* _tmp0_;
	GVariant* _tmp1_ = NULL;
	MyGrid* _tmp2_;
	GtkEntry* _tmp3_;
	guint16 _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, &_tmp1_, &_inner_error_);
	_g_variant_unref0 (res);
	res = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_variant_unref0 (res);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	proxy_port = (guint16) g_variant_get_int64 (res);
	_tmp2_ = grid1;
	_tmp3_ = _tmp2_->port1;
	_tmp4_ = proxy_port;
	_tmp5_ = g_strdup_printf ("%hu", _tmp4_);
	_tmp6_ = _tmp5_;
	gtk_entry_set_text (_tmp3_, _tmp6_);
	_g_free0 (_tmp6_);
	_g_variant_unref0 (res);
}


static void
____lambda22__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda22_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_set_proxy (RpcClient* self,
                      guint16 port)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_variant_new ("(i)", port, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		_tmp1_ = self->c;
		jsonrpc_client_call_async (_tmp1_, "PClient.ProxyPort", params, NULL, ____lambda22__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally17;
	__catch17_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stdout;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "Error: %s\n", _tmp4_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally17:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp5_;
}


static void
___lambda18_ (RpcClient* self,
              GObject* s,
              GAsyncResult* r)
{
	JsonrpcClient* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void
____lambda18__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda18_ ((RpcClient*) self, source_object, res);
	g_object_unref (self);
}


gboolean
rpc_client_remove_friend (RpcClient* self,
                          gint64 fid)
{
	gboolean result = FALSE;
	GVariant* params = NULL;
	GVariant* _tmp0_;
	gboolean _tmp6_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	if (fid == ((gint64) 0)) {
		result = FALSE;
		return result;
	}
	_tmp0_ = g_variant_new ("(i)", fid, NULL);
	g_variant_ref_sink (_tmp0_);
	params = _tmp0_;
	{
		JsonrpcClient* _tmp1_;
		GVariant* _tmp2_;
		_tmp1_ = self->c;
		_tmp2_ = params;
		jsonrpc_client_call_async (_tmp1_, "PClient.RemoveFriend", _tmp2_, NULL, ____lambda18__gasync_ready_callback, g_object_ref (self));
		result = TRUE;
		_g_variant_unref0 (params);
		return result;
	}
	goto __finally18;
	__catch18_g_error:
	{
		GError* e = NULL;
		FILE* _tmp3_;
		GError* _tmp4_;
		const gchar* _tmp5_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp3_ = stdout;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		fprintf (_tmp3_, "Error: %s\n", _tmp5_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		return result;
	}
	__finally18:
	_g_variant_unref0 (params);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp6_;
}


static Block7Data*
block7_data_ref (Block7Data* _data7_)
{
	g_atomic_int_inc (&_data7_->_ref_count_);
	return _data7_;
}


static void
block7_data_unref (void * _userdata_)
{
	Block7Data* _data7_;
	_data7_ = (Block7Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data7_->_ref_count_)) {
		RpcClient* self;
		self = _data7_->self;
		_g_free0 (_data7_->msg);
		_g_object_unref0 (self);
		g_slice_free (Block7Data, _data7_);
	}
}


static void
___lambda23_ (Block7Data* _data7_,
              GObject* s,
              GAsyncResult* r)
{
	RpcClient* self;
	GVariant* res = NULL;
	JsonrpcClient* _tmp0_;
	GVariant* _tmp1_ = NULL;
	gint64 id = 0LL;
	GVariant* _tmp2_;
	GVariant* _tmp3_;
	gint64 _tmp4_;
	gchar* name = NULL;
	GVariant* _tmp5_;
	GVariant* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gint16 age = 0;
	GVariant* _tmp10_;
	GVariant* _tmp11_;
	gint16 _tmp12_;
	gint16 sex = 0;
	GVariant* _tmp13_;
	GVariant* _tmp14_;
	gint16 _tmp15_;
	gchar* desc = NULL;
	GVariant* _tmp16_;
	GVariant* _tmp17_;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	GDateTime* tm1 = NULL;
	GDateTime* _tmp21_;
	UserData u = {0};
	gint64 _tmp22_;
	gint16 _tmp23_;
	const gchar* _tmp24_;
	gchar* _tmp25_;
	const gchar* _tmp26_;
	gchar* _tmp27_;
	gint16 _tmp28_;
	gchar* _tmp29_;
	GDateTime* _tmp30_;
	gchar* _tmp31_;
	UserData _tmp32_ = {0};
	UserData _tmp33_;
	GError * _inner_error_ = NULL;
	self = _data7_->self;
	g_return_if_fail (r != NULL);
	_tmp0_ = self->c;
	jsonrpc_client_call_finish (_tmp0_, r, &_tmp1_, &_inner_error_);
	_g_variant_unref0 (res);
	res = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_variant_unref0 (res);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = g_variant_lookup_value (res, "Id", NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_variant_get_int64 (_tmp3_);
	_g_variant_unref0 (_tmp3_);
	id = _tmp4_;
	_tmp5_ = g_variant_lookup_value (res, "Name", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_variant_get_string (_tmp6_, NULL);
	_tmp8_ = g_strdup (_tmp7_);
	_tmp9_ = _tmp8_;
	_g_variant_unref0 (_tmp6_);
	name = _tmp9_;
	_tmp10_ = g_variant_lookup_value (res, "Age", NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = (gint16) g_variant_get_int64 (_tmp11_);
	_g_variant_unref0 (_tmp11_);
	age = _tmp12_;
	_tmp13_ = g_variant_lookup_value (res, "Sex", NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = (gint16) g_variant_get_int64 (_tmp14_);
	_g_variant_unref0 (_tmp14_);
	sex = _tmp15_;
	_tmp16_ = g_variant_lookup_value (res, "Desc", NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_variant_get_string (_tmp17_, NULL);
	_tmp19_ = g_strdup (_tmp18_);
	_tmp20_ = _tmp19_;
	_g_variant_unref0 (_tmp17_);
	desc = _tmp20_;
	_tmp21_ = g_date_time_new_now_local ();
	tm1 = _tmp21_;
	_tmp22_ = id;
	_tmp23_ = sex;
	_tmp24_ = name;
	_tmp25_ = g_strdup (_tmp24_);
	_tmp26_ = desc;
	_tmp27_ = g_strdup (_tmp26_);
	_tmp28_ = age;
	_tmp29_ = g_strdup (_data7_->msg);
	_tmp30_ = tm1;
	_tmp31_ = g_date_time_format (_tmp30_, "%Y-%m-%d %H:%M:%S");
	_tmp32_.id = _tmp22_;
	_tmp32_.sex = _tmp23_;
	_g_free0 (_tmp32_.name);
	_tmp32_.name = _tmp25_;
	_g_free0 (_tmp32_.desc);
	_tmp32_.desc = _tmp27_;
	_tmp32_.age = _tmp28_;
	_g_free0 (_tmp32_.msg_offline);
	_tmp32_.msg_offline = _tmp29_;
	_g_free0 (_tmp32_.timestamp_offline);
	_tmp32_.timestamp_offline = _tmp31_;
	u = _tmp32_;
	_tmp33_ = u;
	_data7_->f (&_tmp33_, _data7_->f_target);
	user_data_destroy (&u);
	_g_date_time_unref0 (tm1);
	_g_free0 (desc);
	_g_free0 (name);
	_g_variant_unref0 (res);
}


static void
____lambda23__gasync_ready_callback (GObject* source_object,
                                     GAsyncResult* res,
                                     gpointer self)
{
	___lambda23_ (self, source_object, res);
	block7_data_unref (self);
}


gboolean
rpc_client_offline_msg_with_id (RpcClient* self,
                                gint64 uid,
                                const gchar* msg,
                                RpcClientQueryCallback f,
                                gpointer f_target)
{
	gboolean result = FALSE;
	Block7Data* _data7_;
	gchar* _tmp0_;
	GVariant* params = NULL;
	GVariant* _tmp1_;
	gboolean _tmp7_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (msg != NULL, FALSE);
	_data7_ = g_slice_new0 (Block7Data);
	_data7_->_ref_count_ = 1;
	_data7_->self = g_object_ref (self);
	_tmp0_ = g_strdup (msg);
	_g_free0 (_data7_->msg);
	_data7_->msg = _tmp0_;
	_data7_->f = f;
	_data7_->f_target = f_target;
	if (uid == ((gint64) 0)) {
		result = FALSE;
		block7_data_unref (_data7_);
		_data7_ = NULL;
		return result;
	}
	_tmp1_ = g_variant_new ("(i)", uid, NULL);
	g_variant_ref_sink (_tmp1_);
	params = _tmp1_;
	{
		JsonrpcClient* _tmp2_;
		GVariant* _tmp3_;
		_tmp2_ = self->c;
		_tmp3_ = params;
		jsonrpc_client_call_async (_tmp2_, "PClient.QueryID", _tmp3_, NULL, ____lambda23__gasync_ready_callback, block7_data_ref (_data7_));
		result = TRUE;
		_g_variant_unref0 (params);
		block7_data_unref (_data7_);
		_data7_ = NULL;
		return result;
	}
	goto __finally19;
	__catch19_g_error:
	{
		GError* e = NULL;
		FILE* _tmp4_;
		GError* _tmp5_;
		const gchar* _tmp6_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stdout;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "Error: %s\n", _tmp6_);
		result = FALSE;
		_g_error_free0 (e);
		_g_variant_unref0 (params);
		block7_data_unref (_data7_);
		_data7_ = NULL;
		return result;
	}
	__finally19:
	_g_variant_unref0 (params);
	block7_data_unref (_data7_);
	_data7_ = NULL;
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return _tmp7_;
}


RpcClient*
rpc_client_construct (GType object_type)
{
	RpcClient * self = NULL;
	self = (RpcClient*) g_object_new (object_type, NULL);
	return self;
}


RpcClient*
rpc_client_new (void)
{
	return rpc_client_construct (TYPE_RPC_CLIENT);
}


gint
rpc_client_get_counter (RpcClient* self)
{
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_counter;
	result = _tmp0_;
	return result;
}


void
rpc_client_set_counter (RpcClient* self,
                        gint value)
{
	g_return_if_fail (self != NULL);
	if (rpc_client_get_counter (self) != value) {
		self->priv->_counter = value;
		g_object_notify_by_pspec ((GObject *) self, rpc_client_properties[RPC_CLIENT_COUNTER_PROPERTY]);
	}
}


static void
rpc_client_class_init (RpcClientClass * klass)
{
	rpc_client_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (RpcClientPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_rpc_client_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_rpc_client_set_property;
	G_OBJECT_CLASS (klass)->finalize = rpc_client_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), RPC_CLIENT_COUNTER_PROPERTY, rpc_client_properties[RPC_CLIENT_COUNTER_PROPERTY] = g_param_spec_int ("counter", "counter", "counter", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void
rpc_client_instance_init (RpcClient * self)
{
	self->priv = RPC_CLIENT_GET_PRIVATE (self);
	self->priv->_counter = 0;
}


static void
rpc_client_finalize (GObject * obj)
{
	RpcClient * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_RPC_CLIENT, RpcClient);
	_g_object_unref0 (self->c);
	G_OBJECT_CLASS (rpc_client_parent_class)->finalize (obj);
}


GType
rpc_client_get_type (void)
{
	static volatile gsize rpc_client_type_id__volatile = 0;
	if (g_once_init_enter (&rpc_client_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RpcClientClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rpc_client_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RpcClient), 0, (GInstanceInitFunc) rpc_client_instance_init, NULL };
		GType rpc_client_type_id;
		rpc_client_type_id = g_type_register_static (G_TYPE_OBJECT, "RpcClient", &g_define_type_info, 0);
		g_once_init_leave (&rpc_client_type_id__volatile, rpc_client_type_id);
	}
	return rpc_client_type_id__volatile;
}


static void
_vala_rpc_client_get_property (GObject * object,
                               guint property_id,
                               GValue * value,
                               GParamSpec * pspec)
{
	RpcClient * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_RPC_CLIENT, RpcClient);
	switch (property_id) {
		case RPC_CLIENT_COUNTER_PROPERTY:
		g_value_set_int (value, rpc_client_get_counter (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void
_vala_rpc_client_set_property (GObject * object,
                               guint property_id,
                               const GValue * value,
                               GParamSpec * pspec)
{
	RpcClient * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_RPC_CLIENT, RpcClient);
	switch (property_id) {
		case RPC_CLIENT_COUNTER_PROPERTY:
		rpc_client_set_counter (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



