/* search.c generated by valac 0.40.8, the Vala compiler
 * generated from search.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define TYPE_SEARCH_DIALG (search_dialg_get_type ())
#define SEARCH_DIALG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SEARCH_DIALG, SearchDialg))
#define SEARCH_DIALG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SEARCH_DIALG, SearchDialgClass))
#define IS_SEARCH_DIALG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SEARCH_DIALG))
#define IS_SEARCH_DIALG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SEARCH_DIALG))
#define SEARCH_DIALG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SEARCH_DIALG, SearchDialgClass))

typedef struct _SearchDialg SearchDialg;
typedef struct _SearchDialgClass SearchDialgClass;

#define TYPE_USER_DATA (user_data_get_type ())
typedef struct _UserData UserData;
typedef struct _SearchDialgPrivate SearchDialgPrivate;
enum  {
	SEARCH_DIALG_0_PROPERTY,
	SEARCH_DIALG_NUM_PROPERTIES
};
static GParamSpec* search_dialg_properties[SEARCH_DIALG_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_APP_WIN (app_win_get_type ())
#define APP_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APP_WIN, AppWin))
#define APP_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APP_WIN, AppWinClass))
#define IS_APP_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APP_WIN))
#define IS_APP_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APP_WIN))
#define APP_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APP_WIN, AppWinClass))

typedef struct _AppWin AppWin;
typedef struct _AppWinClass AppWinClass;

#define TYPE_RPC_CLIENT (rpc_client_get_type ())
#define RPC_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RPC_CLIENT, RpcClient))
#define RPC_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RPC_CLIENT, RpcClientClass))
#define IS_RPC_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RPC_CLIENT))
#define IS_RPC_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RPC_CLIENT))
#define RPC_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RPC_CLIENT, RpcClientClass))

typedef struct _RpcClient RpcClient;
typedef struct _RpcClientClass RpcClientClass;

#define TYPE_MY_GRID (my_grid_get_type ())
#define MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_GRID, MyGrid))
#define MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_GRID, MyGridClass))
#define IS_MY_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_GRID))
#define IS_MY_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_GRID))
#define MY_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_GRID, MyGridClass))

typedef struct _MyGrid MyGrid;
typedef struct _MyGridClass MyGridClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _UserData {
	gint64 id;
	gint16 sex;
	gchar* name;
	gchar* desc;
	gint16 age;
	gchar* msg_offline;
	gchar* timestamp_offline;
};

typedef void (*SearchCallback) (UserData* user1, gpointer user_data);
struct _SearchDialg {
	GObject parent_instance;
	SearchDialgPrivate * priv;
	GtkDialog* dlg1;
	GtkEntry* key1;
	GtkListStore* store1;
	GList* persons;
};

struct _SearchDialgClass {
	GObjectClass parent_class;
};


extern SearchDialg* search1;
SearchDialg* search1 = NULL;
static gpointer search_dialg_parent_class = NULL;
extern AppWin* app;
extern RpcClient* rpc1;
extern MyGrid* grid1;

GType search_dialg_get_type (void) G_GNUC_CONST;
GType user_data_get_type (void) G_GNUC_CONST;
UserData* user_data_dup (const UserData* self);
void user_data_free (UserData* self);
void user_data_copy (const UserData* self,
                     UserData* dest);
void user_data_destroy (UserData* self);
static void _user_data_free0_ (gpointer var);
static inline void _g_list_free__user_data_free0_ (GList* self);
SearchDialg* search_dialg_new (void);
SearchDialg* search_dialg_construct (GType object_type);
GType app_win_get_type (void) G_GNUC_CONST;
void search_dialg_search (SearchDialg* self);
static void _search_dialg_search_gtk_button_clicked (GtkButton* _sender,
                                              gpointer self);
static void __lambda30_ (SearchDialg* self,
                  gint rid);
static void ___lambda30__gtk_dialog_response (GtkDialog* _sender,
                                       gint response_id,
                                       gpointer self);
static void __lambda31_ (SearchDialg* self,
                  GtkTreeView* tree,
                  GtkTreePath* path,
                  GtkTreeViewColumn* col);
GType rpc_client_get_type (void) G_GNUC_CONST;
gboolean rpc_client_add_friend (RpcClient* self,
                                gint64 uid);
GType my_grid_get_type (void) G_GNUC_CONST;
void my_grid_add_friend (MyGrid* self,
                         UserData* user1);
gboolean rpc_client_tell (RpcClient* self,
                          gint64 to);
static void ___lambda31__gtk_tree_view_row_activated (GtkTreeView* _sender,
                                               GtkTreePath* path,
                                               GtkTreeViewColumn* column,
                                               gpointer self);
void search_dialg_add_row (SearchDialg* self,
                           UserData* u1);
void search_dialg_seach_callback (SearchDialg* self,
                                  UserData* u);
gboolean rpc_client_search_person_async (RpcClient* self,
                                         const gchar* key,
                                         SearchCallback f,
                                         gpointer f_target);
static void _search_dialg_seach_callback_search_callback (UserData* user1,
                                                   gpointer self);
void search_dialg_show (SearchDialg* self);
static void search_dialg_finalize (GObject * obj);


static void
_user_data_free0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (user_data_free (var), NULL));
}


static inline void
_g_list_free__user_data_free0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _user_data_free0_);
}


static void
_search_dialg_search_gtk_button_clicked (GtkButton* _sender,
                                         gpointer self)
{
	search_dialg_search ((SearchDialg*) self);
}


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


static void
__lambda30_ (SearchDialg* self,
             gint rid)
{
	GtkDialog* _tmp0_;
	_tmp0_ = self->dlg1;
	g_signal_emit_by_name (_tmp0_, "close");
}


static void
___lambda30__gtk_dialog_response (GtkDialog* _sender,
                                  gint response_id,
                                  gpointer self)
{
	__lambda30_ ((SearchDialg*) self, response_id);
}


static void
__lambda31_ (SearchDialg* self,
             GtkTreeView* tree,
             GtkTreePath* path,
             GtkTreeViewColumn* col)
{
	GtkTreeIter iter = {0};
	GtkTreeModel* model = NULL;
	GtkTreeModel* _tmp0_;
	GtkTreeModel* _tmp1_;
	GtkTreeModel* _tmp2_;
	GtkTreeIter _tmp3_ = {0};
	GValue idv = {0};
	GValue _tmp4_ = {0};
	GtkTreeModel* _tmp5_;
	GtkTreeIter _tmp6_;
	GValue _tmp7_ = {0};
	gint64 id = 0LL;
	RpcClient* _tmp8_;
	gint64 _tmp9_;
	GList* _tmp10_;
	g_return_if_fail (tree != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (col != NULL);
	_tmp0_ = gtk_tree_view_get_model (tree);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	model = _tmp1_;
	_tmp2_ = model;
	gtk_tree_model_get_iter (_tmp2_, &_tmp3_, path);
	iter = _tmp3_;
	g_value_init (&_tmp4_, G_TYPE_INT64);
	idv = _tmp4_;
	_tmp5_ = model;
	_tmp6_ = iter;
	gtk_tree_model_get_value (_tmp5_, &_tmp6_, 0, &_tmp7_);
	G_IS_VALUE (&idv) ? (g_value_unset (&idv), NULL) : NULL;
	idv = _tmp7_;
	id = g_value_get_int64 (&idv);
	_tmp8_ = rpc1;
	_tmp9_ = id;
	rpc_client_add_friend (_tmp8_, _tmp9_);
	_tmp10_ = self->persons;
	{
		GList* u_collection = NULL;
		GList* u_it = NULL;
		u_collection = _tmp10_;
		for (u_it = u_collection; u_it != NULL; u_it = u_it->next) {
			UserData _tmp11_ = {0};
			UserData u = {0};
			user_data_copy ((UserData*) u_it->data, &_tmp11_);
			u = _tmp11_;
			{
				UserData _tmp12_;
				gint64 _tmp13_;
				gint64 _tmp14_;
				_tmp12_ = u;
				_tmp13_ = _tmp12_.id;
				_tmp14_ = id;
				if (_tmp13_ == _tmp14_) {
					MyGrid* _tmp15_;
					UserData _tmp16_;
					RpcClient* _tmp17_;
					gint64 _tmp18_;
					_tmp15_ = grid1;
					_tmp16_ = u;
					my_grid_add_friend (_tmp15_, &_tmp16_);
					_tmp17_ = rpc1;
					_tmp18_ = id;
					rpc_client_tell (_tmp17_, _tmp18_);
				}
				user_data_destroy (&u);
			}
		}
	}
	G_IS_VALUE (&idv) ? (g_value_unset (&idv), NULL) : NULL;
	_g_object_unref0 (model);
}


static void
___lambda31__gtk_tree_view_row_activated (GtkTreeView* _sender,
                                          GtkTreePath* path,
                                          GtkTreeViewColumn* column,
                                          gpointer self)
{
	__lambda31_ ((SearchDialg*) self, _sender, path, column);
}


SearchDialg*
search_dialg_construct (GType object_type)
{
	SearchDialg * self = NULL;
	AppWin* _tmp0_;
	GtkDialog* _tmp1_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp2_;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
	GtkEntry* _tmp5_;
	GtkEntry* _tmp6_;
	GtkButton* b1 = NULL;
	GtkButton* _tmp7_;
	GtkListStore* _tmp8_;
	GtkTreeView* view = NULL;
	GtkListStore* _tmp9_;
	GtkTreeView* _tmp10_;
	GtkCellRendererText* _tmp11_;
	GtkCellRendererText* _tmp12_;
	GtkCellRendererText* _tmp13_;
	GtkCellRendererText* _tmp14_;
	GtkCellRendererText* _tmp15_;
	GtkCellRendererText* _tmp16_;
	GtkCellRendererText* _tmp17_;
	GtkCellRendererText* _tmp18_;
	GtkCellRendererText* _tmp19_;
	GtkCellRendererText* _tmp20_;
	GtkScrolledWindow* scroll1 = NULL;
	GtkScrolledWindow* _tmp21_;
	GtkBox* content = NULL;
	GtkDialog* _tmp22_;
	GtkBox* _tmp23_;
	GtkBox* _tmp24_;
	GtkDialog* _tmp25_;
	GtkDialog* _tmp26_;
	self = (SearchDialg*) g_object_new (object_type, NULL);
	_tmp0_ = app;
	_tmp1_ = (GtkDialog*) gtk_dialog_new_with_buttons ("找人", (GtkWindow*) _tmp0_, GTK_DIALOG_MODAL, NULL);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->dlg1);
	self->dlg1 = _tmp1_;
	_tmp2_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp2_);
	grid = _tmp2_;
	_tmp3_ = (GtkLabel*) gtk_label_new ("名字(部分)：");
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	gtk_grid_attach (grid, (GtkWidget*) _tmp4_, 0, 0, 1, 1);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->key1);
	self->key1 = _tmp5_;
	_tmp6_ = self->key1;
	gtk_grid_attach (grid, (GtkWidget*) _tmp6_, 1, 0, 1, 1);
	_tmp7_ = (GtkButton*) gtk_button_new_with_label ("搜索");
	g_object_ref_sink (_tmp7_);
	b1 = _tmp7_;
	gtk_grid_attach (grid, (GtkWidget*) b1, 2, 0, 1, 1);
	g_signal_connect_object (b1, "clicked", (GCallback) _search_dialg_search_gtk_button_clicked, self, 0);
	_tmp8_ = gtk_list_store_new (5, G_TYPE_INT64, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_INT, G_TYPE_STRING, -1);
	_g_object_unref0 (self->store1);
	self->store1 = _tmp8_;
	_tmp9_ = self->store1;
	_tmp10_ = (GtkTreeView*) gtk_tree_view_new_with_model ((GtkTreeModel*) _tmp9_);
	g_object_ref_sink (_tmp10_);
	view = _tmp10_;
	_tmp11_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp11_);
	_tmp12_ = _tmp11_;
	gtk_tree_view_insert_column_with_attributes (view, 0, "ID", (GtkCellRenderer*) _tmp12_, "text", 0, NULL);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp13_);
	_tmp14_ = _tmp13_;
	gtk_tree_view_insert_column_with_attributes (view, 1, "名称", (GtkCellRenderer*) _tmp14_, "text", 1, NULL);
	_g_object_unref0 (_tmp14_);
	_tmp15_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp15_);
	_tmp16_ = _tmp15_;
	gtk_tree_view_insert_column_with_attributes (view, 2, "性别", (GtkCellRenderer*) _tmp16_, "text", 2, NULL);
	_g_object_unref0 (_tmp16_);
	_tmp17_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp17_);
	_tmp18_ = _tmp17_;
	gtk_tree_view_insert_column_with_attributes (view, 3, "年龄", (GtkCellRenderer*) _tmp18_, "text", 3, NULL);
	_g_object_unref0 (_tmp18_);
	_tmp19_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp19_);
	_tmp20_ = _tmp19_;
	gtk_tree_view_insert_column_with_attributes (view, 4, "自述", (GtkCellRenderer*) _tmp20_, "text", 4, NULL);
	_g_object_unref0 (_tmp20_);
	gtk_tree_view_set_headers_visible (view, TRUE);
	gtk_widget_show_all ((GtkWidget*) view);
	_tmp21_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp21_);
	scroll1 = _tmp21_;
	gtk_container_add ((GtkContainer*) scroll1, (GtkWidget*) view);
	g_object_set ((GtkWidget*) view, "expand", TRUE, NULL);
	g_object_set ((GtkWidget*) scroll1, "expand", TRUE, NULL);
	gtk_widget_set_size_request ((GtkWidget*) scroll1, 250, 250);
	gtk_grid_attach (grid, (GtkWidget*) scroll1, 0, 1, 3, 1);
	_tmp22_ = self->dlg1;
	_tmp23_ = gtk_dialog_get_content_area (_tmp22_);
	_tmp24_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp23_, gtk_box_get_type ()) ? ((GtkBox*) _tmp23_) : NULL);
	content = _tmp24_;
	gtk_box_pack_start (content, (GtkWidget*) grid, TRUE, TRUE, (guint) 0);
	_tmp25_ = self->dlg1;
	gtk_dialog_add_button (_tmp25_, "关闭", 2);
	_tmp26_ = self->dlg1;
	g_signal_connect_object (_tmp26_, "response", (GCallback) ___lambda30__gtk_dialog_response, self, 0);
	g_signal_connect_object (view, "row-activated", (GCallback) ___lambda31__gtk_tree_view_row_activated, self, 0);
	_g_object_unref0 (content);
	_g_object_unref0 (scroll1);
	_g_object_unref0 (view);
	_g_object_unref0 (b1);
	_g_object_unref0 (grid);
	return self;
}


SearchDialg*
search_dialg_new (void)
{
	return search_dialg_construct (TYPE_SEARCH_DIALG);
}


void
search_dialg_add_row (SearchDialg* self,
                      UserData* u1)
{
	GtkTreeIter iter = {0};
	GtkListStore* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gchar* sex = NULL;
	gchar* _tmp2_;
	UserData _tmp3_;
	gint16 _tmp4_;
	GtkListStore* _tmp9_;
	GtkTreeIter _tmp10_;
	UserData _tmp11_;
	gint64 _tmp12_;
	UserData _tmp13_;
	const gchar* _tmp14_;
	const gchar* _tmp15_;
	UserData _tmp16_;
	gint16 _tmp17_;
	UserData _tmp18_;
	const gchar* _tmp19_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (u1 != NULL);
	_tmp0_ = self->store1;
	gtk_list_store_append (_tmp0_, &_tmp1_);
	iter = _tmp1_;
	_tmp2_ = g_strdup ("不明");
	sex = _tmp2_;
	_tmp3_ = *u1;
	_tmp4_ = _tmp3_.sex;
	if (((gint) _tmp4_) == 1) {
		gchar* _tmp5_;
		_tmp5_ = g_strdup ("男");
		_g_free0 (sex);
		sex = _tmp5_;
	} else {
		UserData _tmp6_;
		gint16 _tmp7_;
		_tmp6_ = *u1;
		_tmp7_ = _tmp6_.sex;
		if (((gint) _tmp7_) == 2) {
			gchar* _tmp8_;
			_tmp8_ = g_strdup ("女");
			_g_free0 (sex);
			sex = _tmp8_;
		}
	}
	_tmp9_ = self->store1;
	_tmp10_ = iter;
	_tmp11_ = *u1;
	_tmp12_ = _tmp11_.id;
	_tmp13_ = *u1;
	_tmp14_ = _tmp13_.name;
	_tmp15_ = sex;
	_tmp16_ = *u1;
	_tmp17_ = _tmp16_.age;
	_tmp18_ = *u1;
	_tmp19_ = _tmp18_.desc;
	gtk_list_store_set (_tmp9_, &_tmp10_, 0, _tmp12_, 1, _tmp14_, 2, _tmp15_, 3, _tmp17_, 4, _tmp19_, -1);
	_g_free0 (sex);
}


static gpointer
_user_data_dup0 (gpointer self)
{
	return self ? user_data_dup (self) : NULL;
}


void
search_dialg_seach_callback (SearchDialg* self,
                             UserData* u)
{
	UserData _tmp0_;
	UserData _tmp1_;
	UserData _tmp2_;
	UserData* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (u != NULL);
	_tmp0_ = *u;
	search_dialg_add_row (self, &_tmp0_);
	_tmp1_ = *u;
	_tmp2_ = _tmp1_;
	_tmp3_ = _user_data_dup0 (&_tmp2_);
	self->persons = g_list_append (self->persons, _tmp3_);
}


static void
_search_dialg_seach_callback_search_callback (UserData* user1,
                                              gpointer self)
{
	search_dialg_seach_callback ((SearchDialg*) self, user1);
}


void
search_dialg_search (SearchDialg* self)
{
	GtkListStore* _tmp0_;
	RpcClient* _tmp1_;
	GtkEntry* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->store1;
	gtk_list_store_clear (_tmp0_);
	(self->persons == NULL) ? NULL : (self->persons = (_g_list_free__user_data_free0_ (self->persons), NULL));
	self->persons = NULL;
	_tmp1_ = rpc1;
	_tmp2_ = self->key1;
	_tmp3_ = gtk_entry_get_text (_tmp2_);
	_tmp4_ = _tmp3_;
	rpc_client_search_person_async (_tmp1_, _tmp4_, _search_dialg_seach_callback_search_callback, self);
}


void
search_dialg_show (SearchDialg* self)
{
	GtkDialog* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->dlg1;
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
}


static void
search_dialg_class_init (SearchDialgClass * klass)
{
	search_dialg_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = search_dialg_finalize;
}


static void
search_dialg_instance_init (SearchDialg * self)
{
}


static void
search_dialg_finalize (GObject * obj)
{
	SearchDialg * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SEARCH_DIALG, SearchDialg);
	_g_object_unref0 (self->dlg1);
	_g_object_unref0 (self->key1);
	_g_object_unref0 (self->store1);
	(self->persons == NULL) ? NULL : (self->persons = (_g_list_free__user_data_free0_ (self->persons), NULL));
	G_OBJECT_CLASS (search_dialg_parent_class)->finalize (obj);
}


GType
search_dialg_get_type (void)
{
	static volatile gsize search_dialg_type_id__volatile = 0;
	if (g_once_init_enter (&search_dialg_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SearchDialgClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) search_dialg_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SearchDialg), 0, (GInstanceInitFunc) search_dialg_instance_init, NULL };
		GType search_dialg_type_id;
		search_dialg_type_id = g_type_register_static (G_TYPE_OBJECT, "SearchDialg", &g_define_type_info, 0);
		g_once_init_leave (&search_dialg_type_id__volatile, search_dialg_type_id);
	}
	return search_dialg_type_id__volatile;
}



